Repository kubeovn/kube-ovn, pull requests merged in 2020-07, with the labels that each got.

#395 perf: use policy-route to replace src-ip route
  pkg/controller/controller.go
  pkg/controller/gc.go
  pkg/controller/init.go
  pkg/controller/node.go
  pkg/controller/pod.go
  pkg/controller/subnet.go
  pkg/ovs/ovn-nbctl.go
  pkg/speaker/pod.go
  pkg/util/const.go
  test/e2e/ip/static_ip.go
Labels: performance

#396 feat: support gw qos
  pkg/daemon/controller.go
  pkg/daemon/gateway.go
  pkg/daemon/ovs.go
  pkg/ovs/ovs-vsctl.go
Labels: feature

#394 Solve the problem of non-standard statefulset creation mode
  pkg/controller/pod.go
Labels: bug

#397 fix: ipv6 policy route
  pkg/controller/node.go
  pkg/controller/subnet.go
Labels: bug

#398 test: statefulset without ippool
  Makefile
  test/e2e/ip/static_ip.go
Labels: test

#399 fix: reset address_set when delete subnet
  pkg/controller/subnet.go
Labels: bug

#403 feat: session service
  pkg/controller/config.go
  pkg/controller/endpoint.go
  pkg/controller/gc.go
  pkg/controller/init.go
  pkg/controller/service.go
  pkg/ovs/ovn-nbctl.go
Labels: feature

#410 fix: available ips calculation issues
  pkg/controller/subnet.go
  pkg/ipam/ipam.go
  pkg/ipam/subnet.go
  pkg/ovs/util.go
  pkg/util/net.go
  test/e2e/subnet/normal.go
Labels: bug

#411 chore: check ovn-sb connectivity from ovn-ovs probe
  dist/images/ovs-dpdk-healthcheck.sh
  dist/images/ovs-healthcheck.sh
Labels: enhancement

#413 fix: set qlen for ovn0
  pkg/daemon/ovs.go
Labels: bug

#414 chore: use j2 to render different kind.yaml
  .github/workflows/build-x86-image.yaml
  Makefile
  docs/development.md
  get_helm.sh
  yamls/kind-single.yaml
  yamls/kind.yaml.j2
Labels: enhancement

#415 ci: save ci time
  .github/workflows/build-x86-image.yaml
  Makefile
  dist/images/install.sh
  dist/images/start-ovs.sh
Labels: enhancement

#416 ci: modify cache usage
  .github/workflows/build-x86-image.yaml
Labels: ci

#417 feat: recycle lsp at runtime
  pkg/controller/controller.go
  pkg/controller/gc.go
Labels: feature

#418 ci: add ipv6 install e2e
  .github/workflows/build-x86-image.yaml
  Makefile
  dist/images/install.sh
  pkg/pinger/config.go
Labels: ci

#419 chore: add logs to sriov interface
  pkg/daemon/ovs.go
Labels: enhancement

#420 ci: add arm build to normal ci process
  .github/workflows/build-arm64-image.yaml
Labels: ci

#421 feat: assign a pod as the gw
  pkg/controller/gc.go
  pkg/controller/node.go
  pkg/controller/pod.go
  pkg/controller/subnet.go
  pkg/ovs/ovn-nbctl.go
  pkg/util/const.go
Labels: feature

#422 fix: use keymutex to serialize pod add/delete operation
  go.mod
  go.sum
  pkg/controller/controller.go
  pkg/controller/pod.go
  vendor/github.com/neverlee/keymutex/LICENSE
  vendor/github.com/neverlee/keymutex/README.md
  vendor/github.com/neverlee/keymutex/hashs.go
  vendor/github.com/neverlee/keymutex/keymutex.go
  vendor/modules.txt
Labels: bug

#424 fix: if sriov device, do not delete the host nic
  cmd/cni/cni.go
  pkg/daemon/handler.go
  pkg/daemon/ovs.go
Labels: bug

#425 docs: add hw-offload docs and resolve some issues
  dist/images/start-ovs.sh
  docs/hw-offload.md
  pkg/daemon/handler.go
  pkg/util/const.go
Labels: bug, docs

#426 chore: optimize dpdk build
  .github/workflows/build-arm64-image.yaml
  .github/workflows/build-dpdk-image.yaml
  .github/workflows/build-x86-image.yaml
  CHANGELOG.md
  Makefile
  dist/images/Dockerfile.dpdk1911
  dist/images/install.sh
Labels: enhancement

#427 dpdk: add kmod, pdump and proc-info tools
  dist/images/Dockerfile.dpdk1911
Labels: enhancement

#430 release: update 1.3.0 docs
  CHANGELOG.md
  README.md
  docs/dpdk.md
  docs/high-available.md
  docs/hw-offload.md
  docs/install.md
  docs/ipv6.md
  docs/pod-gw.md
  docs/vlan.md
Labels: docs
