Repository kubeovn/kube-ovn, pull requests merged in 2020-04, with the labels that each got.

#289 fix: remove auto checksums
  dist/images/install.sh
  docs/install.md
  pkg/daemon/config.go
Labels: bug

#290 feat: expose iface in install.sh
  dist/images/install.sh
Labels: enhancement

#291 fix: acl and qos issues
  pkg/daemon/controller.go
  pkg/ovs/ovn-nbctl.go
Labels: bug

#294 test: add node test
  pkg/util/net.go
  pkg/util/validator.go
  test/e2e/e2e_suite_test.go
  test/e2e/ip/static_ip.go
  test/e2e/node/node.go
Labels: test

#296 test: check host route when add/del a subnet
  go.mod
  go.sum
  pkg/util/validator.go
  test/e2e/framework/framework.go
  test/e2e/subnet/normal.go
  vendor/github.com/docker/spdystream/CONTRIBUTING.md
  vendor/github.com/docker/spdystream/LICENSE
  vendor/github.com/docker/spdystream/LICENSE.docs
  vendor/github.com/docker/spdystream/MAINTAINERS
  vendor/github.com/docker/spdystream/README.md
  vendor/github.com/docker/spdystream/connection.go
  vendor/github.com/docker/spdystream/handlers.go
  vendor/github.com/docker/spdystream/priority.go
  vendor/github.com/docker/spdystream/spdy/dictionary.go
  vendor/github.com/docker/spdystream/spdy/read.go
  vendor/github.com/docker/spdystream/spdy/types.go
  vendor/github.com/docker/spdystream/spdy/write.go
  vendor/github.com/docker/spdystream/stream.go
  vendor/github.com/docker/spdystream/utils.go
  vendor/k8s.io/apimachinery/pkg/util/httpstream/doc.go
  vendor/k8s.io/apimachinery/pkg/util/httpstream/httpstream.go
  vendor/k8s.io/apimachinery/pkg/util/httpstream/spdy/connection.go
  vendor/k8s.io/apimachinery/pkg/util/httpstream/spdy/roundtripper.go
  vendor/k8s.io/apimachinery/pkg/util/httpstream/spdy/upgrade.go
  vendor/k8s.io/apimachinery/pkg/util/remotecommand/constants.go
  vendor/k8s.io/apimachinery/third_party/forked/golang/netutil/addr.go
  vendor/k8s.io/client-go/tools/remotecommand/doc.go
  vendor/k8s.io/client-go/tools/remotecommand/errorstream.go
  vendor/k8s.io/client-go/tools/remotecommand/reader.go
  vendor/k8s.io/client-go/tools/remotecommand/remotecommand.go
  vendor/k8s.io/client-go/tools/remotecommand/resize.go
  vendor/k8s.io/client-go/tools/remotecommand/v1.go
  vendor/k8s.io/client-go/tools/remotecommand/v2.go
  vendor/k8s.io/client-go/tools/remotecommand/v3.go
  vendor/k8s.io/client-go/tools/remotecommand/v4.go
  vendor/k8s.io/client-go/transport/spdy/spdy.go
  vendor/k8s.io/client-go/util/exec/exec.go
Labels: test

#297 feat: use buildx to reduce image size
  Makefile
  dist/images/Dockerfile
  dist/ovs/Dockerfile
Labels: enhancement

#300 fix: separate log for no address and wrong address
  pkg/daemon/init.go
Labels: bug

#301 OVS local interface table mac_in_use col is in lower case, but pod
  dist/images/install.sh
  dist/images/kubectl-ko
Labels: bug

#306 feat: diagnose check if dns/kubernetes svc exist
  dist/images/install.sh
  dist/images/kubectl-ko
Labels: enhancement

#308 docs: change the cidr to avoid misunderstanding
  docs/subnet.md
Labels: docs

#313 add support for multi-arch build
  Makefile
  dist/images/Dockerfile
  dist/images/build.sh
  dist/ovs/Dockerfile
Labels: feature

#314 fix: mount etc/origin/ovn to ovs-ovn
  dist/images/install.sh
  docs/install.md
  yamls/ovn-ha.yaml
  yamls/ovn.yaml
Labels: bug

#315 docs: add arm build steps
  README.md
  docs/development.md
Labels: docs

#317 fix: fork go-ping and apply patches
  go.mod
  go.sum
  pkg/daemon/ovs.go
  pkg/pinger/ping.go
  vendor/github.com/sparrc/go-ping/.gitignore
  vendor/github.com/sparrc/go-ping/LICENSE
  vendor/github.com/sparrc/go-ping/README.md
  vendor/github.com/sparrc/go-ping/ping.go
  vendor/modules.txt
Labels: bug

#318 Merge vlan
  cmd/daemon/cniserver.go
  dist/images/cleanup.sh
  dist/images/install.sh
  docs/vlan.md
  pkg/apis/kubeovn/v1/condition.go
  pkg/apis/kubeovn/v1/register.go
  pkg/apis/kubeovn/v1/status.go
  pkg/apis/kubeovn/v1/types.go
  pkg/apis/kubeovn/v1/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/typed/kubeovn/v1/fake/fake_kubeovn_client.go
  pkg/client/clientset/versioned/typed/kubeovn/v1/fake/fake_network.go
  pkg/client/clientset/versioned/typed/kubeovn/v1/fake/fake_vlan.go
  pkg/client/clientset/versioned/typed/kubeovn/v1/generated_expansion.go
  pkg/client/clientset/versioned/typed/kubeovn/v1/kubeovn_client.go
  pkg/client/clientset/versioned/typed/kubeovn/v1/network.go
  pkg/client/clientset/versioned/typed/kubeovn/v1/vlan.go
  pkg/client/informers/externalversions/kubeovn/v1/interface.go
  pkg/client/informers/externalversions/kubeovn/v1/network.go
  pkg/client/informers/externalversions/kubeovn/v1/vlan.go
  pkg/client/listers/kubeovn/v1/expansion_generated.go
  pkg/client/listers/kubeovn/v1/network.go
  pkg/client/listers/kubeovn/v1/vlan.go
  pkg/controller/config.go
  pkg/controller/controller.go
  pkg/controller/init.go
  pkg/controller/node.go
  pkg/controller/pod.go
  pkg/controller/subnet.go
  pkg/controller/vlan.go
  pkg/daemon/config.go
  pkg/daemon/controller.go
  pkg/daemon/gateway.go
  pkg/daemon/handler.go
  pkg/daemon/init.go
  pkg/daemon/ovs.go
  pkg/ovs/ovn-nbctl.go
  pkg/ovs/ovs-vsctl.go
  pkg/ovs/util.go
  pkg/util/const.go
  pkg/util/validator.go
  pkg/util/vlan.go
  yamls/crd-vlan.yaml
  yamls/kube-ovn-vlan.yaml
  yamls/ovn-vlan.yaml
Labels: feature

#319 feat: improve install/uninstall
  dist/images/cleanup.sh
  dist/images/install.sh
  dist/images/uninstall.sh
Labels: enhancement

#321 monitor: make graph more sensitive to changes
  dist/monitoring/pinger-grafana.json
Labels: enhancement

#322 fix: ping output format
  pkg/daemon/ovs.go
Labels: bug

#324 fix: labels might be nil
  pkg/controller/network_policy.go
Labels: bug

#326 fix: concurrent panic
  pkg/controller/pod.go
  pkg/speaker/config.go
Labels: bug

#327 fix: error log found in scale test
  pkg/controller/pod.go
  pkg/daemon/gateway.go
Labels: bug

#328 fix: check ovn-nbctl socket in new dir
  dist/images/kube-ovn-controller-healthcheck.sh
Labels: bug

#329 fix: wait node annotations ready before handle pods
  dist/images/install.sh
  dist/images/start-cniserver.sh
  pkg/controller/controller.go
  yamls/ovn-ha.yaml
  yamls/ovn.yaml
Labels: bug
