Repository kubeovn/kube-ovn, pull requests merged in 2020-05, with the labels that each got.

#330 feat: github action
  .github/workflows/build-arm64-image.yaml
  .github/workflows/build-x86-image.yaml
  Makefile
Labels: enhancement

#331 fix: validate if node address conflict with subnet cidr
  pkg/controller/subnet.go
Labels: bug

#332 fix: validate if subnet cidr conflicts with svc ip
  pkg/util/validator.go
Labels: bug

#333 fix: ipv6 related issues
  dist/images/install.sh
  dist/images/start-db.sh
  dist/images/start-ovs.sh
  pkg/apis/kubeovn/v1/types.go
  pkg/client/informers/externalversions/generic.go
  pkg/controller/endpoint.go
  pkg/controller/init.go
  pkg/controller/subnet.go
  pkg/daemon/ovs.go
  pkg/util/net.go
  yamls/crd.yaml
Labels: bug

#334 fix: map concurrent panic
  pkg/ipam/subnet.go
Labels: bug

#335 feat: only show error log of kube-ovn-controller
  dist/images/install.sh
  dist/images/kubectl-ko
Labels: enhancement

#336 chore: reduce logs
  pkg/controller/pod.go
  pkg/controller/service.go
Labels: enhancement

#337 fix: use kubectl to avoid tls handshake error
  dist/images/kube-ovn-controller-healthcheck.sh
Labels: bug

#338 feat: refactor subnet and allow cidr change
  dist/images/.dockerignore
  dist/images/install.sh
  dist/images/kubectl-ko
  pkg/controller/controller.go
  pkg/controller/subnet.go
  pkg/controller/vlan.go
  pkg/ovs/ovn-nbctl.go
  test/e2e/subnet/normal.go
  test/unittest/ipam/ipam.go
Labels: feature

#339 feat: change pod route when update gateway type
  pkg/controller/node.go
  pkg/controller/subnet.go
  pkg/ovs/util.go
  pkg/webhook/static_ip.go
Labels: enhancement

#340 fix: wrong subnet status
  pkg/controller/subnet.go
Labels: bug

#341 fix: when podName or namespace contains dot, lsp cannot be deleted co…
  pkg/controller/controller.go
  pkg/controller/gc.go
Labels: bug

#342 fix: check svc and endpoint protocol
  pkg/controller/endpoint.go
Labels: bug

#343 perf: reduce lflow count
  dist/images/build.sh
Labels: performance

#346 chore: remove networks crd
  .gitignore
  dist/images/install.sh
  pkg/apis/kubeovn/v1/register.go
  pkg/apis/kubeovn/v1/types.go
  pkg/apis/kubeovn/v1/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/typed/kube-ovn/v1/doc.go
  pkg/client/clientset/versioned/typed/kube-ovn/v1/fake/doc.go
  pkg/client/clientset/versioned/typed/kube-ovn/v1/fake/fake_ip.go
  pkg/client/clientset/versioned/typed/kube-ovn/v1/fake/fake_kube-ovn_client.go
  pkg/client/clientset/versioned/typed/kube-ovn/v1/fake/fake_subnet.go
  pkg/client/clientset/versioned/typed/kube-ovn/v1/generated_expansion.go
  pkg/client/clientset/versioned/typed/kube-ovn/v1/ip.go
  pkg/client/clientset/versioned/typed/kube-ovn/v1/kube-ovn_client.go
  pkg/client/clientset/versioned/typed/kube-ovn/v1/subnet.go
  pkg/client/clientset/versioned/typed/kubeovn/v1/fake/fake_kubeovn_client.go
  pkg/client/clientset/versioned/typed/kubeovn/v1/fake/fake_network.go
  pkg/client/clientset/versioned/typed/kubeovn/v1/generated_expansion.go
  pkg/client/clientset/versioned/typed/kubeovn/v1/kubeovn_client.go
  pkg/client/clientset/versioned/typed/kubeovn/v1/network.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/kube-ovn/interface.go
  pkg/client/informers/externalversions/kube-ovn/v1/interface.go
  pkg/client/informers/externalversions/kube-ovn/v1/ip.go
  pkg/client/informers/externalversions/kube-ovn/v1/subnet.go
  pkg/client/informers/externalversions/kubeovn/v1/interface.go
  pkg/client/informers/externalversions/kubeovn/v1/network.go
  pkg/client/listers/kube-ovn/v1/expansion_generated.go
  pkg/client/listers/kube-ovn/v1/ip.go
  pkg/client/listers/kube-ovn/v1/subnet.go
  pkg/client/listers/kubeovn/v1/expansion_generated.go
  pkg/client/listers/kubeovn/v1/network.go
  pkg/controller/init.go
  yamls/crd-vlan.yaml
  yamls/crd.yaml
  yamls/kind-single.yaml
  yamls/ovn-ha.yaml
  yamls/ovn.yaml
Labels: enhancement

#347 fix: return early if allocation is not ready
  .github/workflows/build-x86-image.yaml
  dist/images/start-ovs.sh
  pkg/daemon/handler.go
  yamls/kind-ha.yaml
  yamls/kind-single.yaml
Labels: bug

#348 fix: patch ovn to lower src-ip route priority to work with ovn-ic
  dist/images/build.sh
Labels: bug

#349 fix: init ipam before gc, other wise routes will be deleted
  pkg/controller/controller.go
Labels: bug

#351 perf: add amd64 compile flags back
  dist/images/Dockerfile
  dist/images/build.sh
Labels: performance

#353 feat: in vlan mode if physical gateway exists, no need to create a vi…
  docs/vlan.md
  pkg/apis/kubeovn/v1/types.go
  pkg/controller/pod.go
  pkg/controller/subnet.go
  pkg/daemon/controller.go
  pkg/ovs/ovn-nbctl.go
Labels: feature

#354 fix: dst route policy might be empty
  pkg/controller/gc.go
  pkg/ovs/ovn-nbctl.go
Labels: bug

#356 fix: gc node lsp
  pkg/controller/gc.go
  pkg/ovs/ovn-nbctl.go
Labels: bug

#357 chore: optimize kube-ovn-cni log
  pkg/daemon/handler.go
Labels: enhancement

#358 feat: support underlay without vlan encap
  pkg/daemon/ovs.go
  pkg/ovs/ovn-nbctl.go
Labels: feature

#359 fix: gc lsp for pod that not alive
  Makefile
  pkg/controller/gc.go
Labels: bug

#360 chore: improve log
  pkg/controller/subnet.go
Labels: enhancement

#361 fix: update ovn patch
  dist/images/build.sh
Labels: bug

#362 fix: native vlan and delete subnet issues
  pkg/controller/subnet.go
  pkg/controller/vlan.go
  pkg/util/validator.go
Labels: bug

#363 fix: pod get deleted between configure nb and patch pod
  pkg/controller/pod.go
Labels: bug

#352 Add OVS-DPDK support, for issue 104
  dist/images/Dockerfile.dpdk1911
  dist/images/install.sh
  dist/images/ovs-dpdk-healthcheck.sh
  dist/images/start-ovs-dpdk.sh
  docs/dpdk.md
Labels: performance

#365 chore: prepare for release 1.2
  .github/workflows/build-arm64-image.yaml
  CHANGELOG.md
  docs/high-available.md
  docs/install.md
  docs/ipv6.md
  docs/vlan.md
Labels: docs
