Repository kubeovn/kube-ovn, pull requests merged in 2020-06, with the labels that each got.

#366 chore: add gosec to audit code security
  .github/workflows/build-arm64-image.yaml
  .github/workflows/build-x86-image.yaml
  Makefile
  cmd/controller/controller.go
  cmd/daemon/cniserver.go
  cmd/webhook/server.go
  pkg/controller/config.go
  pkg/controller/network_policy.go
  pkg/controller/pod.go
  pkg/daemon/config.go
  pkg/daemon/handler.go
  pkg/daemon/ovs.go
  pkg/ovs/ovn-nbctl.go
  pkg/pinger/config.go
  pkg/speaker/config.go
  pkg/speaker/pod.go
  pkg/webhook/static_ip.go
  test/e2e/framework/framework.go
  test/e2e/ip/static_ip.go
  test/e2e/subnet/normal.go
  test/unittest/ipam/ipam.go
Labels: enhancement

#367 refactor: use ovs.Exec replace raw command
  pkg/daemon/ovs.go
  pkg/ovs/ovn-nbctl.go
  pkg/ovs/ovs-vsctl.go
Labels: enhancement

#368 security: add trivy scan and fix image CVEs
  .github/workflows/build-x86-image.yaml
  Makefile
  dist/images/Dockerfile
Labels: enhancement

#369 Config support for OVS-DPDK
  dist/images/install.sh
  dist/images/start-ovs-dpdk.sh
  docs/dpdk.md
  yamls/ovn-dpdk.yaml
Labels: feature

#370 fix: add back privilege for ipv6
  dist/images/Dockerfile
  dist/images/install.sh
  yamls/kube-ovn-ipv6.yaml
  yamls/kube-ovn.yaml
Labels: bug

#372 security: update loopback to fix CVE
  dist/images/Dockerfile
Labels: security

#371 Reduce DPDK image size
  dist/images/Dockerfile.dpdk1911
  dist/images/start-ovs-dpdk.sh
Labels: enhancement

#374 Userspace-CNI updates in dpdk.md
  docs/dpdk.md
Labels: docs

#375 Fix typo in multi-nic.md
  docs/multi-nic.md
Labels: docs

#377 fix node's annotations overwrited incorrectly
  pkg/controller/node.go
Labels: bug

#378 security: update yum repo
  .github/workflows/build-x86-image.yaml
  .trivyignore
  dist/images/Dockerfile
Labels: security

#381 ci: do not push image when pr
  .github/workflows/build-arm64-image.yaml
  .github/workflows/build-x86-image.yaml
Labels: enhancement

#382 fix: create/delete order might lead ip conflict
  pkg/controller/pod.go
Labels: bug

#383 ci: use tmpfs to accelerate build and e2e
  yamls/kind-ha.yaml
  yamls/kind-single.yaml
Labels: enhancement

#384 feat: use never used address first to reduce conflict
  pkg/ipam/subnet.go
  test/e2e/ip/static_ip.go
  test/unittest/ipam/ipam.go
Labels: feature

#385 chore: update ovn to 20.06
  dist/images/build.sh
  dist/images/kube-ovn-controller-healthcheck.sh
Labels: enhancement

#386 pinger: add metrics to resolve external address
  dist/images/install.sh
  dist/monitoring/pinger-grafana.json
  pkg/pinger/config.go
  pkg/pinger/metrics.go
  pkg/pinger/ping.go
  pkg/util/network_attachment.go
  yamls/kube-ovn.yaml
Labels: diagnose

#387 kubectl-ko: add ovs-tracing info
  .trivyignore
  dist/images/Dockerfile
  dist/images/install.sh
  dist/images/kubectl-ko
Labels: diagnose

#389 chore: save disk space when building
  .trivyignore
  dist/images/Dockerfile
Labels: enhancement

#392 Add libatomic to docker image
  dist/images/Dockerfile
Labels: bug

#393 action: use commit as image tag
  .github/workflows/build-arm64-image.yaml
  .github/workflows/build-x86-image.yaml
Labels: enhancement
