Repository kubeovn/kube-ovn, pull requests merged in 2021-06, with the labels that each got.

#842 fix: release ip addresses even if pods not found
  pkg/controller/pod.go
Labels: bug, need backport

#843 fix: do not nat route traffic
  pkg/daemon/gateway.go
Labels: bug, need backport

#855 fix: acl overlay issues
  pkg/ovs/ovn-nbctl.go
  pkg/util/const.go
Labels: bug, need backport

#860 fix: ci issues
  .github/workflows/build-arm64-image.yaml
  .github/workflows/build-dpdk-image.yaml
  .github/workflows/build-x86-image.yaml
  Makefile
  dist/images/Dockerfile.dpdk1911
Labels: ci

#858 fix: cleanup kube-ovn-monitor resource
  dist/images/cleanup.sh
Labels: bug, need backport

#859 fix: remove wait ovn sb
  dist/images/start-db.sh
  dist/images/start-ovs.sh
Labels: bug, need backport

#867 ci: remove dpdk ci
  .github/workflows/build-dpdk-image.yaml
Labels: ci

#865 fix: remove rollout check
  dist/images/start-cniserver.sh
Labels: bug, need backport

#870 ignore update pod nic annotation when is not nil
  pkg/controller/pod.go
  pkg/ovs/ovn-nbctl.go
Labels: bug, need backport

#869 1.Support to specify node nic name
  pkg/daemon/config.go
  pkg/util/const.go
Labels: need backport

#872 fix: add nicType for offload
  pkg/daemon/handler.go
  pkg/util/const.go
Labels: bug, need backport

#882 fix: lsp may lost when server pressure is high
  pkg/controller/controller.go
  pkg/controller/gc.go
  pkg/ovs/ovn-nbctl.go
Labels: bug, need backport

#885 Fix multicast when nic type is OVS internal port
  pkg/daemon/ovs.go
Labels: bug, need backport

#880 fix: check crds when controller start
  cmd/controller/controller.go
  dist/images/install-pre-1.16.sh
  dist/images/install.sh
  dist/images/kubectl-ko
Labels: bug, need backport

#884 some fixes in vlan initialization
  pkg/daemon/ovs.go
  test/e2e-vlan/node/node.go
Labels: bug, need backport

#888 fix: clean up gateway chassis list for external gw
  pkg/controller/external-gw.go
Labels: bug, need backport

#892 fix: node route should filter out 'vpc'
  pkg/daemon/controller.go
Labels: bug, need backport

#894 do not delete statefulset pod when update pod
  pkg/controller/pod.go
Labels: bug, need backport
