Repository kubeovn/kube-ovn, pull requests merged in 2021-12, with the labels that each got.

#1124 Check IPv4 gateway by resolving gateway MAC in underlay subnets
  docs/vlan.md
  go.mod
  go.sum
  pkg/daemon/handler.go
  pkg/daemon/ovs.go
  pkg/util/arping.go
Labels: enhancement

#1142 add pod in default vpc to node port-group
  pkg/controller/init.go
  pkg/controller/node.go
Labels: need backport

#1144 security: update base ubuntu image
  dist/images/Dockerfile.base
Labels: security, need backport

#1141 fix pinger's compatibility for k8s v1.16
  dist/images/install.sh
  dist/images/update/1.7-1.8.1.sh
  pkg/pinger/config.go
  yamls/kube-ovn-ipv6.yaml
  yamls/kube-ovn.yaml
Labels: bug, need backport

#1146 fix LB: skip service without cluster IP
  pkg/controller/endpoint.go
Labels: bug, need backport

#1152 add db compact for nb and sb db
  dist/images/ovn-is-leader.sh
Labels: enhancement, need backport

#1147 deleting all chassises which are not nodes
  pkg/controller/node.go
  pkg/ovs/ovn-sbctl.go
Labels: bug, need backport

#1159 fix: add kube-ovn-cni prob timeout
  dist/images/install.sh
  yamls/kube-ovn.yaml
Labels: bug, need backport

#1157 chore: update klog to v2 which embed log rotation
  cmd/cmdmain.go
  cmd/controller/controller.go
  cmd/daemon/cniserver.go
  cmd/ovn_monitor/ovn_monitor.go
  cmd/pinger/pinger.go
  cmd/speaker/speaker.go
  cmd/webhook/server.go
  go.mod
  pkg/controller/config.go
  pkg/controller/controller.go
  pkg/controller/election.go
  pkg/controller/endpoint.go
  pkg/controller/exporter.go
  pkg/controller/external-gw.go
  pkg/controller/external_vpc.go
  pkg/controller/gc.go
  pkg/controller/init.go
  pkg/controller/inspection.go
  pkg/controller/ip.go
  pkg/controller/namespace.go
  pkg/controller/network_policy.go
  pkg/controller/node.go
  pkg/controller/ovn-ic.go
  pkg/controller/pod.go
  pkg/controller/provider-network.go
  pkg/controller/security_group.go
  pkg/controller/service.go
  pkg/controller/subnet.go
  pkg/controller/vlan.go
  pkg/controller/vpc.go
  pkg/controller/vpc_lb.go
  pkg/controller/vpc_nat_gateway.go
  pkg/daemon/config.go
  pkg/daemon/controller.go
  pkg/daemon/gateway.go
  pkg/daemon/handler.go
  pkg/daemon/init.go
  pkg/daemon/ovs.go
  pkg/daemon/server.go
  pkg/ipam/ipam.go
  pkg/ipam/subnet.go
  pkg/ovnmonitor/config.go
  pkg/ovnmonitor/exporter.go
  pkg/ovnmonitor/util.go
  pkg/ovs/ovn-ic-nbctl.go
  pkg/ovs/ovn-nbctl.go
  pkg/ovs/ovn-sbctl.go
  pkg/ovs/ovs-vsctl.go
  pkg/pinger/config.go
  pkg/pinger/exporter.go
  pkg/pinger/ovn.go
  pkg/pinger/ping.go
  pkg/pinger/util.go
  pkg/speaker/config.go
  pkg/speaker/controller.go
  pkg/speaker/subnet.go
  pkg/webhook/static_ip.go
  pkg/webhook/webhook.go
Labels: need backport

#1161 update delete operation for statefulset pod
  pkg/controller/pod.go
Labels: bug, need backport

#1164 fix port_security
  pkg/controller/pod.go
Labels: bug

#1165 fix: add back the leader check
  dist/images/install.sh
  dist/images/ovn-is-leader.sh
  yamls/ovn.yaml
Labels: bug, need backport

#1166 perf: do not send traffic to ct if not designate to svc
  dist/images/Dockerfile.base
  docs/performance-tuning.md
Labels: performance

#1167 When netpol is added to a workload, the workload's POD can be accessed using service
  pkg/controller/controller.go
  pkg/controller/network_policy.go
  pkg/controller/service.go
  pkg/ovs/ovn-nbctl.go
Labels: bug, need backport

#1172 fix: do not reuse released ip after subnet updated
  pkg/ipam/ipam.go
  test/unittest/ipam/ipam.go
Labels: bug, need backport

#1182 fix: check np switch
  pkg/controller/service.go
Labels: bug, need backport

#1187 perf: jemalloc and ISA optimization
  dist/images/Dockerfile.base
Labels: performance

#1200 pinger: fix getting empty PodIPs
  pkg/pinger/config.go
Labels: bug, need backport

#1197 support running ovn-ic e2e on macOS
  .gitignore
  Makefile
  pkg/controller/ovn-ic.go
  yamls/ovn-ic.yaml.j2
Labels: test

#1208 move chassis judge to the end of node processing
  pkg/controller/node.go
Labels: bug, need backport

#1207 change nbctl args 'wait=sb' to 'no-wait'
  pkg/ovs/ovn-nbctl.go
Labels: performance, need backport

#1212 fix installation script
  dist/images/install.sh
Labels: bug, need backport

#1215 fix pod tolerations
  dist/images/install.sh
  yamls/kube-ovn-dual-stack.yaml
  yamls/kube-ovn-ipv6.yaml
  yamls/kube-ovn.yaml
  yamls/ovn-dpdk.yaml
  yamls/ovn-ha.yaml
  yamls/ovn.yaml
Labels: bug, need backport

#1211 add log for ecmp route
  pkg/controller/node.go
  pkg/controller/subnet.go
  pkg/util/net.go
Labels: need backport

#1214 modify pod's process of update for use multus cni as default cni
  pkg/controller/init.go
  pkg/controller/node.go
  pkg/controller/pod.go
  pkg/daemon/handler.go
  pkg/util/const.go
Labels: bug, need backport
