Repository kubeovn/kube-ovn, pull requests merged in 2021-05, with the labels that each got.

#777 fix ovn nb reconnect
  pkg/ovs/ovn-nbctl.go
Labels: bug, need backport

#778 fix: remove tty error notification
  dist/images/install-pre-1.16.sh
  dist/images/install.sh
  dist/images/kubectl-ko
Labels: bug, need backport

#781 fix: do not gc learned routes
  pkg/ovs/ovn-nbctl.go
Labels: bug, need backport

#779 fix: get_leader_ip always return fist node ip
  dist/images/start-db.sh
Labels: bug, need backport

#783 fix: do not re-generate ts port
  pkg/controller/ovn-ic.go
  pkg/ovs/ovn-nbctl.go
Labels: bug, need backport

#794 fix: del might panic if duplicate delete
  pkg/daemon/gateway.go
  pkg/daemon/handler.go
Labels: bug, need backport

#808 fix mss rule
  pkg/daemon/gateway.go
Labels: bug, need backport

#814 add judge about nic address
  pkg/controller/pod.go
Labels: bug

#819 fix: forward policy to accept
  dist/images/start-cniserver.sh
Labels: bug, need backport

#823 fix: check if provider network exists
  pkg/daemon/handler.go
Labels: bug

#832 add e2e testing for vlan mode
  .github/workflows/build-x86-image.yaml
  Makefile
  dist/images/install.sh
  docs/development.md
  test/e2e-vlan/e2e_suite_test.go
  test/e2e-vlan/node/.gitignore
  test/e2e-vlan/node/network.go
  test/e2e-vlan/node/node.go
Labels: ci, test

#831 fix: add node to pod allow acl
  pkg/controller/controller.go
  pkg/controller/network_policy.go
  pkg/ovs/ovn-nbctl.go
Labels: bug, need backport
