Repository kubeovn/kube-ovn, pull requests merged in 2021-09, with the labels that each got.

#1007 update provider network CRD
  dist/images/install-pre-1.16.sh
  dist/images/install.sh
  yamls/crd-pre-1.16.yaml
  yamls/crd.yaml
Labels: enhancement

#1006 perf: use link alias to filter packet
  fastpath/kube_ovn_fastpath.c
  pkg/daemon/ovs.go
Labels: performance, need backport

#1013 fix adding OVN routes in dual stack Kubernetes
  pkg/controller/subnet.go
  test/e2e/e2e_suite_test.go
  test/e2e/subnet/normal.go
Labels: bug, test

#1015 fix nat-outgoing/policy-routing on pod startup
  pkg/daemon/controller.go
  pkg/daemon/gateway.go
  test/e2e/subnet/normal.go
  test/e2e/underlay/underlay.go
Labels: bug, need backport

#1018 fix typos
  ARCHITECTURE.MD
  CHANGELOG.md
  README.md
  cmd/controller/controller.go
  docs/cluster-interconnection.md
  docs/dpdk.md
  docs/high-availability.md
  docs/install.md
  docs/internal-port.md
  docs/snat-and-eip.md
  docs/vlan-topology.png
  docs/vlan.md
  pkg/controller/client_go_adapter.go
  pkg/controller/node.go
  pkg/controller/pod.go
  pkg/controller/subnet.go
  pkg/controller/vpc_nat_gateway.go
  pkg/daemon/config.go
  pkg/daemon/controller.go
  pkg/daemon/gateway.go
  pkg/daemon/init.go
  pkg/daemon/metrics.go
  pkg/daemon/ovs.go
  pkg/pinger/metrics.go
  pkg/pinger/ping.go
  pkg/util/net.go
Labels: docs

#1019 fix variable referrence
  dist/images/install-pre-1.16.sh
  dist/images/install.sh
  dist/images/kubectl-ko
Labels: bug, need backport

#1010 fix e2e testing
  .github/workflows/build-x86-image.yaml
  go.mod
  go.sum
  test/e2e-underlay-single-nic/e2e_suite_test.go
  test/e2e-underlay-single-nic/node/node.go
  test/e2e/e2e_suite_test.go
  test/e2e/framework/framework.go
  test/e2e/ip/static_ip.go
Labels: test, need backport

#1017 perf: switch's router port's addresses to "router"
  pkg/ovs/ovn-nbctl.go
Labels: performance

#1023 perf: do not diagnose external access
  pkg/pinger/config.go
Labels: performance, need backport

#1024 fix: re-check ns annotation to avoid annotations lost
  pkg/controller/namespace.go
Labels: bug, need backport

#1025 perf: increase ovn-nb timeout
  dist/images/kube-ovn-controller-healthcheck.sh
  pkg/controller/config.go
  pkg/ovs/ovn-nbctl.go
Labels: performance, need backport

#1030 ci: push dev image to separate repo
  .github/workflows/build-arm64-image.yaml
  .github/workflows/build-x86-image.yaml
Labels: ci

#1029 fix: kubeclient timeout
  pkg/controller/config.go
  pkg/controller/controller.go
Labels: bug, need backport

#1035 fix VPC document
  docs/vpc.md
Labels: docs

#1031 feat: support VLAN subnet in VPC
  pkg/controller/subnet.go
  pkg/daemon/init.go
  pkg/daemon/ovs.go
  pkg/ovs/ovn-nbctl.go
Labels: feature

#956 feature: LoadBalancer for custom VPC
  dist/images/install-pre-1.16.sh
  dist/images/install.sh
  docs/vpc.md
  pkg/controller/config.go
  pkg/controller/vpc.go
  pkg/controller/vpc_lb.go
  pkg/util/const.go
  yamls/kube-ovn-ipv6.yaml
  yamls/kube-ovn.yaml
Labels: feature

#1037 append externalIds for pod and node when upgrade
  pkg/controller/init.go
  pkg/ovs/ovn-nbctl.go
Labels: bug, need backport

#1038 fix IPAM for StatefulSet
  pkg/controller/gc.go
  pkg/controller/init.go
  pkg/controller/pod.go
  pkg/daemon/handler.go
Labels: bug, need backport

#1040 fix: wrong link for iptables
  dist/images/Dockerfile.base
Labels: bug, need backport

#1042 refactor: mute ovn0 ping log and add ping details
  pkg/daemon/ovs.go
Labels: need backport, refactor

#1044 fix vpc policy route
  docs/vpc.md
  pkg/controller/vpc.go
  pkg/ovs/ovn-nbctl.go
Labels: bug, need backport

#1041 fix StatefulSet down scale
  pkg/controller/pod.go
Labels: bug, need backport

#1045 fix getting LSP UUID by name
  pkg/ovs/ovn-nbctl.go
Labels: bug, need backport

#1047 fix installation scripts
  dist/images/install-pre-1.16.sh
  dist/images/install.sh
Labels: bug, need backport

#1048 fix: init node with wrong ipamkey and lead conflict
  pkg/controller/init.go
Labels: bug, need backport
