Repository kubeovn/kube-ovn, pull requests merged in 2021-07, with the labels that each got.

#900 fix IP/route transfer on node reboot
  pkg/daemon/init.go
  pkg/daemon/ovs.go
Labels: bug, need backport

#904 add judge before use slices's index
  pkg/daemon/controller.go
Labels: bug

#908 security: add go build security options
  Makefile
Labels: need backport, security

#911 perf: enable tx offload again as upstream already fix it
  dist/images/install-pre-1.16.sh
  dist/images/install.sh
  pkg/daemon/config.go
  pkg/daemon/controller.go
  pkg/daemon/init.go
  pkg/daemon/ovs.go
  yamls/kube-ovn.yaml
Labels: need backport, performance

#912 fix uninstall.sh execution in OVS pods
  dist/images/install-pre-1.16.sh
  dist/images/install.sh
  yamls/ovn-dpdk.yaml
  yamls/ovn-ha.yaml
  yamls/ovn.yaml
Labels: bug, need backport

#906 feat: ko support cluster operations status/kick/backup
  dist/images/install-pre-1.16.sh
  dist/images/install.sh
  dist/images/kubectl-ko
  test/e2e/kubectl-ko/ko.go
Labels: need backport

#903 Underlay/VLAN refactoring
  .github/workflows/build-x86-image.yaml
  Makefile
  cmd/daemon/cniserver.go
  dist/images/cleanup.sh
  dist/images/install-pre-1.16.sh
  dist/images/install.sh
  docs/development.md
  docs/vlan.md
  hack/update-codegen-docker.sh
  pkg/apis/kubeovn/v1/condition.go
  pkg/apis/kubeovn/v1/register.go
  pkg/apis/kubeovn/v1/status.go
  pkg/apis/kubeovn/v1/types.go
  pkg/apis/kubeovn/v1/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/typed/kubeovn/v1/fake/fake_kubeovn_client.go
  pkg/client/clientset/versioned/typed/kubeovn/v1/fake/fake_providernetwork.go
  pkg/client/clientset/versioned/typed/kubeovn/v1/generated_expansion.go
  pkg/client/clientset/versioned/typed/kubeovn/v1/kubeovn_client.go
  pkg/client/clientset/versioned/typed/kubeovn/v1/providernetwork.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/kubeovn/v1/interface.go
  pkg/client/informers/externalversions/kubeovn/v1/providernetwork.go
  pkg/client/listers/kubeovn/v1/expansion_generated.go
  pkg/client/listers/kubeovn/v1/providernetwork.go
  pkg/controller/config.go
  pkg/controller/controller.go
  pkg/controller/init.go
  pkg/controller/node.go
  pkg/controller/pod.go
  pkg/controller/subnet.go
  pkg/controller/vlan.go
  pkg/daemon/config.go
  pkg/daemon/controller.go
  pkg/daemon/handler.go
  pkg/daemon/init.go
  pkg/daemon/ovs.go
  pkg/ovs/ovs-vsctl.go
  pkg/util/const.go
  pkg/util/validator.go
  pkg/util/vlan.go
  test/e2e-vlan-single-nic/e2e_suite_test.go
  test/e2e-vlan-single-nic/node/network.go
  test/e2e-vlan-single-nic/node/node.go
  test/e2e-vlan/node/.gitignore
  test/e2e/e2e_suite_test.go
  test/e2e/framework/framework.go
  test/e2e/ip/static_ip.go
  test/e2e/subnet/normal.go
  test/e2e/underlay/const.go
  test/e2e/underlay/network.go
  test/e2e/underlay/normal.go
  test/e2e/underlay/pod.go
  yamls/crd-pre-1.16.yaml
  yamls/crd.yaml
  yamls/ovn-dpdk.yaml
  yamls/ovn-ha.yaml
  yamls/ovn.yaml
Labels: feature

#921 [kubectl-ko] support trace in underlay networking
  dist/images/Dockerfile.base
  dist/images/install-pre-1.16.sh
  dist/images/install.sh
  dist/images/kubectl-ko
Labels: bug, need backport

#866 fix subnet available IPs
  pkg/controller/subnet.go
  pkg/ipam/ipam.go
  pkg/ipam/subnet.go
  pkg/util/net.go
  pkg/util/validator.go
  test/unittest/unit_suite_test.go
  test/unittest/util/net.go
Labels: bug, need backport

#924 delete ecmp route when node is not ready
  pkg/controller/node.go
  pkg/ovs/ovn-nbctl.go
Labels: bug, need backport

#925 keep subnet's vlan empty if not specified
  pkg/controller/subnet.go
Labels: bug, need backport

#926 add field defaultNetworkType in configmap ovn-config
  dist/images/install-pre-1.16.sh
  dist/images/install.sh
  yamls/ovn-dpdk.yaml
  yamls/ovn-ha.yaml
  yamls/ovn.yaml
Labels: need backport

#929 fix CRD provider-networks.kubeovn.io
  dist/images/install-pre-1.16.sh
  yamls/crd-pre-1.16.yaml
Labels: bug, need backport

#927 <fix> update qos ingress_policing_burst
  pkg/ovs/ovs-vsctl.go
Labels: bug, need backport

#930 match chassis until timeout
  pkg/controller/node.go
Labels: bug, need backport

#922 update underlay e2e testing
  Makefile
  test/e2e-vlan-single-nic/e2e_suite_test.go
  test/e2e-vlan-single-nic/kubectl-ko/ko.go
  test/e2e-vlan-single-nic/node/node.go
  test/e2e/e2e_suite_test.go
  test/e2e/network.go
  test/e2e/underlay/const.go
  test/e2e/underlay/normal.go
  test/e2e/underlay/pod.go
  test/e2e/underlay/underlay.go
Labels: need backport

#933 fix ipsets
  pkg/daemon/gateway.go
  test/e2e/underlay/underlay.go
Labels: bug, need backport

#934 delete overlapped var subnet
  pkg/controller/subnet.go
Labels: bug, need backport

#935 fix: if nftables not exists do no exit
  dist/images/start-cniserver.sh
Labels: bug, need backport

#936 delete ecmp route when node is deleted
  pkg/controller/node.go
Labels: bug, need backport

#939 security: fix CVE-2021-33910
  dist/images/Dockerfile.base
Labels: need backport, security

#940 fix cleanup.sh
  dist/images/cleanup.sh
Labels: bug, need backport

#941 add switch for gateway connectivity check
  dist/images/install-pre-1.16.sh
  dist/images/install.sh
  pkg/apis/kubeovn/v1/types.go
  pkg/daemon/gateway.go
  pkg/daemon/handler.go
  pkg/daemon/ovs.go
  test/e2e/subnet/normal.go
  yamls/crd-pre-1.16.yaml
  yamls/crd.yaml
Labels: feature

#937 fix iptables
  .github/workflows/build-x86-image.yaml
  pkg/daemon/gateway.go
  test/e2e/service/service.go
Labels: bug, need backport

#946 ignore empty lines when counting lbs
  pkg/ovs/ovn-nbctl.go
Labels: bug, need backport

#947 fix subnet e2e
  test/e2e/subnet/normal.go
Labels: bug, need backport

#938 Add switch for network policy support
  .github/workflows/build-x86-image.yaml
  dist/images/install-pre-1.16.sh
  dist/images/install.sh
  docs/install.md
  pkg/controller/config.go
  pkg/controller/controller.go
  pkg/controller/gc.go
  pkg/controller/namespace.go
  pkg/controller/pod.go
  pkg/daemon/config.go
  yamls/kube-ovn-ipv6.yaml
  yamls/kube-ovn.yaml
Labels: feature

#948 fix external_ids:pod_netns
  dist/images/install-pre-1.16.sh
  dist/images/install.sh
  dist/images/kubectl-ko
  pkg/daemon/handler.go
  test/e2e/underlay/underlay.go
Labels: bug, need backport

#950 delete attachment ips
  pkg/controller/pod.go
  pkg/controller/subnet.go
Labels: bug, need backport

#953 fix docs
  docs/OpenstackOnKubernetes.md
  docs/dpdk.md
  docs/dual-stack.md
  docs/high-available.md
  docs/hw-offload.md
  docs/install.md
  docs/internal-port.md
  docs/kubectl-plugin.md
  docs/ovn-ovs-monitor.md
  docs/pod-gw.md
  docs/qos.md
  docs/snat-and-eip.md
  docs/static-ip.md
  docs/subnet.md
  docs/vlan.md
  docs/vpc.md
Labels: docs

#952 Fix LoadBalancer in custom VPCs
  dist/images/install-pre-1.16.sh
  dist/images/install.sh
  pkg/controller/endpoint.go
  pkg/controller/pod.go
  pkg/util/const.go
Labels: bug, need backport
