Repository kubeovn/kube-ovn, pull requests merged in 2021-08, with the labels that each got.

#949 Support Pod annotations control port mirroring
  pkg/daemon/controller.go
  pkg/daemon/handler.go
  pkg/daemon/init.go
  pkg/daemon/ovs.go
  pkg/ovs/ovs-vsctl.go
  pkg/util/const.go
Labels: feature

#957 append pod/exec resource for vpc nat gw
  dist/images/install.sh
  pkg/controller/subnet.go
  pkg/controller/vpc_nat_gateway.go
  yamls/ovn-dpdk.yaml
  yamls/ovn-ha.yaml
Labels: bug, need backport

#958 fix: panic when node has nil annotations
  pkg/controller/node.go
Labels: bug, need backport

#962 fix underlay networking on node reboot
  cmd/daemon/cniserver.go
  pkg/daemon/init.go
  pkg/ovs/ovs-vsctl.go
Labels: bug, need backport

#963 if the string of ip is empty,program will die
  pkg/ovs/ovn-nbctl.go
Labels: bug, need backport

#965 fix default bind socket of cni server
  docs/install.md
  pkg/daemon/config.go
Labels: bug, need backport

#967 fix dual stack cluster created by kind
  Makefile
  yamls/kind.yaml.j2
Labels: bug, need backport

#968 fix multi-nic.md
  docs/multi-nic.md
Labels: docs

#969 fix gofmt lint
  Makefile
  pkg/ovs/ovn-nbctl.go
Labels: bug, need backport

#966 fix uninstall.sh
  dist/images/cleanup.sh
  dist/images/uninstall.sh
Labels: bug, need backport

#971 ensure provider nic is up
  pkg/daemon/ovs.go
Labels: bug, need backport

#974 fix port-security, address parameters should be merged into one
  pkg/ovs/ovn-nbctl.go
Labels: bug, need backport

#975 fix: bad udp checksum when access nodeport
  dist/images/install-pre-1.16.sh
  dist/images/install.sh
  dist/images/uninstall.sh
  pkg/daemon/gateway.go
Labels: bug, need backport

#972 fix IPv6-related issues
  .github/workflows/build-x86-image.yaml
  .gitignore
  Makefile
  dist/images/Dockerfile.base
  dist/images/install-pre-1.16.sh
  dist/images/install.sh
  dist/images/kubectl-ko
  pkg/controller/subnet.go
  pkg/ovs/ovn-nbctl.go
  pkg/ovs/ovn-nbctl_test.go
  test/e2e-vlan-single-nic/kubectl-ko/ko.go
  test/e2e/kubectl-ko/ko.go
  test/e2e/service/service.go
  test/e2e/subnet/normal.go
  test/e2e/underlay/underlay.go
  yamls/kube-ovn-ipv6.yaml
  yamls/kube-ovn.yaml
Labels: bug, need backport

#981 fix issues in underlay networking
  pkg/daemon/controller.go
  pkg/daemon/init.go
  pkg/daemon/ovs.go
Labels: bug, need backport

#983 fix node labels and provider network status
  pkg/daemon/controller.go
Labels: bug, need backport

#980 add support for custom routes
  cmd/cni/cni.go
  docs/multi-nic.md
  pkg/daemon/handler.go
  pkg/daemon/ovs.go
  pkg/request/cniserver.go
Labels: feature

#986 Add missing metadata directive in VpcNatGateway example
  docs/vpc.md
Labels: docs

#976 avoid Pod IP to be the same with node internal IP
  pkg/controller/node.go
  pkg/controller/pod.go
  pkg/ipam/ip.go
  pkg/ipam/ipam.go
  pkg/ipam/subnet.go
  test/unittest/ipam/ipam.go
Labels: bug, need backport

#987 add ready status for provider network
  dist/images/install-pre-1.16.sh
  dist/images/install.sh
  pkg/apis/kubeovn/v1/types.go
  pkg/controller/controller.go
  pkg/controller/init.go
  pkg/controller/provider-network.go
  test/e2e/e2e_suite_test.go
  test/e2e/framework/framework.go
  yamls/crd-pre-1.16.yaml
  yamls/crd.yaml
Labels: enhancement, need backport

#988 fix ipset on pod creation/deletion
  pkg/daemon/gateway.go
Labels: bug, need backport

#996 fix: ovn-northd svc flip flop
  dist/images/ovn-is-leader.sh
Labels: bug, need backport

#994 delete residual ovs internal ports
  pkg/daemon/controller.go
  pkg/ovs/ovs-vsctl.go
Labels: bug, need backport

#997 initialize ipsets on cni server startup
  pkg/daemon/controller.go
Labels: bug, need backport
