Repository kubeovn/kube-ovn, pull requests merged in 2021-11, with the labels that each got.

#1098 fix bug: logical switch ts not ready
  pkg/controller/ovn-ic.go
Labels: bug, need backport

#1099 fix: ensure all kube-ovn components deleted before annotate pods
  dist/images/cleanup.sh
Labels: bug, need backport

#1101 docs: optimize cilium integration docs
  docs/IntegrateCiliumIntoKubeOVN.md
Labels: documents

#1092 support using logical gateway in underlay subnet
  dist/images/install-pre-1.16.sh
  dist/images/install.sh
  dist/images/kubectl-ko
  docs/multi-nic.md
  docs/subnet.md
  pkg/apis/kubeovn/v1/types.go
  pkg/controller/config.go
  pkg/controller/init.go
  pkg/controller/node.go
  pkg/controller/subnet.go
  test/e2e/subnet/normal.go
  test/e2e/underlay/underlay.go
  yamls/crd-pre-1.16.yaml
  yamls/crd.yaml
  yamls/kube-ovn-ipv6.yaml
  yamls/kube-ovn.yaml
Labels: feature

#1103 fix: check allocated annotation in update handler
  pkg/controller/pod.go
Labels: bug, need backport

#1104 fix LB in dual stack cluster
  pkg/controller/endpoint.go
  pkg/util/net.go
Labels: bug, need backport

#1107 fix: trace in custom vpc
  dist/images/install.sh
  dist/images/kubectl-ko
Labels: bug, need backport

#1105 fix read-only pointer in vlan and provider-network
  pkg/controller/vlan.go
  pkg/daemon/controller.go
Labels: bug, need backport

#1109 fix read-only pointer in vlan and provider-network
  pkg/controller/init.go
  pkg/controller/node.go
  pkg/controller/subnet.go
  pkg/controller/vlan.go
Labels: bug, need backport

#1115 fix node address set name
  pkg/controller/node.go
Labels: bug

#1116 fix ko trace
  dist/images/install.sh
  dist/images/kubectl-ko
Labels: enhancement, need backport

#1118 other CNI can be used as the default network
  cmd/cni/cni.go
Labels: need backport

#1120 fix: do not nat route traffic
  dist/images/uninstall.sh
  pkg/daemon/gateway.go
Labels: bug, need backport

#1127 Add switch for NB_Global option mcast_privileged
  dist/images/Dockerfile.base
  dist/images/install.sh
  pkg/controller/config.go
  pkg/controller/init.go
  pkg/ovs/ovn-nbctl.go
  yamls/crd-pre-1.16.yaml
  yamls/kube-ovn-ipv6.yaml
  yamls/kube-ovn.yaml
Labels: performance

#1132 cleanup command flags
  docs/install.md
  pkg/controller/config.go
  pkg/daemon/config.go
Labels: docs

#1135 fix: no need to set address for ls to lr port
  pkg/ovs/ovn-nbctl.go
Labels: bug, need backport
