Repository kubeovn/kube-ovn, pull requests merged in 2022-12, with the labels that each got.

#2107 fix go mod
  go.mod
  go.sum
Labels: ci

#2108 fix policy route for subnets with logical gateway
  pkg/controller/pod.go
  pkg/controller/subnet.go
Labels: bug, need backport

#2118 fix: eip deletion
  pkg/controller/pod.go
  pkg/ovs/ovn-nbctl-legacy.go
Labels: bug, need backport, eip

#2116 fix removing default static route in default vpc
  pkg/controller/vpc.go
Labels: bug, need backport

#2130 fix: delete static route should consider dualstack
  pkg/controller/pod.go
  pkg/ovs/ovn-nbctl-legacy.go
Labels: bug, need backport

#2132 fix: sometimes allocate IPv6 address failed but there is available IP in V6FreeIPList
  pkg/ipam/subnet.go
Labels: bug, need backport

#2133 kubectl-ko: fix registry/version
  dist/images/kubectl-ko
Labels: bug, need backport

#2135 some optimization for provider network status update
  pkg/apis/kubeovn/v1/condition.go
  pkg/controller/provider-network.go
Labels: need backport

#2126 refactor ipam unit test
  test/unittest/ipam/ipam.go
Labels: test

#2143 delete ip crd base on podName
  pkg/controller/pod.go
Labels: bug, need backport

#2142 update go modules
  go.mod
  go.sum
  hack/update-codegen-docker.sh
  pkg/util/address_family_test.go
  pkg/util/k8s_test.go
  pkg/util/net_test.go
  pkg/util/network_attachment_test.go
  pkg/util/patch.go
  pkg/util/slice_test.go
  pkg/util/validator_test.go
  pkg/util/version_test.go
  pkg/util/vlan_test.go
Labels: dependencies, go

#2123 add benchmark test for ipam
  Makefile
  test/unittest/ipam_bench/ipam_test.go
Labels: test

#2154 northd: fix race condition in health check
  .github/workflows/build-x86-image.yaml
  pkg/ovn_leader_checker/ovn.go
Labels: bug, need backport

#2144 add scheduled e2e testing
  .github/workflows/scheduled-e2e.yaml
  Makefile
  Makefile.e2e
  go.mod
  go.sum
  test/cyclonus.yaml
  test/k8s-network/e2e_test.go
Labels: test

#2159 security remove private key
  dist/images/Dockerfile.base
Labels: security

#2157 add process for delete networkpolicy start with number
  pkg/controller/network_policy.go
Labels: bug, need backport

#2164 ci: refactor previous push multi arch
  .github/workflows/publish.yaml
Labels: ci, refactor

#2156 add metric interface_rx_multicast_packets
  docs/ovn-ovs-monitor.md
  go.mod
  go.sum
  pkg/ovnmonitor/util.go
  pkg/pinger/metrics.go
  pkg/pinger/util.go
Labels: need backport, monitoring

#2172 fix base/windows build
  .github/workflows/build-windows.yaml
  dist/images/Dockerfile.base
Labels: bug, need backport

#2177 fix lr policy for default subnet with logical gateway enabled
  pkg/controller/gc.go
  pkg/controller/node.go
  pkg/daemon/controller_linux.go
  pkg/daemon/gateway.go
Labels: bug, need backport

#2196 update docs link in install.sh
  dist/images/install.sh
Labels: docs, need backport

#2195 local ip bind to service
  cmd/controller/controller.go
  cmd/controller_health_check/controller_health_check.go
  cmd/daemon/cniserver.go
  cmd/ovn_monitor/ovn_monitor.go
  dist/images/install.sh
  dist/images/ovn-is-leader.sh
  dist/images/start-db.sh
  kubeovn-helm/templates/central-deploy.yaml
  kubeovn-helm/templates/controller-deploy.yaml
  kubeovn-helm/templates/monitor-deploy.yaml
  kubeovn-helm/templates/ovncni-ds.yaml
  kubeovn-helm/values.yaml
  pkg/ovn_leader_checker/ovn.go
  yamls/kube-ovn-dual-stack.yaml
  yamls/kube-ovn-ipv6.yaml
  yamls/kube-ovn.yaml
  yamls/ovn-dpdk.yaml
  yamls/ovn-ha.yaml
  yamls/ovn.yaml
Labels: refactor

#2189 u2o feature
  Makefile
  dist/images/install.sh
  kubeovn-helm/templates/kube-ovn-crd.yaml
  pkg/apis/kubeovn/v1/types.go
  pkg/controller/config.go
  pkg/controller/init.go
  pkg/controller/ip.go
  pkg/controller/node.go
  pkg/controller/subnet.go
  pkg/controller/vpc.go
  pkg/daemon/handler.go
  pkg/daemon/ovs_linux.go
  pkg/daemon/ovs_windows.go
  pkg/ovs/ovn-nbctl-legacy.go
  pkg/util/const.go
  yamls/crd.yaml
Labels: feature
