Repository kubeovn/kube-ovn, pull requests merged in 2022-09, with the labels that each got.

#1873 cni should handler unmounted volume, when delete pod.
  go.mod
  go.sum
  pkg/daemon/handler_linux.go
Labels: bug, need backport

#1868 refactor iptables rules
  dist/images/uninstall.sh
  pkg/daemon/gateway_linux.go
  pkg/util/strings.go
  pkg/util/strings_test.go
Labels: bug, need backport

#1881 fix setting ether dst addr for dnat
  dist/images/Dockerfile.base
Labels: bug, need backport

#1886 fix duplicate logs for leader election
  pkg/controller/election.go
Labels: need backport

#1802 kubectl-ko: fix trace for KubeVirt VM
  dist/images/kubectl-ko
  docs/kubectl-plugin.md
Labels: bug, need backport, need docs

#1891 kubectl-ko: turn off pipefail for ovn leader check
  dist/images/kubectl-ko
Labels: bug, need backport

#1850 ci: use concurrency to ensure that only a single workflow using the same concurrency group will run at a time
  .github/workflows/build-arm64-image.yaml
  .github/workflows/build-windows.yaml
  .github/workflows/build-x86-image.yaml
  .github/workflows/codeql-analysis.yml
  .github/workflows/lint.yaml
  .github/workflows/push-multiarch-image.yaml
Labels: ci

#1895 fix: api rollback
  pkg/apis/kubeovn/v1/types.go
Labels: bug, need backport

#1894 ci: increase golangci-lint timeout
  .github/workflows/lint.yaml
Labels: ci, need backport

#1896 fix: gatewaynode might be null
  pkg/apis/kubeovn/v1/types.go
  pkg/controller/init.go
Labels: bug, need backport

#1898 fix: failed to add eip
  dist/images/vpcnatgateway/nat-gateway.sh
Labels: bug, need backport

#1899 fix: Make the /sys directory in ovs-ovn-dpdk pod writable
  dist/images/install.sh
Labels: bug, need backport

#1917 fix: eip and nat crd can delete even if nat gw pod deleted and ipatab…
  pkg/controller/vpc_nat_gateway.go
  pkg/controller/vpc_nat_gw_eip.go
  pkg/controller/vpc_nat_gw_nat.go
Labels: bug, need backport

#1918 fix EIP/SNAT on dynamic Pod annotation
  docs/snat-and-eip.md
  pkg/controller/pod.go
  yamls/ovn-external-gw-config.yaml
Labels: bug, need backport

#1921 update ns annotation when subnet cidr changed
  pkg/controller/namespace.go
  pkg/controller/subnet.go
Labels: bug, need backport

#1904 No need to change deivceID to sriov_netdevice.
  pkg/daemon/handler.go
  pkg/daemon/ovs_linux.go
Labels: bug, need backport

#1922 fix: fip unbind can't take effect immediately when conntrack record e…
  dist/images/vpcnatgateway/Dockerfile
  dist/images/vpcnatgateway/nat-gateway.sh
Labels: bug, need backport

#1923 add network partition check in ovn probes
  dist/images/ovn-healthcheck.sh
Labels: bug, need backport

#1924 ignore pod without lsp when add pod to port-group
  pkg/controller/subnet.go
Labels: bug, need backport

#1925 fix: pod mistaken ls label
  pkg/controller/subnet.go
Labels: bug, need backport

#1933 fix: UpdateNatRule error when logicalIP, externalIP in different protocols
  pkg/ovs/ovn-nbctl-legacy.go
Labels: bug, need backport

#1937 set ovsdb-server vlog level to avoid warnings caused by ovs-vsctl
  dist/images/start-ovs.sh
Labels: bug, need backport

#1939 set leader flag when get leader
  pkg/controller/election.go
Labels: bug, need backport

#1929 fix underlay e2e testing
  pkg/daemon/init_linux.go
  test/e2e/underlay/underlay.go
Labels: bug, test, need backport

#1941 ovs: add fdb update logging
  dist/images/Dockerfile.base
Labels: need backport
