Repository kubeovn/kube-ovn, pull requests merged in 2022-10, with the labels that each got.

#1935 fix: add default deny acl
  .github/workflows/build-x86-image.yaml
  pkg/controller/network_policy.go
  test/networkpolicy-cyclonus/cyclonus.yaml
  test/networkpolicy-cyclonus/start-test.sh
Labels: bug, need backport

#1943 ovs: fix mac learning in environments with hairpin enabled
  dist/images/Dockerfile.base
  pkg/daemon/config.go
  pkg/daemon/controller.go
  pkg/daemon/init.go
  pkg/daemon/ovs.go
Labels: enhancement, need backport

#1967 fix version mismatch between the Ginkgo CLI and the imported package
  .github/workflows/build-x86-image.yaml
  docs/development.md
  go.mod
  go.sum
Labels: test, ci

#1971 validate nbctl socket path in start-controller.sh
  dist/images/start-controller.sh
Labels: bug, need backport

#1976 avoid concurrent subnet status update
  pkg/controller/controller.go
  pkg/controller/subnet.go
Labels: bug, need backport

#1960 upgrade ovs-ovn pod by generation version instead of chart version
  dist/images/upgrade-ovs.sh
Labels: bug, need backport

#1973 fix: modify src route priority
  dist/images/Dockerfile.base
Labels: bug, need backport

#1980 ovn db: recover automatically on startup if db corruption is detected
  dist/images/Dockerfile.base
  dist/images/start-db.sh
Labels: bug, need backport

#1983 ovs: fix waiting flows in underlay networking
  dist/images/start-ovs.sh
Labels: bug, need backport

#1984 delete pod after TerminationGracePeriodSeconds
  pkg/controller/pod.go
Labels: bug, need backport

#1986 fix grep matching device in routes
  dist/images/start-ovs.sh
Labels: bug, need backport

#1988 release-1.9: update ovs version to branch-2.16
  dist/images/Dockerfile.base
Labels: bug

#1989 add check of write to ovn sb db for ovn-controller
  dist/images/ovs-healthcheck.sh
Labels: enhancement, need backport

#1998 fix: delete fiprule failed at first time
  dist/images/vpcnatgateway/nat-gateway.sh
Labels: bug, need backport

#1996 fix: nat gw probably not enqueue its resources after rebuild
  pkg/controller/vpc_nat_gateway.go
Labels: bug, need backport

#1999 fix: Add support for Mellanox NIC
  dist/images/Dockerfile.base-dpdk
  dist/images/start-ovs-dpdk-v2.sh
Labels: bug, need backport
