Repository kubeovn/kube-ovn, pull requests merged in 2022-02, with the labels that each got.

#1280 add policy route for distributed subnet in default vpc
  pkg/controller/controller.go
  pkg/controller/gc.go
  pkg/controller/init.go
  pkg/controller/node.go
  pkg/controller/pod.go
  pkg/controller/subnet.go
  pkg/ovs/ovn-nbctl.go
  pkg/util/const.go
Labels: enhancement

#1287 fix: only log matched svc with np
  pkg/controller/network_policy.go
Labels: bug, need backport

#1284 feat: update provider network via node annotation
  pkg/controller/init.go
  pkg/controller/node.go
  test/e2e/underlay/underlay.go
Labels: feature

#1324 fix underlay subnet in custom VPC
  pkg/controller/subnet.go
Labels: bug, need backport

#1329 resync provider network status periodically
  pkg/controller/controller.go
  pkg/controller/exporter.go
Labels: enhancement, need backport

#1326 fix statefulset Pod deletion
  pkg/controller/pod.go
Labels: bug, need backport

#1332 Fix usage of ovn commands
  pkg/ovs/ovn-nbctl.go
Labels: bug, need backport

#1320 feat: support DHCP
  dist/images/install.sh
  docs/subnet.md
  pkg/apis/kubeovn/v1/types.go
  pkg/apis/kubeovn/v1/zz_generated.deepcopy.go
  pkg/controller/gc.go
  pkg/controller/node.go
  pkg/controller/pod.go
  pkg/controller/subnet.go
  pkg/ovs/ovn-nbctl.go
  yamls/crd.yaml
Labels: feature

#1335 fix: continue of deletion for del pod failed when can't found vpc or subnet
  pkg/controller/pod.go
  pkg/daemon/gateway.go
Labels: bug, need backport

#1336 fix OVS bridge with bond port in mode 6
  docs/vlan.md
  pkg/daemon/ovs.go
  pkg/ovs/ovs-vsctl.go
Labels: bug, need backport
