Repository kubeovn/kube-ovn, pull requests merged in 2022-03, with the labels that each got.

#1344 fix usage of ovn commands
  pkg/ovs/ovn-nbctl.go
Labels: bug, need backport

#1340 add check for pod update process
  pkg/controller/inspection.go
Labels: bug, need backport

#1350 update flag parse in webhook
  cmd/webhook/server.go
  yamls/webhook.yaml
Labels: bug, need backport

#1343 add service cidr when init kubeadm
  docs/install.md
Labels: docs

#1352 skip ping gateway for pods during live migration
  pkg/daemon/handler.go
Labels: feature

#1356 modify ipam v6 release ip problem
  pkg/ipam/subnet.go
Labels: bug, need backport

#1357 feat: add webhook to check subnet deletion.
  pkg/webhook/static_ip.go
  pkg/webhook/subnet.go
  pkg/webhook/webhook.go
  yamls/webhook.yaml
Labels: feature

#1346 fix SNAT/PR on Pod startup
  pkg/daemon/gateway.go
Labels: bug, need backport

#1365 add reset porocess for ovs interface metrics
  pkg/pinger/exporter.go
  pkg/pinger/util.go
Labels: bug, need backport

#1359 optimize kube-ovn-monitor and add db restore process
  dist/images/install.sh
  dist/images/kubectl-ko
  dist/images/restore-ovn-nb-db.sh
  dist/images/start-ovn-monitor.sh
  dist/images/update/1.7-1.8.2.sh
  dist/images/update/1.8.2-1.9.0.sh
  pkg/ovnmonitor/exporter.go
  yamls/kube-ovn-dual-stack.yaml
  yamls/kube-ovn-ipv6.yaml
  yamls/kube-ovn.yaml
  yamls/ovn-dpdk.yaml
  yamls/ovn-ha.yaml
  yamls/ovn.yaml
Labels: enhancement, need backport

#1372 Use camel case instead of snake case
  pkg/controller/vpc_nat_gateway.go
Labels: code style

#1375 update script to add restore plugin cmd
  dist/images/install.sh
  dist/images/kubectl-ko
  dist/images/update/1.7-1.8.3.sh
  dist/images/update/1.8.0-1.8.3.sh
  dist/images/update/1.8.3-1.9.1.sh
Labels: bug, need backport

#1377 fix range loop
  pkg/controller/init.go
  pkg/controller/node.go
Labels: bug, need backport

#1380 increase memory limit of ovn-central
  dist/images/install.sh
  yamls/ovn-ha.yaml
  yamls/ovn.yaml
Labels: bug, need backport

#1362 Add missing link scope routes in vpc-nat-gateway
  dist/images/vpcnatgateway/nat-gateway.sh
  pkg/controller/vpc_nat_gateway.go
Labels: bug, need backport

#1382 update nodeips for restore cmd in ko plugin
  dist/images/install.sh
  dist/images/kubectl-ko
  dist/images/restore-ovn-nb-db.sh
  dist/images/update/1.7-1.8.3.sh
  dist/images/update/1.8.0-1.8.3.sh
  dist/images/update/1.8.3-1.9.1.sh
Labels: bug, need backport

#1384 fix external egress gateway
  pkg/daemon/gateway.go
Labels: bug, need backport

#1386 ci: update kind and k8s
  .github/workflows/build-x86-image.yaml
  yamls/kind.yaml.j2
Labels: ci

#1387 docs: update the maintainer and roadmap
  MAINTAINERS
  ROADMAP.md
  docs/dpdk-hybrid.md
Labels: docs

#1388 chore: reduce image size
  Makefile
  cmd/cmdmain.go
  cmd/cni/cni.go
  dist/images/Dockerfile
  dist/images/Dockerfile.base
  dist/images/Dockerfile.base-dpdk
  dist/images/Dockerfile.dpdk
Labels: enhancement

#1373 We should handle the case where the subnet protocol is handled
  pkg/controller/subnet.go
Labels: enhancement

#1390 append vm deletion check
  pkg/controller/pod.go
Labels: bug

#1391 adding IP Protocol enumeration to CRD can reduce the kube-ovn Controller judgment logic
  dist/images/install.sh
  pkg/controller/subnet.go
  test/e2e-ebpf/e2e_ebpf_suite_test.go
  test/e2e/e2e_suite_test.go
  test/e2e/subnet/normal.go
  test/e2e/underlay/underlay.go
  yamls/crd.yaml
Labels: enhancement

#1393 optimize docs due to frequently asked question.
  docs/cluster-interconnection.md
  docs/dpdk-hybrid.md
  docs/install.md
  docs/qos.md
  docs/snat-and-eip.md
  docs/static-ip.md
  docs/subnet.md
  docs/vlan.md
  docs/vpc.md
Labels: docs

#1396 check the cidr format whether is correct
  pkg/util/net.go
  pkg/util/validator.go
Labels: bug, need backport

#1395 add custom acls for subnet
  dist/images/install.sh
  pkg/apis/kubeovn/v1/types.go
  pkg/apis/kubeovn/v1/zz_generated.deepcopy.go
  pkg/controller/subnet.go
  pkg/ovs/ovn-nbctl.go
  yamls/crd.yaml
Labels: feature

#1400 fix: The underlay physical gateway config by external-gw-addr when use snat&eip
  docs/snat-and-eip.md
  pkg/controller/pod.go
Labels: bug, need backport

#1403 add reset for kube-ovn-monitor metrics
  pkg/ovnmonitor/exporter.go
  pkg/ovnmonitor/util.go
Labels: bug, need backport

#1401 [release-1.8] avoid frequent ipset update
  dist/images/uninstall.sh
  go.mod
  go.sum
  pkg/daemon/gateway.go
Labels: bug, need backport

#1402 avoid frequent ipset update
  dist/images/uninstall.sh
  go.mod
  go.sum
  pkg/daemon/gateway.go
  test/e2e/service/service.go
Labels: bug, need backport

#1407 update underlay environment requirements
  docs/vlan.md
Labels: docs

#1397 update cni version to 1.0
  .github/workflows/build-arm64-image.yaml
  .github/workflows/build-x86-image.yaml
  cmd/cni/cni.go
  docs/development.md
  go.mod
  go.sum
Labels: enhancement

#1409 fix: do not recreate port for terminating pods
  pkg/controller/inspection.go
Labels: bug, need backport

#1411 fix: add condition for triggering the deletion of redundant chassises in sbdb
  pkg/controller/node.go
Labels: bug, need backport

#1413 create ip crd in kube-ovn-controller
  pkg/controller/node.go
  pkg/controller/pod.go
Labels: bug, need backport

#1415 recover ips CR on IPAM initialization
  pkg/controller/init.go
  pkg/controller/node.go
Labels: bug, need backport

#1327 update e2e testing
  .github/workflows/build-x86-image.yaml
  dist/images/cleanup.sh
  test/e2e/ip/static_ip.go
  test/e2e/underlay/underlay.go
Labels: test, ci

#1404 add simple e2e for multus integration
  .github/workflows/build-x86-image.yaml
  Makefile
  dist/images/install.sh
Labels: test, ci

#1408 windows support for CNI
  .github/workflows/build-windows.yaml
  .gitignore
  Makefile
  cmd/cni/cni.go
  cmd/cni/netconf.go
  cmd/cni/netconf_windows.go
  cmd/windows/cni/main_windows.go
  go.mod
  go.sum
  pkg/request/client.go
  pkg/request/client_windows.go
  pkg/request/cniserver.go
  pkg/util/address_family.go
  pkg/util/arping.go
  pkg/util/iptables.go
  pkg/util/net.go
Labels: feature

#1201 cilium e2e: deploy k8s without kube-proxy
  .github/workflows/build-x86-image.yaml
  Makefile
  dist/images/install.sh
  dist/images/kubectl-ko
  docs/IntegrateCiliumIntoKubeOVN.md
Labels: test, ci

#1398 build ovs/ovn for windows in ci
  .github/workflows/build-ovs-win64.yaml
Labels: feature

#1416 fix provider-networks status
  dist/images/install.sh
  pkg/apis/kubeovn/v1/status.go
  pkg/apis/kubeovn/v1/types.go
  pkg/controller/node.go
  pkg/controller/provider-network.go
  pkg/controller/subnet.go
  pkg/controller/vlan.go
  pkg/daemon/controller.go
  test/e2e/e2e_suite_test.go
  yamls/crd.yaml
  yamls/ovn-dpdk.yaml
  yamls/ovn-ha.yaml
  yamls/ovn.yaml
Labels: bug, need backport
