Repository kubeovn/kube-ovn, pull requests merged in 2022-06, with the labels that each got.

#1562 fix 'request ip return 500 no address allocated' when pod is created by ephemeral VMI
  pkg/controller/pod.go
  pkg/util/const.go
Labels: bug

#1511 optimized initialization and gc for the chassis
  pkg/controller/controller.go
  pkg/controller/gc.go
  pkg/controller/init.go
  pkg/controller/node.go
  pkg/ovs/ovn-nbctl-legacy.go
  pkg/ovs/ovn-sbctl.go
  pkg/ovs/ovn.go
  pkg/util/version.go
Labels: bug

#1570 fix: Do not Recreate Logical_Router_Port when Vpc recreated
  pkg/controller/vpc.go
  pkg/ovs/ovn-nb-logical_router.go
  pkg/ovs/ovn-nb-logical_router_port.go
  pkg/ovs/ovn.go
  pkg/ovs/util.go
  pkg/ovsdb/client/client.go
Labels: bug

#1580 fix duplicate netns parameter
  pkg/daemon/handler.go
  pkg/daemon/ovs.go
Labels: bug

#1571 do not handle Pod update event when the route has already been added
  pkg/controller/pod.go
Labels: bug

#1586 cni handler: do not wait routed annotation for net1
  pkg/daemon/handler.go
Labels: bug

#1587 fix: all cluster pod will be in podadd queue
  pkg/controller/pod.go
Labels: bug, need backport

#1590 fix ovn-ic doc err
  docs/cluster-interconnection.md
Labels: bug

#1596 Support CNI VESION command
  cmd/cni/cni.go
  go.mod
  go.sum
Labels: enhancement

#1593 docs: fix the kind name
  docs/virtual-ip.md
Labels: docs

#1597 fix: check deploy could be patient
  dist/images/kubectl-ko
Labels: enhancement

#1601 Add ebgp-multihop function for kube-ovn-speaker
  pkg/speaker/config.go
Labels: feature

#1598 fix static ip error in dual stack
  pkg/controller/pod.go
  pkg/util/validator.go
  test/e2e/ip/static_ip.go
Labels: bug

#1604 Modify the next hop calculation method for kube-ovn-speaker
  pkg/speaker/subnet.go
Labels: bug

#1612 fix acl log name too long (exceed 63)
  pkg/ovs/ovn-nbctl-legacy.go
Labels: bug

#1617 refactor: use ConfigMap resourceVersion to check if ovn-vpc-nat-gw-co…
  pkg/controller/vpc_nat_gateway.go
Labels: enhancement

#1625 ci: auto changelog now
  .github/workflows/changelog.yaml
  CHANGELOG.md
  hack/changelog.sh
Labels: ci

#1627 wait ovn-central pods running before delete ovs-ovn pods
  dist/images/kubectl-ko
Labels: need backport

#1628 delete "allow" policy route on subnet deletion
  pkg/controller/subnet.go
Labels: bug, need backport

#1626 fix: cleanup should ignore patch failed
  dist/images/cleanup.sh
Labels: bug

#1634 increase initial delay of ovs-ovn liveness probe
  charts/templates/ovsovn-ds.yaml
  dist/images/install.sh
  yamls/ovn-dpdk.yaml
  yamls/ovn-ha.yaml
  yamls/ovn.yaml
Labels: bug, need backport

#1630 change vpc gw pod workload from deployment to statefulset
  pkg/controller/gc.go
  pkg/controller/vpc_nat_gateway.go
Labels: enhancement

#1636 fix no interface report to multus cni, missing in k8s.v1.cni.cncf.io/network[s]-status
  cmd/cni/cni.go
Labels: bug, need backport

#1637 ci: update trivy options
  Makefile
Labels: ci, need backport

#1633 set networkpolicy log default to false
  pkg/controller/network_policy.go
  pkg/ovs/ovn-nbctl-legacy.go
  pkg/util/const.go
Labels: performance, need backport

#1645 Update install.sh
  dist/images/install.sh
Labels: bug, need backport

#1639 ci: fix golangci-lint
  .github/workflows/lint.yaml
Labels: ci

#1643 fix e2e testing
  test/e2e/e2e_suite_test.go
  test/e2e/ip/static_ip.go
Labels: test, ci, need backport

#1512 set ether dst addr for dnat on logical switch
  dist/images/Dockerfile.base
  dist/images/install.sh
  pkg/controller/config.go
  pkg/controller/controller.go
  pkg/ovs/ovn-nbctl-legacy.go
Labels: enhancement, performance

#1652 fix: no need routed when use v1.multus-cni.io/default-network
  pkg/daemon/handler.go
Labels: bug, need backport
