Repository kubeovn/kube-ovn, pull requests merged in 2022-04, with the labels that each got.

#1417 support alloc static ip from any subnet after ns supports multi subnets
  pkg/controller/pod.go
Labels: bug, need backport

#1422 We are looking forward to your PR!
  README.md
Labels: documents

#1423 feat：add webhook vaildate the vpc resource whether can be deleted.
  pkg/webhook/static_ip.go
  pkg/webhook/vpc.go
  pkg/webhook/webhook.go
  yamls/webhook.yaml
Labels: feature

#1425 replace pod name when create ip crd
  pkg/controller/pod.go
Labels: bug, need backport

#1430 fix error handling for netlink.AddrDel
  pkg/daemon/ovs.go
Labels: bug, need backport

#1432 ignore all link local unicast addresses/routes
  pkg/daemon/ovs.go
  test/e2e-underlay-single-nic/node/node.go
Labels: bug, need backport

#1428 fix: temporary cancel the external2cluater e2e test for cilium
  test/e2e/service/service.go
Labels: test

#1434 fix IPAM initialization
  pkg/controller/init.go
  pkg/controller/node.go
Labels: bug, need backport

#1435 fix adding key to delete Pod queue
  pkg/controller/pod.go
Labels: bug, need backport

#1438 update alpine to fix CVE-2022-1271
  dist/images/vpcnatgateway/Dockerfile
Labels: security, need backport

#1442 modify webhook img to independent image
  .gitignore
  Makefile
  cmd/cmdmain.go
  cmd/webhook/server.go
  dist/images/Dockerfile
  dist/images/Dockerfile.dpdk
Labels: bug, need backport

#1431 prepare windows support for cni server
  pkg/daemon/config.go
  pkg/daemon/config_linux.go
  pkg/daemon/controller.go
  pkg/daemon/controller_linux.go
  pkg/daemon/gateway.go
  pkg/daemon/gateway_linux.go
  pkg/daemon/handler.go
  pkg/daemon/handler_linux.go
  pkg/daemon/init.go
  pkg/daemon/listen.go
  pkg/daemon/ovs.go
  pkg/daemon/ovs_linux.go
  pkg/daemon/server.go
  pkg/ovs/ovs-vsctl.go
  pkg/util/const.go
  pkg/util/const_linux.go
  pkg/util/link.go
Labels: feature

#1443 log: show the reason if get gw node failed
  pkg/controller/subnet.go
Labels: enhancement, need backport

#1444 base: refactor ovn/ovs build
  dist/images/Dockerfile.base
  dist/images/Dockerfile.base-dpdk
  dist/images/Dockerfile.rpm
  dist/images/install.sh
Labels: ci

#1448 modify init ipam by ip crd only for sts pod
  dist/images/install.sh
  dist/images/update/1.7-1.8.3.sh
  dist/images/update/1.8.3-1.9.1.sh
  pkg/apis/kubeovn/v1/types.go
  pkg/controller/init.go
  pkg/controller/node.go
  pkg/controller/pod.go
  yamls/crd.yaml
Labels: bug, need backport

#1454 docs: add USERS.md
  USERS.md
Labels: docs

#1433 add kube-ovn-controller switch for EIP and SNAT
  dist/images/install.sh
  pkg/controller/config.go
  pkg/controller/pod.go
  pkg/controller/subnet.go
  yamls/kube-ovn-dual-stack.yaml
  yamls/kube-ovn-ipv6.yaml
  yamls/kube-ovn.yaml
Labels: performance, need backport

#1455 windows support for cni server
  .gitignore
  Makefile
  cmd/daemon/cniserver.go
  cmd/windows/daemon/main_windows.go
  go.mod
  go.sum
  pkg/daemon/config.go
  pkg/daemon/config_linux.go
  pkg/daemon/config_windows.go
  pkg/daemon/controller_windows.go
  pkg/daemon/gateway.go
  pkg/daemon/gateway_linux.go
  pkg/daemon/gateway_windows.go
  pkg/daemon/handler.go
  pkg/daemon/handler_linux.go
  pkg/daemon/handler_windows.go
  pkg/daemon/listen_windows.go
  pkg/daemon/ovs_linux.go
  pkg/daemon/ovs_windows.go
  pkg/ovs/ovs-vsctl.go
  pkg/ovs/ovs-vsctl_linux.go
  pkg/ovs/ovs-vsctl_windows.go
  pkg/util/const_linux.go
  pkg/util/const_windows.go
  pkg/util/link_windows.go
  pkg/util/network_windows.go
Labels: feature

#1456 update OVS and OVN for windows
  .github/workflows/build-ovs-win64.yaml
Labels: ci

#1459 masquerade packets from Pods to service IP
  dist/images/uninstall.sh
  pkg/daemon/gateway_linux.go
  test/e2e/service/service.go
Labels: bug, need backport

#1465 append metrics
  docs/ovn-ovs-monitor.md
Labels: enhancement, docs

#1466 fix routes for packets from Pods to other nodes
  pkg/controller/subnet.go
  test/e2e/subnet/normal.go
Labels: bug

#1468 Support kubevirt vm live migrate for pod static ip
  pkg/webhook/static_ip.go
Labels: bug

#1464 add env-check
  dist/images/Dockerfile.base
  dist/images/env-check.sh
  dist/images/install.sh
Labels: enhancement, need backport

#1474 add delete ovs pods after restore nb db
  dist/images/install.sh
  dist/images/kubectl-ko
  dist/images/restore-ovn-nb-db.sh
Labels: diagnose

#1478 fix: workqueue_depth should show count not rate
  dist/monitoring/controller-grafana.json
Labels: bug

#1479 CVE-2022-27191
  go.mod
  go.sum
Labels: security

#1476 add acl doc
  docs/qos.md
  docs/subnet-acl.md
  docs/subnet.md
Labels: docs

#1480 fix pod annotation may be overridden by patch
  pkg/controller/inspection.go
  pkg/controller/namespace.go
  pkg/controller/pod.go
  pkg/controller/vpc_nat_gateway.go
  pkg/ovn_leader_checker/ovn.go
  pkg/util/patch.go
  pkg/util/patch_test.go
Labels: bug

#1482 fix: wrong vpc-nat-gateway arm image
  .github/workflows/build-arm64-image.yaml
Labels: bug, need backport

#1483 delete ipam record when gc lsp
  pkg/controller/gc.go
  pkg/ovs/ovn-nbctl.go
Labels: bug

#1487 feat: lsp forwarding external Layer-2 packets
  pkg/controller/pod.go
  pkg/ovs/ovn-nbctl.go
  pkg/util/const.go
Labels: feature

#1484 fix: add empty chassis check in ovn db
  pkg/controller/node.go
Labels: bug

#1489 update github actions
  .github/workflows/build-arm64-image.yaml
  .github/workflows/build-dpdk-image.yaml
  .github/workflows/build-kube-ovn-base-dpdk.yaml
  .github/workflows/build-kube-ovn-base.yaml
  .github/workflows/build-ovs-win64.yaml
  .github/workflows/build-windows.yaml
  .github/workflows/build-x86-image.yaml
  .github/workflows/codeql-analysis.yml
  .github/workflows/lint.yaml
  .github/workflows/push-multiarch-image.yaml
Labels: ci

#1437 Feature iptables eip nats splits
  dist/images/install.sh
  dist/images/vpcnatgateway/nat-gateway.sh
  docs/virtual-ip.md
  docs/vpc.md
  go.mod
  pkg/apis/kubeovn/v1/register.go
  pkg/apis/kubeovn/v1/status.go
  pkg/apis/kubeovn/v1/types.go
  pkg/apis/kubeovn/v1/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/typed/kubeovn/v1/fake/fake_iptablesdnatrule.go
  pkg/client/clientset/versioned/typed/kubeovn/v1/fake/fake_iptableseip.go
  pkg/client/clientset/versioned/typed/kubeovn/v1/fake/fake_iptablesfiprule.go
  pkg/client/clientset/versioned/typed/kubeovn/v1/fake/fake_iptablessnatrule.go
  pkg/client/clientset/versioned/typed/kubeovn/v1/fake/fake_kubeovn_client.go
  pkg/client/clientset/versioned/typed/kubeovn/v1/fake/fake_vip.go
  pkg/client/clientset/versioned/typed/kubeovn/v1/generated_expansion.go
  pkg/client/clientset/versioned/typed/kubeovn/v1/iptablesdnatrule.go
  pkg/client/clientset/versioned/typed/kubeovn/v1/iptableseip.go
  pkg/client/clientset/versioned/typed/kubeovn/v1/iptablesfiprule.go
  pkg/client/clientset/versioned/typed/kubeovn/v1/iptablessnatrule.go
  pkg/client/clientset/versioned/typed/kubeovn/v1/kubeovn_client.go
  pkg/client/clientset/versioned/typed/kubeovn/v1/vip.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/kubeovn/v1/interface.go
  pkg/client/informers/externalversions/kubeovn/v1/iptablesdnatrule.go
  pkg/client/informers/externalversions/kubeovn/v1/iptableseip.go
  pkg/client/informers/externalversions/kubeovn/v1/iptablesfiprule.go
  pkg/client/informers/externalversions/kubeovn/v1/iptablessnatrule.go
  pkg/client/informers/externalversions/kubeovn/v1/vip.go
  pkg/client/listers/kubeovn/v1/expansion_generated.go
  pkg/client/listers/kubeovn/v1/iptablesdnatrule.go
  pkg/client/listers/kubeovn/v1/iptableseip.go
  pkg/client/listers/kubeovn/v1/iptablesfiprule.go
  pkg/client/listers/kubeovn/v1/iptablessnatrule.go
  pkg/client/listers/kubeovn/v1/vip.go
  pkg/controller/config.go
  pkg/controller/controller.go
  pkg/controller/init.go
  pkg/controller/subnet.go
  pkg/controller/vip.go
  pkg/controller/vpc_nat_gateway.go
  pkg/controller/vpc_nat_gw_eip.go
  pkg/controller/vpc_nat_gw_nat.go
  pkg/ipam/ipam.go
  pkg/util/const.go
Labels: feature

#1494 update document for mellanox hardware offload
  docs/hw-offload-mellanox.md
Labels: docs

#1495 use OVS branch-2.17
  .github/workflows/build-ovs-win64.yaml
  dist/images/Dockerfile.base
Labels: ci
