Repository kubeovn/kube-ovn, pull requests merged in 2022-01, with the labels that each got.

#1219 add kubectl-ko to docker image
  dist/images/.dockerignore
  dist/images/Dockerfile
Labels: enhancement

#1206 fix iptables rules
  Makefile
  dist/images/uninstall.sh
  go.mod
  go.sum
  pkg/controller/config.go
  pkg/daemon/gateway.go
  test/e2e-ebpf/e2e_ebpf_suite_test.go
  test/e2e-ebpf/service/service.go
  test/e2e/e2e_suite_test.go
  test/e2e/service/service.go
  test/e2e/underlay/underlay.go
  yamls/kind.yaml.j2
Labels: bug, test, ci

#1240 kubectl-ko: support trace Pods being created
  dist/images/install.sh
  dist/images/kubectl-ko
Labels: enhancement

#1244 update check for delete statefulset pod
  pkg/controller/pod.go
Labels: bug, need backport

#1249 update networkpolicy port process
  pkg/ovs/ovn-nbctl.go
Labels: bug, need backport

#1262 fix: validate statefulset pod by name
  pkg/controller/pod.go
Labels: bug, need backport

#1270 add gateway check after update subnet
  pkg/controller/subnet.go
Labels: bug, need backport

#1279 set up tunnel correctly in hybrid mode
  cmd/daemon/cniserver.go
  pkg/daemon/config.go
  pkg/daemon/init.go
Labels: bug, need backport

#1274 check static route conflict
  pkg/controller/pod.go
  pkg/daemon/handler.go
  pkg/ovs/ovn-nbctl.go
Labels: bug, need backport

#1261 transfer IP/route after OVS startup
  dist/images/start-ovs.sh
Labels: bug, need backport

#1282 ci: add retry to fix flaky test
  .github/workflows/build-x86-image.yaml
Labels: ci
