Repository kubeovn/kube-ovn, pull requests merged in 2022-08, with the labels that each got.

#1741 avoid patch interface deletion & recreation during restart
  dist/images/Dockerfile.base
Labels: bug, need backport

#1756 replace some of port_group table with libovsdb
  pkg/ovs/ovn-nb-gateway_chassis.go
  pkg/ovs/ovn-nb-load_balancer.go
  pkg/ovs/ovn-nb-logical_router.go
  pkg/ovs/ovn-nb-logical_router_port.go
  pkg/ovs/ovn-nb-logical_switch.go
  pkg/ovs/ovn-nb-logical_switch_port.go
  pkg/ovs/ovn-nb-logical_switch_test.go
  pkg/ovs/ovn-nb-port_group.go
  pkg/ovs/ovn-nb-port_group_test.go
  pkg/ovs/ovn-nb-suite_test.go
Labels: performance

#1764 perf: replace jemalloc to reduce memory usage
  dist/images/Dockerfile.base
Labels: performance, need backport

#1765 fix: add omitempty to subnet spec
  hack/update-codegen-docker.sh
  pkg/apis/kubeovn/v1/types.go
Labels: bug, need backport

#1758 set sysctl variables on cni server startup
  dist/images/start-cniserver.sh
Labels: enhancement, need backport

#1760 replace some of address_set with libovsdb
  pkg/ovs/ovn-nb-address_set.go
  pkg/ovs/ovn-nb-address_set_test.go
  pkg/ovs/ovn-nb-gateway_chassis.go
  pkg/ovs/ovn-nb-load_balancer.go
  pkg/ovs/ovn-nb-logical_switch.go
  pkg/ovs/ovn-nb-logical_switch_port.go
  pkg/ovs/ovn-nb-port_group.go
  pkg/ovs/ovn-nb-port_group_test.go
  pkg/ovs/ovn-nb-suite_test.go
  pkg/ovsdb/client/client.go
Labels: performance

#1728 fix iptables for service traffic when external traffic policy set to local
  .github/workflows/build-x86-image.yaml
  dist/images/uninstall.sh
  pkg/daemon/gateway_linux.go
Labels: bug, need backport

#1770 replace some of acl table with libovsdb
  pkg/ovs/ovn-nb-acl.go
  pkg/ovs/ovn-nb-acl_test.go
  pkg/ovs/ovn-nb-address_set.go
  pkg/ovs/ovn-nb-address_set_test.go
  pkg/ovs/ovn-nb-logical_switch_port.go
  pkg/ovs/ovn-nb-logical_switch_port_test.go
  pkg/ovs/ovn-nb-port_group.go
  pkg/ovs/ovn-nb-port_group_test.go
  pkg/ovs/ovn-nb-suite_test.go
  pkg/ovs/util.go
  pkg/ovs/util_test.go
Labels: performance

#1781 fix: 5ms is too short for eip and nats creation
  pkg/controller/config.go
  pkg/controller/controller.go
  pkg/controller/vpc_nat_gateway.go
  pkg/controller/vpc_nat_gw_eip.go
  pkg/controller/vpc_nat_gw_nat.go
Labels: bug, need backport

#1780 northd: remove lookup_arp_ip actions
  dist/images/Dockerfile.base
Labels: bug, need backport

#1776 replace some of acl table with libovsdb
  pkg/ovs/ovn-nb-acl.go
  pkg/ovs/ovn-nb-acl_test.go
  pkg/ovs/ovn-nb-gateway_chassis.go
  pkg/ovs/ovn-nb-gateway_chassis_test.go
  pkg/ovs/ovn-nb-suite_test.go
  pkg/ovs/util.go
  pkg/ovs/util_test.go
Labels: performance

#1784 perf: reduce metrics labels
  pkg/controller/client_go_adapter.go
  pkg/daemon/metrics.go
Labels: bug, performance, need backport

#1773 fix iptables for services with external traffic policy set to Local
  .github/workflows/build-x86-image.yaml
  dist/images/uninstall.sh
  pkg/daemon/gateway_linux.go
Labels: bug, need backport

#1788 delete htb qos when releated annotation is deleted
  pkg/ovs/ovs-vsctl_linux.go
Labels: bug, need backport

#1791 Perf/memleak
  dist/images/Dockerfile.base
  dist/images/start-ovs.sh
Labels: performance, need backport

#1793 done for acl table replacment
  pkg/ovs/ovn-nb-acl.go
  pkg/ovs/ovn-nb-acl_test.go
  pkg/ovs/ovn-nb-address_set.go
  pkg/ovs/ovn-nb-address_set_test.go
  pkg/ovs/ovn-nb-logical_router_port.go
  pkg/ovs/ovn-nb-logical_switch.go
  pkg/ovs/ovn-nb-logical_switch_port.go
  pkg/ovs/ovn-nb-logical_switch_test.go
  pkg/ovs/ovn-nb-port_group_test.go
  pkg/ovs/ovn-nb-suite_test.go
  pkg/ovs/ovn-nb.go
Labels: performance

#1799 avoid invalid ovn-nbctl daemon socket path
  pkg/ovs/ovn-nbctl-legacy.go
Labels: bug, need backport

#1797 abort kube-ovn-controller on leader change
  pkg/controller/election.go
Labels: bug, need backport

#1801 kubectl-ko: fix destination mac
  dist/images/kubectl-ko
Labels: bug, need backport

#1804 kubectl-ko: fix missing env-check
  dist/images/kubectl-ko
Labels: bug, need backport

#1812 initialize IPAM from IP CR with empty PodType for sts Pods
  pkg/controller/init.go
Labels: bug, need backport

#1817 release-1.8: do not check static route conflict
  pkg/controller/pod.go
  pkg/ovs/ovn-nbctl.go
Labels: bug

#1820 replace some of logical_router_policy with libovsdb
  pkg/ovs/ovn-nb-acl.go
  pkg/ovs/ovn-nb-acl_test.go
  pkg/ovs/ovn-nb-logical_router.go
  pkg/ovs/ovn-nb-logical_router_policy.go
  pkg/ovs/ovn-nb-logical_router_policy_test.go
  pkg/ovs/ovn-nb-logical_router_test.go
  pkg/ovs/ovn-nb-logical_switch_test.go
  pkg/ovs/ovn-nb-suite_test.go
  pkg/ovs/ovn-nb.go
  pkg/ovs/ovn-nb_test.go
  pkg/ovsdb/client/client.go
Labels: performance

#1825 fix: use full longest word to match full ip about dnat
  dist/images/vpcnatgateway/nat-gateway.sh
Labels: bug, need backport

#1821 update ovs/ovn version to fix hardware offload
  dist/images/Dockerfile.base
Labels: bug, need backport

#1823 fix duplicate log for tunnel interface decision
  pkg/daemon/config.go
  pkg/daemon/controller_linux.go
Labels: bug, need backport

#1822 remove pod security policy
  charts/templates/ovn-CR.yaml
  charts/templates/ovnconfig-cm.yaml
  dist/images/install.sh
  yamls/ovn-dpdk.yaml
  yamls/ovn-ha.yaml
  yamls/ovn.yaml
Labels: enhancement

#1762 support adding routes in underlay Pods for access to overlay Pods
  .github/workflows/build-x86-image.yaml
  dist/images/install.sh
  pkg/apis/kubeovn/v1/types.go
  pkg/daemon/handler.go
  test/e2e-underlay-single-nic/e2e_suite_test.go
  test/e2e-underlay-single-nic/overlay/overlay.go
  yamls/crd.yaml
Labels: feature

#1831 修改 ovs-ovn-dpdk 容器镜像编译打包，解决容器中 ovs 运行不正常：无法添加物理网卡，无法创建 vhostuserclient port 问题
  dist/images/Dockerfile.base-dpdk
  dist/images/start-ovs-dpdk-v2.sh
Labels: bug, need backport

#1830 windows: fix ovs/ovn versions and patches
  .github/workflows/build-windows.yaml
Labels: bug, need backport

#1829 CI: update Go cache to speed up jobs
  .github/workflows/build-arm64-image.yaml
  .github/workflows/build-dpdk-image.yaml
  .github/workflows/build-kube-ovn-base-dpdk.yaml
  .github/workflows/build-kube-ovn-base.yaml
  .github/workflows/build-windows.yaml
  .github/workflows/build-x86-image.yaml
Labels: ci

#1807 ci: split image builds to speed up jobs
  .github/workflows/build-x86-image.yaml
  Makefile
Labels: ci

#1838 ci: switch environment to ubuntu-20.04
  .github/workflows/build-arm64-image.yaml
  .github/workflows/build-dpdk-image.yaml
  .github/workflows/codeql-analysis.yml
  .github/workflows/lint.yaml
  .github/workflows/push-multiarch-image.yaml
Labels: ci, need backport

#1844 base: use patch from OVN upstream
  dist/images/Dockerfile.base
Labels: need backport

#1842 ko: fix kube-proxy check
  dist/images/install.sh
  dist/images/kubectl-ko
Labels: bug, need backport

#1841 fix arping error log
  pkg/util/arping.go
Labels: bug, need backport

#1828 fix underlay e2e
  test/e2e/underlay/underlay.go
Labels: test, need backport

#1843 fix: multus macvlan ipvlan use kube-ovn ipam，but ip not inited in init-ipam
  pkg/controller/init.go
Labels: bug, need backport

#1853 fix ovn dhcp not work with ovs-dpdk
  dist/images/Dockerfile.base-dpdk
  dist/images/start-ovs-dpdk-v2.sh
Labels: bug, need backport

#1848 fix ovs-ovn logging
  dist/images/start-ic-db.sh
  dist/images/start-ovs-dpdk-v2.sh
  dist/images/start-ovs-dpdk.sh
  dist/images/start-ovs.sh
Labels: bug, need backport

#1854 fix: dnat port not use whole words to check
  dist/images/vpcnatgateway/nat-gateway.sh
Labels: bug, need backport

#1855 ovs: fix log file descriptor leak in monitor process
  dist/images/Dockerfile.base
Labels: bug, need backport

#1861 upgrade to Ginkgo v2
  .github/workflows/build-x86-image.yaml
  Makefile
  docs/development.md
  go.mod
  go.sum
  test/e2e-ebpf/e2e_ebpf_suite_test.go
  test/e2e-multus/e2e_multus_suite_test.go
  test/e2e-multus/lbsvc/lbsvc.go
  test/e2e-ovnic/e2e_suite_test.go
  test/e2e-underlay-single-nic/e2e_suite_test.go
  test/e2e-underlay-single-nic/kubectl-ko/ko.go
  test/e2e-underlay-single-nic/node/node.go
  test/e2e-underlay-single-nic/overlay/overlay.go
  test/e2e/e2e_suite_test.go
  test/e2e/framework/framework.go
  test/e2e/ip/static_ip.go
  test/e2e/kubectl-ko/ko.go
  test/e2e/node/node.go
  test/e2e/qos/qos.go
  test/e2e/service/service.go
  test/e2e/subnet/normal.go
  test/e2e/underlay/underlay.go
  test/unittest/ipam/ipam.go
  test/unittest/unit_suite_test.go
  test/unittest/util/net.go
Labels: test, ci

#1871 e2e: add timeout for waiting resources to be ready
  test/e2e/framework/framework.go
Labels: test, ci

#1860 sec: conform to Gosec [G114](https://github.com/securego/gosec\#avail…
  cmd/controller/controller.go
  cmd/daemon/cniserver.go
  cmd/ovn_monitor/ovn_monitor.go
  cmd/pinger/pinger.go
  cmd/speaker/speaker.go
Labels: security

#1872 delete and recreate netem qos when update process
  pkg/ovs/ovs-vsctl.go
  pkg/ovs/ovs-vsctl_linux.go
Labels: bug, need backport
