Repository kubeovn/kube-ovn, pull requests merged in 2022-07, with the labels that each got.

#1654 bug fix:can not delete pod with sriov vf
  pkg/daemon/ovs_linux.go
Labels: bug, need backport

#1663 fix: get security group name error by external_ids:associated_sg_xxx
  pkg/controller/security_group.go
Labels: bug, need backport

#1661 fix ovs-ovn not running on newly added nodes
  dist/images/install.sh
Labels: bug, need backport

#1664 fix libovsdb
  go.mod
  go.sum
  pkg/ovsdb/client/client.go
Labels: bug, need backport

#1666 ignore pod not scheduled when reconcile subnet
  pkg/controller/subnet.go
Labels: bug, need backport

#1653 fix: subnet failed when create without protocol
  Makefile
  pkg/controller/subnet.go
Labels: bug, need backport

#1665 mount modules for auto load ip6tables moudles
  dist/images/install.sh
  yamls/kube-ovn-dual-stack.yaml
  yamls/kube-ovn-ipv6.yaml
  yamls/kube-ovn.yaml
Labels: bug, need backport

#1669 fix: kubectl-ko does't work when ovn-nb, ovn-sb and ovn-northd master slave Switchover
  pkg/ovn_leader_checker/ovn.go
  pkg/ovn_leader_checker/ovn_test.go
Labels: bug, need backport

#1650 feature: support pod use static vip
  pkg/controller/gc.go
  pkg/controller/init.go
  pkg/controller/pod.go
  pkg/controller/subnet.go
  pkg/controller/vip.go
  pkg/controller/vpc_nat_gw_eip.go
  pkg/util/const.go
Labels: feature, need docs, need test

#1578 fix iptables for direct routing
  dist/images/cleanup.sh
  dist/images/uninstall.sh
  pkg/daemon/gateway_linux.go
Labels: bug, need backport

#1673 fix bgp: sync service cache
  pkg/speaker/controller.go
Labels: bug, need backport

#1672 security: disable pprof by default
  cmd/controller/controller.go
  cmd/daemon/cniserver.go
  pkg/controller/config.go
  pkg/daemon/config.go
Labels: security, need backport

#1674 bgp: consolidate service check and use service const
  pkg/speaker/controller.go
  pkg/speaker/subnet.go
Labels: need backport

#1671 refactor: extract external routes from eip func, make it the same as …
  dist/images/vpcnatgateway/nat-gateway.sh
  pkg/controller/vpc_nat_gateway.go
Labels: feature

#1616 do not snat packets only for subnets with distributed gateway when external traffic policy is set to local
  .github/workflows/build-x86-image.yaml
  dist/images/uninstall.sh
  pkg/daemon/gateway.go
  pkg/daemon/gateway_linux.go
Labels: need backport

#1656 Develop switch lb rule
  charts/templates/ovn-CR.yaml
  dist/images/cleanup.sh
  dist/images/install.sh
  pkg/apis/kubeovn/v1/register.go
  pkg/apis/kubeovn/v1/types.go
  pkg/apis/kubeovn/v1/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/typed/kubeovn/v1/fake/fake_kubeovn_client.go
  pkg/client/clientset/versioned/typed/kubeovn/v1/fake/fake_switchlbrule.go
  pkg/client/clientset/versioned/typed/kubeovn/v1/generated_expansion.go
  pkg/client/clientset/versioned/typed/kubeovn/v1/kubeovn_client.go
  pkg/client/clientset/versioned/typed/kubeovn/v1/switchlbrule.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/kubeovn/v1/interface.go
  pkg/client/informers/externalversions/kubeovn/v1/switchlbrule.go
  pkg/client/listers/kubeovn/v1/expansion_generated.go
  pkg/client/listers/kubeovn/v1/switchlbrule.go
  pkg/controller/controller.go
  pkg/controller/endpoint.go
  pkg/controller/gc.go
  pkg/controller/service.go
  pkg/controller/switch_lb_rule.go
  pkg/util/const.go
  yamls/ovn.yaml
Labels: feature, need docs, need test

#1670 fix: sync ovn-ic static route to policy
  pkg/controller/controller.go
  pkg/controller/ovn-ic.go
  pkg/ovs/ovn-nb-logical_router_policy.go
  pkg/ovs/ovn-nb-logical_router_route.go
  pkg/ovsdb/client/client.go
  pkg/util/const.go
Labels: bug, need backport

#1688 update priority range in htb qos
  docs/qos.md
  pkg/controller/init.go
  test/e2e/qos/qos.go
Labels: bug, need backport

#1699 add note in install.sh for install --with-hybrid-dpdk(dpdk-v2).
  dist/images/install.sh
Labels: docs

#1694 replace most of logical_router_port table with libovsdb
  Makefile
  pkg/ovs/ovn-nb-gateway_chassis.go
  pkg/ovs/ovn-nb-gateway_chassis_test.go
  pkg/ovs/ovn-nb-logical_router.go
  pkg/ovs/ovn-nb-logical_router_port.go
  pkg/ovs/ovn-nb-logical_router_port_test.go
  pkg/ovs/ovn-nb-logical_router_test.go
  pkg/ovs/ovn-nb-suite_test.go
  pkg/ovs/ovn-nbctl-legacy_test.go
  pkg/ovs/util.go
  pkg/ovs/util_test.go
  pkg/ovsdb/client/client.go
Labels: performance

#1703 fix: response has no gw when create nic without default route
  cmd/cni/cni.go
Labels: bug, need backport

#1693 fix MTU in overlay networks
  dist/images/install.sh
  docs/dual-stack.md
  docs/install.md
  docs/ipv6.md
  pkg/daemon/config.go
  pkg/util/const.go
Labels: bug, need backport

#1710 fix CVE-2022-30065
  dist/images/vpcnatgateway/Dockerfile
Labels: security, need backport

#1662 Develop custom vpc-dns
  dist/images/cleanup.sh
  dist/images/install.sh
  pkg/apis/kubeovn/v1/register.go
  pkg/apis/kubeovn/v1/types.go
  pkg/apis/kubeovn/v1/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/typed/kubeovn/v1/fake/fake_kubeovn_client.go
  pkg/client/clientset/versioned/typed/kubeovn/v1/fake/fake_vpcdns.go
  pkg/client/clientset/versioned/typed/kubeovn/v1/generated_expansion.go
  pkg/client/clientset/versioned/typed/kubeovn/v1/kubeovn_client.go
  pkg/client/clientset/versioned/typed/kubeovn/v1/vpcdns.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/kubeovn/v1/interface.go
  pkg/client/informers/externalversions/kubeovn/v1/vpcdns.go
  pkg/client/listers/kubeovn/v1/expansion_generated.go
  pkg/client/listers/kubeovn/v1/vpcdns.go
  pkg/controller/controller.go
  pkg/controller/gc.go
  pkg/controller/vpc_dns.go
  pkg/util/const.go
  yamls/coredns-template.yaml
Labels: feature, need docs, need test

#1713 add kernel prerequisite for Rocky Linux 8.6
  docs/install.md
Labels: docs

#1718 fix: new ovn-ic static route method adapted due to old ovn version
  pkg/controller/ovn-ic.go
  pkg/ovs/ovn-nb-logical_router_route.go
  pkg/util/const.go
Labels: bug

#1719 replace some of logical_switch_port table with libovsdb
  pkg/ovs/ovn-nb-logical_router.go
  pkg/ovs/ovn-nb-logical_router_port.go
  pkg/ovs/ovn-nb-logical_router_port_test.go
  pkg/ovs/ovn-nb-logical_router_test.go
  pkg/ovs/ovn-nb-logical_switch_port.go
  pkg/ovs/ovn-nb-logical_switch_port_test.go
  pkg/ovs/ovn-nb-suite_test.go
  pkg/ovs/ovn-nb.go
Labels: performance

#1726 fix: wrong info when update subnet from dual to ipv4 or ipv6.
  pkg/controller/subnet.go
Labels: bug, need backport

#1733 fix: cancel delete staticroute when it's used by NatRule
  pkg/controller/gc.go
  pkg/ovs/ovn-nbctl-legacy.go
Labels: bug, need backport

#1712 optimize lrp create for subnet in vpc
  pkg/controller/subnet.go
  pkg/controller/vpc.go
  pkg/ovs/ovn-nb-logical_switch.go
  pkg/ovs/ovn-nb-logical_switch_port.go
  pkg/ovs/ovn-nbctl-legacy.go
Labels: bug, need backport

#1724 fix service not working when a node's IPv6 address is before the IPv4 address
  pkg/util/net.go
Labels: bug, need backport

#1735 do not add subnet not processed by kube-ovn to vpc
  pkg/controller/vpc.go
Labels: bug, need backport

#1722 enqueue subnets after vpc update
  pkg/controller/vpc.go
Labels: bug, need backport

#1737 replace CreatePort function with libovsdb
  pkg/controller/config.go
  pkg/ovs/ovn-nb-logical_switch_port.go
  pkg/ovs/ovn-nb-logical_switch_port_test.go
  pkg/ovs/ovn-nb-suite_test.go
  pkg/util/const.go
Labels: performance

#1744 done for logical_switch_port replacment with libovsdb
  pkg/ovs/ovn-nb-logical_switch_port.go
  pkg/ovs/ovn-nb-logical_switch_port_test.go
  pkg/ovs/ovn-nb-suite_test.go
Labels: performance

#1750 repalce some of lb table with libovsdb
  pkg/ovs/ovn-nb-gateway_chassis.go
  pkg/ovs/ovn-nb-gateway_chassis_test.go
  pkg/ovs/ovn-nb-load_balancer.go
  pkg/ovs/ovn-nb-load_balancer_test.go
  pkg/ovs/ovn-nb-logical_router.go
  pkg/ovs/ovn-nb-logical_router_test.go
  pkg/ovs/ovn-nb-logical_switch.go
  pkg/ovs/ovn-nb-logical_switch_port.go
  pkg/ovs/ovn-nb-logical_switch_test.go
  pkg/ovs/ovn-nb-suite_test.go
  pkg/ovsdb/client/client.go
Labels: performance

#1752 done for lb table replacement with libovsdb
  pkg/ovs/ovn-nb-load_balancer.go
  pkg/ovs/ovn-nb-load_balancer_test.go
  pkg/ovs/ovn-nb-logical_router.go
  pkg/ovs/ovn-nb-logical_router_port.go
  pkg/ovs/ovn-nb-logical_router_test.go
  pkg/ovs/ovn-nb-logical_switch.go
  pkg/ovs/ovn-nb-logical_switch_port.go
  pkg/ovs/ovn-nb-logical_switch_test.go
  pkg/ovs/ovn-nb-suite_test.go
  pkg/ovs/ovn-nb.go
  pkg/ovs/ovn-nb_test.go
Labels: performance

#1755 replace CreateGatewaySwitch and DeleteGatewaySwitch func with libovsdb
  go.mod
  go.sum
  pkg/ovs/ovn-nb-gateway_chassis.go
  pkg/ovs/ovn-nb-load_balancer.go
  pkg/ovs/ovn-nb-load_balancer_test.go
  pkg/ovs/ovn-nb-logical_router.go
  pkg/ovs/ovn-nb-logical_router_port.go
  pkg/ovs/ovn-nb-logical_router_port_test.go
  pkg/ovs/ovn-nb-logical_switch.go
  pkg/ovs/ovn-nb-logical_switch_port.go
  pkg/ovs/ovn-nb-logical_switch_port_test.go
  pkg/ovs/ovn-nb-suite_test.go
  pkg/ovs/ovn-nb.go
  pkg/ovs/ovn-nb_global.go
  pkg/ovs/ovn-nb_test.go
Labels: performance

#1736 feature: support exchange link names of OVS bridge and provider nic in underlay networks
  dist/images/install.sh
  dist/images/start-ovs.sh
  go.mod
  go.sum
  pkg/apis/kubeovn/v1/types.go
  pkg/controller/config.go
  pkg/controller/init.go
  pkg/daemon/controller.go
  pkg/daemon/init.go
  pkg/daemon/init_linux.go
  pkg/daemon/init_windows.go
  pkg/daemon/ovs.go
  pkg/daemon/ovs_linux.go
  test/e2e/e2e_suite_test.go
  test/e2e/underlay/underlay.go
  yamls/crd.yaml
Labels: feature
