Repository kubeovn/kube-ovn, pull requests merged in 2022-11, with the labels that each got.

#2004 ci: upgrade deprecated actions
  .github/workflows/build-x86-image.yaml
Labels: ci, need backport

#2010 test: add test-server to collect packet lost during upgrade
  Makefile
  dist/images/Dockerfile.test
  dist/images/test-server.sh
  test/server/README.md
  test/server/server.go
  test/server/test-server.yaml
Labels: test

#1959 do not need to delete pg when update networkpolicy
  pkg/controller/network_policy.go
  pkg/ovs/ovn-nbctl-legacy.go
Labels: bug, need backport

#2017 perf: add debug info for perf trace
  .github/workflows/build-kube-ovn-debug.yaml
  Makefile
  dist/images/Dockerfile.debug
Labels: performance

#2014 fix ovs fdb for the local bridge port
  pkg/daemon/ovs_linux.go
Labels: bug, need backport

#2019 fix ovn nb/sb health check
  dist/images/ovn-healthcheck.sh
Labels: bug, need backport

#2023 bump kind and node image versions
  .github/workflows/build-x86-image.yaml
  yamls/kind.yaml.j2
Labels: test, ci, need backport

#2028 iptables: avoid duplicate logging
  pkg/daemon/gateway_linux.go
Labels: bug, need backport

#2034 bug fix: pinger crashed when change --ds-namespace=other-namespace
  pkg/pinger/config.go
Labels: bug, need backport

#2038 ovs: fix reaching resubmit limit in underlay
  dist/images/Dockerfile.base
Labels: bug, need backport

#2048 pass klog verbosity to libovsdb
  go.mod
  go.sum
  pkg/controller/config.go
  pkg/controller/controller.go
  pkg/ovs/ovn.go
  pkg/ovsdb/client/client.go
Labels: need backport

#1901 refactor Makefile
  .github/workflows/build-arm64-image.yaml
  .github/workflows/build-dpdk-image.yaml
  .github/workflows/build-kube-ovn-base-dpdk.yaml
  .github/workflows/build-kube-ovn-base.yaml
  .github/workflows/build-kube-ovn-debug.yaml
  .github/workflows/build-x86-image.yaml
  .github/workflows/codeql-analysis.yml
  .github/workflows/lint.yaml
  .github/workflows/push-multiarch-image.yaml
  .gitignore
  Makefile
  dist/images/install.sh
  test/e2e-cilium/e2e_cilium_suite_test.go
  test/e2e-ovn-ic/e2e_suite_test.go
  test/e2e-underlay-single-nic/node/network.json
  test/e2e-underlay-single-nic/node/node.go
  test/e2e/e2e_suite_test.go
  test/e2e/network.json
  test/e2e/underlay/underlay.go
  test/kind-vlan.sh
  yamls/kind.yaml.j2
Labels: test, ci, need backport

#2054 perf: reduce controller init time
  pkg/controller/election.go
  pkg/controller/gc.go
Labels: performance

#2060 update ipv6 address for vpc peer
  pkg/ovs/ovn-nbctl-legacy.go
Labels: bug, need backport

#2057 remove no need params svcasname
  pkg/controller/network_policy.go
  pkg/ovs/ovn-nbctl-legacy.go
Labels: refactor

#2069 fix OVN LS/LB gc
  pkg/controller/gc.go
Labels: bug, need backport

#2067 refactor: add unknown config to logic switch port
  pkg/controller/node.go
  pkg/controller/pod.go
  pkg/ovs/ovn-nbctl-legacy.go
Labels: refactor

#2074 fix: do not change lrp even if restart kube ovn controller
  pkg/controller/external-gw.go
  pkg/controller/gc.go
  pkg/controller/node.go
  pkg/controller/pod.go
  pkg/controller/subnet.go
  pkg/controller/vip.go
  pkg/controller/vlan.go
  pkg/controller/vpc.go
  pkg/ovs/ovn-nb-logical_router_port.go
  pkg/ovs/ovn-nbctl-legacy.go
Labels: bug

#2086 ipset: fix unknown ipset data attribute from kernel
  go.mod
  go.sum
  pkg/daemon/gateway_linux.go
Labels: bug, need backport

#2070 fix libovsdb issues
  go.mod
  go.sum
  pkg/controller/config.go
  pkg/controller/controller.go
  pkg/ovs/ovn-nb-logical_router.go
  pkg/ovs/ovn-nb-logical_router_port.go
  pkg/ovs/ovn-nb-logical_router_route.go
  pkg/ovs/ovn-nb-logical_switch_port.go
  pkg/ovs/ovn-nb-port_group.go
  pkg/ovs/ovn.go
  pkg/ovsdb/client/client.go
  pkg/ovsdb/ovnnb/acl.go
  pkg/ovsdb/ovnnb/address_set.go
  pkg/ovsdb/ovnnb/bfd.go
  pkg/ovsdb/ovnnb/connection.go
  pkg/ovsdb/ovnnb/copp.go
  pkg/ovsdb/ovnnb/dhcp_options.go
  pkg/ovsdb/ovnnb/dns.go
  pkg/ovsdb/ovnnb/forwarding_group.go
  pkg/ovsdb/ovnnb/gateway_chassis.go
  pkg/ovsdb/ovnnb/ha_chassis.go
  pkg/ovsdb/ovnnb/ha_chassis_group.go
  pkg/ovsdb/ovnnb/load_balancer.go
  pkg/ovsdb/ovnnb/load_balancer_group.go
  pkg/ovsdb/ovnnb/load_balancer_health_check.go
  pkg/ovsdb/ovnnb/logical_router.go
  pkg/ovsdb/ovnnb/logical_router_policy.go
  pkg/ovsdb/ovnnb/logical_router_port.go
  pkg/ovsdb/ovnnb/logical_router_static_route.go
  pkg/ovsdb/ovnnb/logical_switch.go
  pkg/ovsdb/ovnnb/logical_switch_port.go
  pkg/ovsdb/ovnnb/meter.go
  pkg/ovsdb/ovnnb/meter_band.go
  pkg/ovsdb/ovnnb/model.go
  pkg/ovsdb/ovnnb/nat.go
  pkg/ovsdb/ovnnb/nb_global.go
  pkg/ovsdb/ovnnb/port_group.go
  pkg/ovsdb/ovnnb/qos.go
  pkg/ovsdb/ovnnb/ssl.go
Labels: bug, need backport

#2084 fix ovs bridge not deleted cause by port link not found
  pkg/daemon/ovs_linux.go
Labels: bug, need backport

#2089 fix: cni response missing sandbox field
  cmd/cni/cni.go
Labels: bug, need backport

#2046 ko-trace: support ARP request/reply
  dist/images/kubectl-ko
Labels: feature

#2093 replace klog.Fatalf with klog.ErrorS and klog.FlushAndExit
  cmd/cmdmain.go
  cmd/controller/controller.go
  cmd/controller_health_check/controller_health_check.go
  cmd/daemon/cniserver.go
  cmd/ovn_leader_checker/ovn_leader_checker.go
  cmd/ovn_monitor/ovn_monitor.go
  cmd/pinger/pinger.go
  cmd/speaker/speaker.go
  cmd/webhook/server.go
  pkg/controller/config.go
  pkg/controller/controller.go
  pkg/controller/election.go
  pkg/daemon/config.go
  pkg/daemon/controller.go
  pkg/daemon/ovs_linux.go
  pkg/ovn_leader_checker/ovn.go
  pkg/ovnmonitor/exporter.go
  pkg/pinger/config.go
  pkg/speaker/config.go
  pkg/speaker/controller.go
  pkg/util/klog.go
  pkg/util/net.go
Labels: bug, need backport
