Repository kubeovn/kube-ovn, pull requests merged in 2022-05, with the labels that each got.

#1506 test: fix flaky test
  Makefile
  test/e2e/subnet/normal.go
Labels: test, ci

#1498 optimize IPAM initialization
  docs/development.md
  go.mod
  pkg/controller/init.go
  pkg/controller/node.go
  pkg/controller/pod.go
  pkg/ovs/ovn-nbctl.go
Labels: performance, need backport

#1508 fix: ovs trace flow always ends with controller action
  dist/images/install.sh
  dist/images/kubectl-ko
Labels: bug

#1500 refactor logical router policy routes
  pkg/controller/gc.go
  pkg/controller/init.go
  pkg/controller/node.go
  pkg/controller/pod.go
  pkg/controller/subnet.go
  pkg/controller/vpc.go
  pkg/ovs/ovn-nbctl.go
  pkg/util/const.go
  test/e2e/qos/qos.go
  test/e2e/subnet/normal.go
Labels: bug

#1463 finish basic windows support
  .github/workflows/build-ovs-win64.yaml
  .github/workflows/build-windows.yaml
  .gitignore
  Makefile
  cmd/cni/cni.go
  cmd/cni/netconf.go
  cmd/cni/netconf_windows.go
  cmd/daemon/cniserver.go
  cmd/daemon/init.go
  cmd/daemon/init_windows.go
  dist/windows/01-kube-ovn.conflist
  dist/windows/install.ps1
  dist/windows/kube-ovn.conf
  dist/windows/ovn-controller.conf
  dist/windows/start-kube-ovn.ps1
  dist/windows/start-ovn-controller.ps1
  go.mod
  go.sum
  pkg/daemon/config.go
  pkg/daemon/config_linux.go
  pkg/daemon/config_windows.go
  pkg/daemon/controller.go
  pkg/daemon/controller_linux.go
  pkg/daemon/controller_windows.go
  pkg/daemon/ovs_windows.go
  pkg/ovs/ovs-vsctl_linux.go
  pkg/ovs/ovs-vsctl_windows.go
  pkg/util/const_linux.go
  pkg/util/const_windows.go
  pkg/util/network_windows.go
Labels: feature

#1516 reduce ovs-ovn restart downtime
  Makefile
  dist/images/start-ovs.sh
Labels: enhancement, need backport

#1515 add document for windows support
  README.md
  dist/windows/PrepareNode.ps1
  docs/windows-support.md
Labels: docs

#1520 fix: keep vm's and statefulset's ips when user specified subnet
  pkg/controller/pod.go
Labels: bug, need backport

#1524 fix arm image
  dist/images/Dockerfile
Labels: bug

#1523 fix defunct ovn-nbctl daemon
  dist/images/Dockerfile.base
  dist/images/install.sh
  yamls/kube-ovn-dual-stack.yaml
  yamls/kube-ovn-ipv6.yaml
  yamls/kube-ovn.yaml
Labels: bug, need backport

#1514 optimize node port-group check
  pkg/controller/config.go
  pkg/controller/controller.go
  pkg/controller/node.go
  pkg/ovs/ovn-nbctl.go
Labels: performance, need backport

#1518 optimize ovs request in cni
  pkg/daemon/controller.go
  pkg/daemon/controller_linux.go
  pkg/daemon/controller_windows.go
  pkg/daemon/gateway.go
  pkg/daemon/handler.go
  pkg/ovs/ovs-vsctl_linux.go
  test/e2e/qos/qos.go
Labels: enhancement, need backport

#1525 fix installing dumb-init in arm64 image
  dist/images/Dockerfile.base
Labels: bug

#1527 move dumb-init from base images to kube-ovn image
  dist/images/Dockerfile
  dist/images/Dockerfile.base
Labels: bug

#1530 update kind to v0.13.0
  .github/workflows/build-x86-image.yaml
  yamls/kind.yaml.j2
Labels: test, ci

#1528 use inc-engine/recompute instead of deprecated recompute
  pkg/daemon/controller.go
  pkg/daemon/controller_linux.go
  pkg/daemon/controller_windows.go
Labels: enhancement

#1522 remove name for default drop acl in networkpolicy
  pkg/controller/network_policy.go
  pkg/ovs/ovn-nbctl.go
Labels: bug, need backport

#1531 fix: tmp cancel cilium external svc test
  test/e2e/service/service.go
Labels: bug

#1534 fix: update check script for restart ovs-ovn after rebuild ovsdb
  dist/images/db_autocheck_script.sh
Labels: bug

#1536 exit kube-ovn-controller on stopped leading
  pkg/controller/election.go
Labels: bug, need backport

#1529 use leases for leader election
  dist/images/install.sh
  pkg/controller/election.go
  yamls/ovn-dpdk.yaml
  yamls/ovn-ha.yaml
  yamls/ovn.yaml
Labels: enhancement

#1550 fix: opt kubectl-ko install solution
  dist/images/install-cni.sh
  dist/images/install.sh
  dist/images/kubectl-ko
Labels: enhancement

#1539 feature: add charts 1.9
  charts/Chart.yaml
  charts/README.md
  charts/templates/central-deploy.yaml
  charts/templates/controller-deploy.yaml
  charts/templates/controller-svc.yaml
  charts/templates/kubeovn-crd.yaml
  charts/templates/monitor-deploy.yaml
  charts/templates/monitor-svc.yaml
  charts/templates/nb-svc.yaml
  charts/templates/northd-svc.yaml
  charts/templates/ovn-CR.yaml
  charts/templates/ovn-CRB.yaml
  charts/templates/ovn-sa.yaml
  charts/templates/ovncni-ds.yaml
  charts/templates/ovncni-svc.yaml
  charts/templates/ovnconfig-cm.yaml
  charts/templates/ovsovn-ds.yaml
  charts/templates/pinger-ds.yaml
  charts/templates/pinger-svc.yaml
  charts/templates/sb-svc.yaml
  charts/values.yaml
Labels: feature

#1552 do not nat packets for incoming traffic when service externalTrafficPolicy is Local
  dist/images/uninstall.sh
  pkg/daemon/gateway_linux.go
Labels: bug, need backport

#1555 CNI: do not return route if nic is not eth0
  cmd/cni/cni.go
  pkg/daemon/handler.go
Labels: bug, need backport

#1556 fix exec cmd in vpc nat gateway
  dist/images/vpcnatgateway/nat-gateway.sh
Labels: bug, need backport

#1544 replace ovn-nbctl daemon with libovsdb in frequent operations
  go.mod
  go.sum
  pkg/apis/kubeovn/v1/types.go
  pkg/controller/controller.go
  pkg/controller/endpoint.go
  pkg/controller/external-gw.go
  pkg/controller/external_vpc.go
  pkg/controller/gc.go
  pkg/controller/init.go
  pkg/controller/inspection.go
  pkg/controller/network_policy.go
  pkg/controller/node.go
  pkg/controller/ovn-ic.go
  pkg/controller/pod.go
  pkg/controller/security_group.go
  pkg/controller/service.go
  pkg/controller/subnet.go
  pkg/controller/vlan.go
  pkg/controller/vpc.go
  pkg/ovs/ovn-ic-nbctl.go
  pkg/ovs/ovn-nb-logical_switch_port.go
  pkg/ovs/ovn-nb-port_group.go
  pkg/ovs/ovn-nbctl-legacy.go
  pkg/ovs/ovn-nbctl-legacy_test.go
  pkg/ovs/ovn-sbctl.go
  pkg/ovs/ovn.go
  pkg/ovsdb/client/client.go
  pkg/ovsdb/ovnnb/acl.go
  pkg/ovsdb/ovnnb/address_set.go
  pkg/ovsdb/ovnnb/bfd.go
  pkg/ovsdb/ovnnb/connection.go
  pkg/ovsdb/ovnnb/copp.go
  pkg/ovsdb/ovnnb/dhcp_options.go
  pkg/ovsdb/ovnnb/dns.go
  pkg/ovsdb/ovnnb/forwarding_group.go
  pkg/ovsdb/ovnnb/gateway_chassis.go
  pkg/ovsdb/ovnnb/ha_chassis.go
  pkg/ovsdb/ovnnb/ha_chassis_group.go
  pkg/ovsdb/ovnnb/load_balancer.go
  pkg/ovsdb/ovnnb/load_balancer_group.go
  pkg/ovsdb/ovnnb/load_balancer_health_check.go
  pkg/ovsdb/ovnnb/logical_router.go
  pkg/ovsdb/ovnnb/logical_router_policy.go
  pkg/ovsdb/ovnnb/logical_router_port.go
  pkg/ovsdb/ovnnb/logical_router_static_route.go
  pkg/ovsdb/ovnnb/logical_switch.go
  pkg/ovsdb/ovnnb/logical_switch_port.go
  pkg/ovsdb/ovnnb/meter.go
  pkg/ovsdb/ovnnb/meter_band.go
  pkg/ovsdb/ovnnb/model.go
  pkg/ovsdb/ovnnb/nat.go
  pkg/ovsdb/ovnnb/nb_global.go
  pkg/ovsdb/ovnnb/port_group.go
  pkg/ovsdb/ovnnb/qos.go
  pkg/ovsdb/ovnnb/ssl.go
Labels: performance, need backport

#1554 fix VPC document
  docs/vpc.md
Labels: docs

#1560 do not delete static routes on controller startup
  pkg/controller/controller.go
  pkg/controller/init.go
Labels: performance, need backport

#1563 fix: clean CRDs introduced by new vpc-nat-gateway
  dist/images/cleanup.sh
Labels: bug, need backport

#1567 Fix incorrect usage info of 'argExternalGatewayNet'
  pkg/controller/config.go
Labels: bug
