Repository kubeovn/kube-ovn, pull requests merged in 2023-03, with the labels that each got.

#2389 update ipv6 security-group remote group name
  pkg/controller/security_group.go
  pkg/ovs/ovn-nbctl-legacy.go
Labels: bug, need backport

#2393 remove unused param
  pkg/controller/init.go
  pkg/controller/subnet.go
  pkg/ovs/ovn-nbctl-legacy.go
Labels: refactor

#2410 e2e: fix random conflict in parallel processes
  test/e2e/framework/util.go
Labels: test

#2408 bump go modules
  go.mod
  go.sum
Labels: dependencies, go

#2417 fix scheduled e2e
  .github/workflows/scheduled-e2e.yaml
Labels: ci

#2411 e2e: double parallel test nodes in ci
  .github/workflows/build-x86-image.yaml
  Makefile.e2e
Labels: ci

#2420 Modify the pod scheduling of vpcdns
  yamls/coredns-template.yaml
Labels: enhancement, vpc

#2425 resolve e2e error in v1.12.0
  test/e2e/kube-ovn/subnet/subnet.go
Labels: test

#2391 ci: fix cilium chaining e2e
  .github/workflows/build-x86-image.yaml
  .github/workflows/scheduled-e2e.yaml
  Makefile
  Makefile.e2e
  dist/images/.dockerignore
  dist/images/cilium.sh
  dist/images/install-cilium-cli.sh
  yamls/cilium-chaining.yaml
Labels: ci, need backport

#2426 fix chart install/upgrade e2e
  .github/workflows/build-x86-image.yaml
  .github/workflows/scheduled-e2e.yaml
  Makefile
  kubeovn-helm/templates/kube-ovn-crd.yaml
  kubeovn-helm/templates/ovn-CR.yaml
  kubeovn-helm/templates/post-upgrade.yaml
  yamls/crd.yaml
Labels: test, ci, need backport

#2428 check subnet gateway after wait
  test/e2e/kube-ovn/subnet/subnet.go
Labels: test

#2416 add sumbarier case
  .github/workflows/build-x86-image.yaml
  .github/workflows/scheduled-e2e.yaml
  Makefile
  Makefile.e2e
  yamls/kind.yaml.j2
  yamls/subopeRules.yaml
Labels: test, ci, need backport

#2433 fix ovn-speaker router bug
  pkg/speaker/subnet.go
Labels: bug, need backport

#1978 Perf/libovsdb
  Makefile
  go.mod
  hack/mockgen.sh
  mocks/doc.go
  mocks/pkg/ovs/interface.go
  pkg/controller/config.go
  pkg/controller/controller.go
  pkg/controller/external-gw.go
  pkg/controller/gc.go
  pkg/controller/ovn-ic.go
  pkg/controller/ovn-ic_test.go
  pkg/controller/pod.go
  pkg/controller/security_group.go
  pkg/controller/security_group_test.go
  pkg/controller/vpc.go
  pkg/ovs/interface.go
  pkg/ovs/ovn-nb-acl.go
  pkg/ovs/ovn-nb-acl_test.go
  pkg/ovs/ovn-nb-address_set.go
  pkg/ovs/ovn-nb-address_set_test.go
  pkg/ovs/ovn-nb-dhcp_options.go
  pkg/ovs/ovn-nb-dhcp_options_test.go
  pkg/ovs/ovn-nb-gateway_chassis.go
  pkg/ovs/ovn-nb-gateway_chassis_test.go
  pkg/ovs/ovn-nb-load_balancer.go
  pkg/ovs/ovn-nb-load_balancer_test.go
  pkg/ovs/ovn-nb-logical_router.go
  pkg/ovs/ovn-nb-logical_router_policy.go
  pkg/ovs/ovn-nb-logical_router_policy_test.go
  pkg/ovs/ovn-nb-logical_router_port.go
  pkg/ovs/ovn-nb-logical_router_port_test.go
  pkg/ovs/ovn-nb-logical_router_route.go
  pkg/ovs/ovn-nb-logical_router_route_test.go
  pkg/ovs/ovn-nb-logical_router_test.go
  pkg/ovs/ovn-nb-logical_switch.go
  pkg/ovs/ovn-nb-logical_switch_port.go
  pkg/ovs/ovn-nb-logical_switch_port_test.go
  pkg/ovs/ovn-nb-logical_switch_test.go
  pkg/ovs/ovn-nb-nat.go
  pkg/ovs/ovn-nb-nat_test.go
  pkg/ovs/ovn-nb-port_group.go
  pkg/ovs/ovn-nb-port_group_test.go
  pkg/ovs/ovn-nb-suite_test.go
  pkg/ovs/ovn-nb.go
  pkg/ovs/ovn-nb_global.go
  pkg/ovs/ovn-nb_global_test.go
  pkg/ovs/ovn-nb_test.go
  pkg/ovs/ovn-nbctl-legacy.go
  pkg/ovs/ovn-nbctl-legacy_test.go
  pkg/ovs/ovn.go
  pkg/ovs/util.go
  pkg/ovs/util_test.go
  pkg/ovsdb/client/client.go
  pkg/util/const.go
Labels: performance

#2445 do not set subnet's vlan empty on error
  pkg/controller/subnet.go
Labels: bug, need backport

#2456 ci: fix ovn-ic installation
  Makefile
Labels: ci, need backport

#2472 fix ips CR not found due to etcd error
  pkg/controller/pod.go
Labels: bug, need backport

#2476 Add jitter support to netem qos parameters
  dist/images/Dockerfile.base
  dist/images/Dockerfile.base-dpdk
  docs/qos.md
  pkg/daemon/controller.go
  pkg/daemon/controller_linux.go
  pkg/daemon/controller_windows.go
  pkg/daemon/handler.go
  pkg/daemon/ovs_linux.go
  pkg/daemon/ovs_windows.go
  pkg/ovs/ovs-vsctl_linux.go
  pkg/ovs/ovs-vsctl_windows.go
  pkg/util/const.go
  test/e2e/kube-ovn/qos/qos.go
Labels: feature

#2481 add node to addNodeQueue if required annotations are missing
  pkg/controller/node.go
Labels: bug, need backport

#2482 remove unused subnet status fields
  pkg/apis/kubeovn/v1/types.go
Labels: need backport

#2483 fix ovs qos e2e for versions prior to v1.12
  test/e2e/kube-ovn/qos/qos.go
Labels: test

#2469 fix scheduled submariner e2e
  .github/workflows/build-x86-image.yaml
  .github/workflows/scheduled-e2e.yaml
  Makefile
Labels: ci

#2487 ensure address label is correct before deleting it
  pkg/daemon/ovs_linux.go
Labels: bug, need backport

#2498 ci: fix go cache
  .github/workflows/build-arm64-image.yaml
  .github/workflows/build-kube-ovn-debug.yaml
  .github/workflows/build-kube-ovn-test.yaml
  .github/workflows/build-windows.yaml
  .github/workflows/build-x86-image.yaml
  .github/workflows/codeql-analysis.yml
  .github/workflows/lint.yaml
  .github/workflows/scheduled-e2e.yaml
Labels: ci

#2477 replace lr,ls,lrp function call with ovnClient
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  pkg/controller/external-gw.go
  pkg/controller/gc.go
  pkg/controller/gc_test.go
  pkg/controller/init.go
  pkg/controller/inspection.go
  pkg/controller/node.go
  pkg/controller/ovn-ic.go
  pkg/controller/ovn-ic_test.go
  pkg/controller/ovn_eip.go
  pkg/controller/pod.go
  pkg/controller/security_group.go
  pkg/controller/security_group_test.go
  pkg/controller/subnet.go
  pkg/controller/subnet_test.go
  pkg/controller/vlan.go
  pkg/controller/vpc.go
  pkg/ovs/ovn-nbctl-legacy.go
  pkg/ovs/ovn.go
  pkg/util/net.go
  pkg/util/net_test.go
  pkg/util/slice_test.go
  pkg/util/validator_test.go
Labels: performance

#2502 add support of user-defined image name for vpc-dns
  pkg/controller/vpc_dns.go
Labels: vpc

#2504 add kubevirt multus nic lsp before gc process
  pkg/controller/gc.go
Labels: bug, need backport

#2514 bump k8s to v1.26.3
  go.mod
  go.sum
Labels: dependencies, go

#2492 optimize e2e framework
  test/e2e/framework/daemonset.go
  test/e2e/framework/deployment.go
  test/e2e/framework/event.go
  test/e2e/framework/kube-ovn.go
  test/e2e/framework/network-policy.go
  test/e2e/framework/pod.go
  test/e2e/framework/service.go
  test/e2e/framework/statefulset.go
  test/e2e/framework/subnet.go
  test/e2e/framework/wait.go
  test/e2e/kube-ovn/network-policy/network-policy.go
  test/e2e/kube-ovn/node/node.go
  test/e2e/kube-ovn/qos/qos.go
  test/e2e/kube-ovn/service/service.go
  test/e2e/kube-ovn/subnet/subnet.go
  test/e2e/kube-ovn/underlay/underlay.go
  test/e2e/kubevirt/e2e_test.go
  test/e2e/lb-svc/e2e_test.go
  test/e2e/ovn-ic/e2e_test.go
  test/e2e/security/e2e_test.go
  test/e2e/webhook/pod/pod.go
Labels: test

#2508 when restart deployment kube-ovn-controller the kubectl ko log loss
  test/e2e/framework/deployment.go
  test/e2e/kube-ovn/underlay/underlay.go
Labels: test

#2513 fix lsp gc after upgrade
  mocks/pkg/ovs/interface.go
  pkg/controller/gc.go
  pkg/controller/init.go
  pkg/ovs/interface.go
  pkg/ovs/ovn-nb-logical_switch.go
  pkg/ovs/ovn-nb-logical_switch_port.go
Labels: bug

#2519 fix submariner e2e
  .github/workflows/build-x86-image.yaml
  .github/workflows/scheduled-e2e.yaml
  .gitignore
  Makefile
  Makefile.e2e
  yamls/subopeRules.yaml
Labels: ci

#2525 add vip to webhook e2e
  test/e2e/framework/vip.go
  test/e2e/webhook/e2e_test.go
  test/e2e/webhook/vip/vip.go
Labels: test

#2516 underlay: fix link name exchange
  dist/images/start-ovs.sh
  pkg/daemon/controller.go
  pkg/daemon/init.go
  pkg/daemon/init_linux.go
  pkg/daemon/ovs.go
  pkg/daemon/ovs_linux.go
Labels: bug, need backport

#2521 feat: support nic-hotplug to a running pod.
  pkg/controller/pod.go
  pkg/ipam/subnet.go
Labels: feature

#2539 underlay: delete altname after renaming the link
  go.mod
  go.sum
  pkg/daemon/init_linux.go
  pkg/daemon/ovs.go
Labels: bug, need backport

#2544 fix lsp deletion failure when external-ids:ls is empty
  pkg/ovs/ovn-nb-logical_switch.go
  pkg/ovs/ovn-nb-logical_switch_port.go
Labels: bug

#2545 controller: fix apiserver connection timeout on startup
  pkg/controller/config.go
  pkg/daemon/config.go
  pkg/util/k8s.go
Labels: bug, need backport

#2546 underlay: fix network manager operation
  dist/images/install.sh
  kubeovn-helm/templates/ovncni-ds.yaml
  pkg/daemon/init_linux.go
  pkg/daemon/ovs_linux.go
  yamls/kube-ovn.yaml
Labels: bug, need backport

#2549 do not set device unmanaged if NetworkManager is not running
  go.mod
  go.sum
  pkg/daemon/init_linux.go
Labels: bug, need backport

#2556 fix go mod list
  go.mod
  go.sum
Labels: bug, need backport

#2559 fix CRD indent in install.sh
  dist/images/install.sh
  kubeovn-helm/templates/kube-ovn-crd.yaml
Labels: bug

#2548 fix lrp deletion after upgrade
  pkg/ovs/ovn-nb-logical_router.go
  pkg/ovs/ovn-nb-logical_router_port.go
  pkg/ovs/ovn-nb-logical_switch.go
Labels: bug

#2564 fix ovn-bridge-mappings deletion
  pkg/daemon/init.go
  pkg/daemon/ovs.go
Labels: bug, need backport

#2566 fix: mem leak in ipam
  pkg/ipam/subnet.go
Labels: bug

#2531 Fix kubectl ko log loss when restart deployment or ds
  dist/images/install.sh
  dist/images/kubectl-ko
  kubeovn-helm/templates/monitor-deploy.yaml
  pkg/ovnmonitor/config.go
  test/e2e/framework/deployment.go
  test/e2e/kube-ovn/underlay/underlay.go
  yamls/kube-ovn-dual-stack.yaml
  yamls/kube-ovn-ipv6.yaml
  yamls/kube-ovn.yaml
Labels: test

#2575 kubectl ko change solution to collect logs to path kubectl-ko-log
  .github/workflows/build-x86-image.yaml
  Makefile.e2e
  dist/images/kubectl-ko
  test/e2e/kube-ovn/kubectl-ko/kubectl-ko.go
Labels: diagnose, test

#2585 fix: invalid memory address
  pkg/controller/vpc_nat.go
Labels: bug, need backport

#2581 ci: bump kind image to v1.26.3
  yamls/kind.yaml.j2
Labels: ci, need backport
