Repository kubeovn/kube-ovn, pull requests merged in 2023-11, with the labels that each got.

#3349 fix pod access svc ip failed
  go.mod
  pkg/ovs/ovn-nb-acl.go
  pkg/ovs/ovn-nb-acl_test.go
Labels: bug, network policy

#3366 kube-ovn-controller: fix memory growth caused by unused workqueue
  pkg/controller/controller.go
  pkg/controller/pod_iptables_eip.go
  pkg/controller/pod_iptables_fip.go
Labels: bug, need backport

#3371 kube-ovn-dpdk building need its dpdk base img
  .github/workflows/build-x86-image.yaml
Labels: need backport

#3385 fix: externalID map should not include external_ids
  pkg/controller/security_group.go
Labels: bug, need backport

#3376 add kube-ovn-controller nodeAffinity prefer not on ic gateway
  charts/templates/controller-deploy.yaml
  dist/images/install.sh
  yamls/kube-ovn-dual-stack.yaml
  yamls/kube-ovn-ipv6.yaml
  yamls/kube-ovn.yaml
Labels: need backport

#3392 fix dualStack network checkgw raise panic
  pkg/daemon/ovs_linux.go
  pkg/daemon/ovs_windows.go
Labels: bug, need backport

#3367 subnet support config mtu
  charts/templates/kube-ovn-crd.yaml
  dist/images/install.sh
  pkg/apis/kubeovn/v1/types.go
  pkg/controller/subnet.go
  pkg/daemon/handler.go
  test/e2e/kube-ovn/subnet/subnet.go
  yamls/crd.yaml
Labels: feature, need backport

#3404 ci: free disk space
  .github/workflows/build-x86-image.yaml
Labels: ci

#3406 ci: free disk space for all x86 jobs
  .github/workflows/build-x86-image.yaml
Labels: ci

#3348 support ovn ic ecmp
  Makefile
  dist/images/start-ic-db.sh
  mocks/pkg/ovs/interface.go
  pkg/controller/node.go
  pkg/controller/ovn_ic.go
  pkg/controller/subnet.go
  pkg/controller/vpc.go
  pkg/ovs/interface.go
  pkg/ovs/ovn-nb-logical_router_policy.go
  pkg/ovs/ovn-nb-logical_router_policy_test.go
  pkg/ovs/ovn-nb-logical_router_route.go
  pkg/ovs/ovn-nb-logical_switch_port.go
  pkg/util/const.go
  test/e2e/ovn-ic/e2e_test.go
  yamls/kind.yaml.j2
Labels: feature, need backport

#3405 ci: fix dpdk jobs
  .github/workflows/build-x86-image.yaml
  .gitignore
  Makefile
  dist/images/Dockerfile.base
  dist/images/Dockerfile.dpdk
Labels: ci

#3409 fix kube-ovn-monitor probe
  charts/templates/monitor-deploy.yaml
  dist/images/install.sh
Labels: need backport

#3413 base: fix ovn-northd/ovn-controller not creating pidfile in arm64
  dist/images/Dockerfile.base
Labels: bug, need backport

#3420 chart: move CRD into directory crds
  charts/crds/crd.yaml
Labels: chart

#3422 fix: lsp dhcp options set failed when subnet dhcp option is enabled
  pkg/ovs/ovn-nb-dhcp_options.go
Labels: bug, need backport

#3415 ci: fix scheduled base image build workflow
  .github/workflows/build-kube-ovn-base-dpdk.yaml
  .github/workflows/build-kube-ovn-base.yaml
Labels: ci

#3340 base: fix ovn build failure
  .github/workflows/build-windows.yaml
  dist/images/Dockerfile.base
Labels: need backport

#3426 base: fix dpdk build failure
  dist/images/Dockerfile.base-dpdk
Labels: need backport

#3427 bump k8s to v1.26.11
  .trivyignore
  dist/images/Dockerfile.base
  go.mod
  go.sum
Labels: dependencies, go

#3430 ci: fix missing environment variables
  .github/workflows/build-x86-image.yaml
Labels: ci, need backport

#3425 bump k8s to v1.27.8
  .trivyignore
  dist/images/Dockerfile.base
  go.mod
  go.sum
Labels: dependencies, go

#3432 fix: multus network status not find dpdk interface name
  pkg/daemon/handler.go
Labels: bug, need backport

#3443 ci: fix deepflow installation
  .github/workflows/build-x86-image.yaml
  .github/workflows/scheduled-e2e.yaml
  Makefile
  yamls/kind.yaml.j2
Labels: ci

#3444 ci: support specifying branch
  .github/workflows/build-kube-ovn-base-dpdk.yaml
  .github/workflows/build-kube-ovn-base.yaml
Labels: ci

#3428 base: fix missing CFLAGS -fPIC for arm64
  dist/images/Dockerfile.base
  dist/images/Dockerfile.base-dpdk
Labels: need backport

#3449 ci: fix scheduled workflow runs of building base images
  .github/workflows/build-kube-ovn-base-dpdk.yaml
  .github/workflows/build-kube-ovn-base.yaml
Labels: ci

#3455 ipam: fix duplicate allocation after cidr expansion
  pkg/ipam/ipam.go
Labels: bug, need backport

#3456 ovs-healthcheck: ignore error when log file does not exist
  dist/images/ovs-healthcheck.sh
Labels: bug, need backport

#3457 kube-ovn-cni: fix pinger result when timeout is reached
  pkg/daemon/ovs.go
Labels: bug, need backport
