Repository kubeovn/kube-ovn, pull requests merged in 2023-04, with the labels that each got.

#2592 underlay: get address/route before setting nm managed to no
  pkg/daemon/init_linux.go
Labels: bug, need backport

#2594 base: fix CVE-2022-3294
  dist/images/Dockerfile.base
Labels: security, need backport

#2598 replace lb function call with ovnClient
  mocks/pkg/ovs/interface.go
  pkg/controller/controller_test.go
  pkg/controller/endpoint.go
  pkg/controller/gc.go
  pkg/controller/init.go
  pkg/controller/ovn_dnat.go
  pkg/controller/service.go
  pkg/controller/service_test.go
  pkg/controller/subnet.go
  pkg/ovs/interface.go
  pkg/ovs/ovn-nb-logical_router.go
  pkg/ovs/ovn-nb-logical_router_test.go
  pkg/ovs/ovn-nb-suite_test.go
  pkg/ovs/ovn-nbctl-legacy.go
Labels: performance

#2597 unittest: fix length assertion
  test/unittest/util/net.go
Labels: test, need backport

#2601 cut invalid OVN_NB_DAEMON to make log more readable
  dist/images/start-controller.sh
Labels: need backport

#2603 bump go modules
  go.mod
  go.sum
Labels: dependencies, go

#2604 ci: fix multus installation
  Makefile
Labels: ci, need backport

#2608 replace port_group function call with ovnClient
  pkg/controller/gc.go
  pkg/controller/network_policy.go
  pkg/controller/node.go
  pkg/controller/pod.go
  pkg/controller/security_group.go
  pkg/controller/subnet.go
  pkg/ovs/ovn-nbctl-legacy.go
Labels: performance

#2620 ovs: fix dpif-netlink ofpbuf memory leak
  dist/images/Dockerfile.base
Labels: bug, need backport

#2622 ci: fix multus installation
  .github/workflows/build-x86-image.yaml
  .github/workflows/scheduled-e2e.yaml
  Makefile
Labels: ci, need backport

#2627 libovsdb: use monitor_cond as the monitor method
  pkg/ovs/ovn-nb-suite_test.go
  pkg/ovsdb/client/client.go
Labels: bug, need backport

#2628 ci: deploy multus in thick-plugin mode
  Makefile
Labels: ci, need backport

#2624 fix IPAM allocation caused by incorrect pod annotations patch
  pkg/controller/pod.go
Labels: bug

#2625 libovsdb: fix race condition in OVN LB operations
  dist/images/Dockerfile.base
  mocks/pkg/ovs/interface.go
  pkg/controller/endpoint.go
  pkg/controller/gc.go
  pkg/controller/ovn_dnat.go
  pkg/controller/service.go
  pkg/ovs/interface.go
  pkg/ovs/ovn-nb-load_balancer.go
  pkg/ovs/ovn-nb-load_balancer_test.go
  pkg/ovs/ovn-nb-logical_router.go
  pkg/ovs/ovn-nb-suite_test.go
Labels: bug

#2638 broadcast free arp when pod is setup
  pkg/daemon/ovs_linux.go
  pkg/util/arp.go
Labels: bug, need backport

#2647 Resolve SetLoadBalancerAffinityTimeout not being effective
  pkg/ovs/ovn-nb-load_balancer.go
  pkg/ovs/ovn-nb-load_balancer_test.go
  pkg/ovs/ovn-nb-suite_test.go
Labels: bug

#2652 fix network policy issues
  Makefile.e2e
  mocks/pkg/ovs/interface.go
  pkg/controller/controller.go
  pkg/controller/network_policy.go
  pkg/controller/node.go
  pkg/controller/pod.go
  pkg/controller/security_group.go
  pkg/controller/subnet.go
  pkg/ovs/interface.go
  pkg/ovs/ovn-nb-port_group.go
  pkg/ovs/ovn-nb-port_group_test.go
Labels: bug, network policy

#2657 fix LSP existence check
  pkg/controller/subnet.go
Labels: bug

#2651 when cidr, gw or exclude_ips change , update subnet ipam
  pkg/ipam/ip.go
  pkg/ipam/ipam.go
Labels: bug

#2639 add nat gw e2e
  .github/workflows/build-x86-image.yaml
  .github/workflows/scheduled-e2e.yaml
  Makefile
  Makefile.e2e
  dist/images/install.sh
  pkg/controller/ovn_eip.go
  pkg/controller/subnet.go
  pkg/controller/vlan.go
  pkg/controller/vpc.go
  pkg/controller/vpc_lb.go
  pkg/controller/vpc_nat_gw_eip.go
  test/e2e/framework/framework.go
  test/e2e/framework/iptables-dnat.go
  test/e2e/framework/iptables-eip.go
  test/e2e/framework/iptables-fip.go
  test/e2e/framework/iptables-snat.go
  test/e2e/framework/ovn-dnat.go
  test/e2e/framework/ovn-eip.go
  test/e2e/framework/ovn-fip.go
  test/e2e/framework/ovn-snat.go
  test/e2e/framework/service.go
  test/e2e/framework/subnet.go
  test/e2e/framework/vip.go
  test/e2e/framework/vpc-nat-gw.go
  test/e2e/framework/vpc.go
  test/e2e/iptables-vpc-nat-gw/e2e_test.go
  test/e2e/kube-ovn/ipam/ipam.go
  test/e2e/kube-ovn/network-policy/network-policy.go
  test/e2e/kube-ovn/node/node.go
  test/e2e/kube-ovn/pod/pod.go
  test/e2e/kube-ovn/subnet/subnet.go
  test/e2e/kube-ovn/underlay/underlay.go
  test/e2e/lb-svc/e2e_test.go
  test/e2e/ovn-vpc-nat-gw/e2e_test.go
  test/e2e/webhook/pod/pod.go
  test/e2e/webhook/subnet/subnet.go
  test/e2e/webhook/vip/vip.go
  yamls/crd.yaml
  yamls/vpc-nat-gw-attachment.yaml
Labels: test, ci

#2658 fix pg set port fail when lsp is already deleted
  pkg/controller/node.go
Labels: bug, need backport

#2676 fix kubectl ko using ovn-central pod that not in a good status
  dist/images/kubectl-ko
Labels: bug, need backport

#2678 adapt ippool annotation
  pkg/controller/pod.go
  test/e2e/kube-ovn/ipam/ipam.go
Labels: bug, test

#2683 add tcp mem collector
  dist/images/kubectl-ko
Labels: enhancement

#2687 netpol: fix enqueueing network policy after LSP creation
  pkg/controller/pod.go
Labels: bug, network policy

#2690 ovn-controller: do not send GARP on localnet for Kube-OVN ports
  dist/images/Dockerfile.base
  pkg/daemon/ovs_linux.go
Labels: bug, need backport

#2692 ci: fix scheduled vpc nat gateway e2e
  .github/workflows/build-x86-image.yaml
  .github/workflows/scheduled-e2e.yaml
  Makefile
Labels: ci

#2698 fix: iptables nat gw e2e not clean sts eth0 net1 ip
  test/e2e/framework/ip.go
  test/e2e/iptables-vpc-nat-gw/e2e_test.go
Labels: test

#2697 kubectl-ko: add support for tracing nodes
  dist/images/kubectl-ko
  test/e2e/framework/framework.go
  test/e2e/kube-ovn/kubectl-ko/kubectl-ko.go
Labels: feature

#2711 fix recover db failed using method on the official document
  dist/images/start-db.sh
Labels: bug

#2715 base: remove patch for fixing ofpbuf memory leak
  dist/images/Dockerfile.base
Labels: need backport

#2728 fix ovn lb gc
  pkg/controller/endpoint.go
  pkg/controller/gc.go
  pkg/controller/network_policy.go
  pkg/util/k8s.go
Labels: bug, performance
