Repository kubeovn/kube-ovn, pull requests merged in 2023-08, with the labels that each got.

#3100 distinguish nat ip for central subnet with ecmp and active-standby
  pkg/daemon/gateway.go
Labels: bug, need backport

#3103 get all chassis once
  pkg/controller/init.go
  pkg/ovs/ovn-sbctl.go
Labels: performance

#3101 ovn: delete the db file if the node with new empty db file cannot join cluster for more than 120s
  dist/images/start-db.sh
Labels: need backport

#3108 Fix relevant annotations are not deleted in hotnoplug nic process
  pkg/controller/pod.go
Labels: bug

#3117 controller: fix vpc update
  pkg/controller/subnet.go
  pkg/controller/vpc.go
  pkg/ovs/ovn-nb-logical_router_route.go
  pkg/pinger/ovn.go
Labels: bug

#3116 some fixes in e2e
  pkg/controller/subnet.go
  test/e2e/framework/daemonset.go
  test/e2e/framework/deployment.go
  test/e2e/framework/endpoints.go
  test/e2e/framework/event.go
  test/e2e/framework/network-policy.go
  test/e2e/framework/pod.go
  test/e2e/framework/service.go
  test/e2e/framework/statefulset.go
  test/e2e/framework/switch-lb-rule.go
  test/e2e/kube-ovn/subnet/subnet.go
  test/e2e/kube-ovn/underlay/underlay.go
Labels: test

#3112 ovn: fix corrupted database file on start
  dist/images/Dockerfile.base
  dist/images/start-db.sh
Labels: need backport

#3118 add e2e test for ovn db recover
  .github/workflows/build-x86-image.yaml
  .github/workflows/scheduled-e2e.yaml
  Makefile.e2e
  test/e2e/framework/deployment.go
  test/e2e/framework/exec_utils.go
  test/e2e/framework/framework.go
  test/e2e/ha/ha_test.go
  test/e2e/iptables-vpc-nat-gw/e2e_test.go
  test/e2e/security/e2e_test.go
Labels: test, ci, need backport

#3125 fix ci
  .github/workflows/build-kube-ovn-base.yaml
  .github/workflows/scheduled-e2e.yaml
Labels: ci

#3127 ci: fix version comparison
  .github/workflows/build-kube-ovn-base.yaml
Labels: ci

#3137 bump go version to 1.21
  go.mod
  go.sum
Labels: go

#3131 ovn: do not send direct traffic between lports to conntrack
  dist/images/Dockerfile.base
  mocks/pkg/ovs/interface.go
  pkg/controller/init.go
  pkg/ovs/interface.go
Labels: bug, need backport, network policy

#3141 base: remove ovn patch for skipping ct
  .github/workflows/build-x86-image.yaml
  .github/workflows/scheduled-e2e.yaml
  Makefile.e2e
  dist/images/Dockerfile.base
Labels: bug, need backport, network policy

#3140 base: remove ovn patch for skipping ct
  .github/workflows/build-x86-image.yaml
  dist/images/Dockerfile.base
  pkg/controller/init.go
Labels: bug, network policy

#3147 underlay: fix NetworkManager operation
  go.mod
  go.sum
  pkg/daemon/nm_linux.go
  pkg/daemon/ovs_linux.go
Labels: bug, need backport

#3162 ci/test: bump various versions
  .github/workflows/build-windows.yaml
  .github/workflows/build-x86-image.yaml
  .github/workflows/scheduled-e2e.yaml
  Makefile
  pkg/ovs/ovn-nb-acl.go
  pkg/ovs/ovn-nb-load_balancer.go
  pkg/ovs/ovn-nb-logical_router.go
  pkg/ovs/ovn-nb-logical_switch.go
  pkg/ovs/ovn-sb-chassis.go
  pkg/util/net.go
Labels: test, ci

#3168 fix chart archive
  .github/workflows/build-arm64-image.yaml
  .github/workflows/build-dpdk-image.yaml
  .github/workflows/build-kube-ovn-base-dpdk.yaml
  .github/workflows/build-kube-ovn-base.yaml
  .github/workflows/build-kube-ovn-debug.yaml
  .github/workflows/build-kube-ovn-test.yaml
  .github/workflows/build-windows.yaml
  .github/workflows/build-x86-image.yaml
  .github/workflows/changelog.yaml
  .github/workflows/code-review.yaml
  .github/workflows/codeql-analysis.yml
  .github/workflows/lint.yaml
  .github/workflows/publish.yaml
  .github/workflows/scheduled-e2e.yaml
  kube-ovn-0.1.0.tgz
Labels: bug
