Repository kubeovn/kube-ovn, pull requests merged in 2023-07, with the labels that each got.

#3002 chart: fix readOnly in volumes
  charts/templates/ovsovn-ds.yaml
Labels: chart

#3004 fix subnet finalizer
  pkg/controller/subnet.go
Labels: bug, need backport

#3003 subnet: fix nat outgoing policy rule
  .github/workflows/build-x86-image.yaml
  Makefile.e2e
  pkg/controller/subnet.go
  pkg/daemon/gateway.go
  pkg/daemon/gateway_linux.go
  pkg/util/strings.go
  test/e2e/kube-ovn/subnet/subnet.go
Labels: bug, test

#3007 fix vlan subnet use logical gw can not access outside cluster node
  pkg/daemon/controller_linux.go
Labels: bug, need backport

#3015 ci: fix go cache key
  .github/workflows/build-x86-image.yaml
  .github/workflows/scheduled-e2e.yaml
Labels: ci

#3011 kube-ovn-controller: fix workqueue metrics
  cmd/controller/controller.go
  go.mod
  pkg/controller/ovn_dnat.go
  pkg/controller/ovn_fip.go
  pkg/controller/ovn_snat.go
Labels: bug, need backport

#3006 cleanup.sh: wait for provier-networks to be deleted before deleting kube-ovn-cni
  .github/workflows/build-x86-image.yaml
  dist/images/cleanup.sh
Labels: bug, ci

#3001 ovn: fix cluster connections when SSL is enabled
  dist/images/start-db.sh
Labels: bug

#3018 replace ovn legacy client with libovsdb
  cmd/controller/controller.go
  cmd/controller_health_check/controller_health_check.go
  dist/images/Dockerfile.base
  dist/images/start-controller.sh
  dist/images/start-webhook.sh
  mocks/pkg/ovs/interface.go
  pkg/controller/controller.go
  pkg/controller/external-gw.go
  pkg/controller/gc.go
  pkg/controller/ovn_fip.go
  pkg/controller/ovn_snat.go
  pkg/controller/pod.go
  pkg/controller/subnet.go
  pkg/controller/vpc.go
  pkg/ovs/interface.go
  pkg/ovs/ovn-nb-dhcp_options.go
  pkg/ovs/ovn-nb-dhcp_options_test.go
  pkg/ovs/ovn-nb-nat.go
  pkg/ovs/ovn-nb-nat_test.go
  pkg/ovs/ovn-nbctl-legacy.go
  pkg/ovs/ovn-sbctl.go
  pkg/ovs/ovn.go
Labels: performance

#3028 uninstall.sh: fix ipset name
  dist/images/uninstall.sh
Labels: bug, need backport

#3031 static ip in exclude-ips can be allocated normally when subnet's avai…
  pkg/controller/pod.go
Labels: bug, need backport

#3034 ci: pin go version to 1.20.5
  .github/workflows/build-arm64-image.yaml
  .github/workflows/build-kube-ovn-test.yaml
  .github/workflows/build-windows.yaml
  .github/workflows/build-x86-image.yaml
  .github/workflows/codeql-analysis.yml
  .github/workflows/lint.yaml
  .github/workflows/scheduled-e2e.yaml
Labels: ci, need backport

#3046 fix vpc lb init
  pkg/controller/vpc.go
Labels: bug, need backport

#3047 cni: reduce memory usage
  .github/workflows/build-windows.yaml
  Makefile
  cmd/cmdmain.go
  cmd/cni/cni.go
  cmd/cni/netconf.go
  cmd/cni/netconf_windows.go
  cmd/windows/cni/main_windows.go
  dist/images/Dockerfile
Labels: performance

#3048 controller: skip VIP gc if LB not found
  pkg/controller/gc.go
Labels: bug, need backport

#3054 ipam: fix ippool with single dual-stack address
  .github/workflows/build-x86-image.yaml
  .github/workflows/scheduled-e2e.yaml
  pkg/controller/pod.go
  test/e2e/kube-ovn/ipam/ipam.go
Labels: bug, need backport

#3056 add srl connectivity test
  pkg/controller/endpoint.go
  pkg/controller/service.go
  pkg/ipam/ipam.go
  test/e2e/kube-ovn/switch_lb_rule/switch_lb_rule.go
Labels: test

#3062 ci: fix multus installation
  .github/workflows/build-x86-image.yaml
  .gitignore
  Makefile
  test/e2e/iptables-vpc-nat-gw/e2e_test.go
Labels: ci, need backport

#3055 e2e: do not import pkg/daemon
  .github/workflows/scheduled-e2e.yaml
  pkg/daemon/gateway_linux.go
  pkg/util/const.go
  test/e2e/framework/image.go
  test/e2e/kube-ovn/ipam/ipam.go
  test/e2e/kube-ovn/pod/vpc_pod_probe.go
Labels: test

#3063 bump k8s to v1.27.4
  dist/images/Dockerfile.base
  go.mod
  go.sum
Labels: dependencies, go

#3066 iptables: add --random-fully to SNAT rules
  pkg/daemon/gateway_linux.go
Labels: need backport

#3073 bump github.com/docker/docker to v24.0.5
  .github/workflows/build-arm64-image.yaml
  .github/workflows/build-windows.yaml
  .github/workflows/build-x86-image.yaml
  .github/workflows/scheduled-e2e.yaml
  go.mod
  go.sum
Labels: ci, need backport, dependencies, go

#3071 e2e: fix switch lb rule test
  test/e2e/kube-ovn/switch_lb_rule/switch_lb_rule.go
Labels: test

#3072 ovn client: fix sb chassis existence check
  pkg/ovs/ovn-sbctl.go
Labels: bug, need backport

#3075 cni-server: fix ovn mappings for vpc nat gateway
  pkg/daemon/gateway_linux.go
  pkg/daemon/gateway_windows.go
Labels: bug, need backport

#3086 fix .status.default when initializing the default vpc
  pkg/controller/controller.go
Labels: bug, need backport

#3094 some fixes in e2e
  test/e2e/framework/util.go
  test/e2e/kube-ovn/network-policy/network-policy.go
  test/e2e/kube-ovn/service/service.go
  test/e2e/kube-ovn/subnet/subnet.go
  test/e2e/kube-ovn/underlay/underlay.go
  test/e2e/ovn-vpc-nat-gw/e2e_test.go
Labels: test

#3088 ipam: return error for invalid ip range
  pkg/ipam/ip_range_list.go
  test/e2e/framework/util.go
Labels: bug, test
