Repository kubeovn/kube-ovn, pull requests merged in 2023-05, with the labels that each got.

#2746 Using full repo name to avoid short-name error in podman
  charts/values.yaml
  dist/images/install.sh
Labels: bug, need backport

#2648 replace acl/address_set function call with ovnClient
  mocks/pkg/ovs/interface.go
  pkg/controller/init.go
  pkg/controller/network_policy.go
  pkg/controller/node.go
  pkg/controller/security_group.go
  pkg/controller/subnet.go
  pkg/ovs/interface.go
  pkg/ovs/ovn-nb-acl.go
  pkg/ovs/ovn-nb-acl_test.go
  pkg/ovs/ovn-nb-address_set.go
  pkg/ovs/ovn-nb-suite_test.go
  pkg/ovs/ovn-nb.go
  pkg/ovs/ovn-nb_test.go
  pkg/ovs/ovn-nbctl-legacy.go
  pkg/ovs/util.go
Labels: performance, network policy

#2756 When Subnet spec.vpc is updated, the status in VPC should also be updated
  pkg/controller/subnet.go
  pkg/controller/vpc.go
Labels: bug, vpc

#2757 kubectl-ko: fix pod tracing in underlay
  dist/images/kubectl-ko
Labels: bug

#2762 ci: run kube-ovn e2e for underlay
  .github/workflows/build-x86-image.yaml
Labels: ci, need backport

#2759 cni-server: wait ovs-vswitchd to be running
  dist/images/start-cniserver.sh
Labels: bug, need backport

#2769 fix ip statistics in subnet status
  pkg/controller/pod.go
Labels: bug, need backport, subnet

#2778 fix static route recreation after kube-ovn-controller restarts
  pkg/controller/vpc.go
Labels: bug

#2781 add key lock for more resources
  pkg/controller/controller.go
  pkg/controller/endpoint.go
  pkg/controller/namespace.go
  pkg/controller/node.go
  pkg/controller/service.go
  pkg/controller/subnet.go
  pkg/controller/vlan.go
  pkg/controller/vpc.go
Labels: bug, network policy

#2799 add available check for northd enpoint
  pkg/ovn_leader_checker/ovn.go
Labels: need backport

#2834 fix MTU when subnet is using logical gateway
  pkg/daemon/handler.go
Labels: bug, need backport

#2842 fix underlay access to node through ovn0 when u2o enable
  pkg/controller/subnet.go
  test/e2e/kube-ovn/underlay/underlay.go
Labels: bug, need backport

#2839 ci: detect ovs/ovn memory leak
  .github/workflows/build-x86-image.yaml
  Makefile
  dist/images/install.sh
  dist/images/start-db.sh
  dist/images/start-ovs.sh
Labels: ci

#2836 kubectl-ko: fix trace when u2oInterconnection is enabled
  dist/images/kubectl-ko
Labels: bug, need backport

#2831 U2o support custom vpc
  charts/templates/kube-ovn-crd.yaml
  dist/images/install.sh
  pkg/apis/kubeovn/v1/types.go
  pkg/controller/subnet.go
  test/e2e/framework/vpc.go
  test/e2e/iptables-vpc-nat-gw/e2e_test.go
  test/e2e/kube-ovn/underlay/underlay.go
  test/e2e/ovn-vpc-nat-gw/e2e_test.go
  yamls/crd.yaml
Labels: feature

#2856 some fixes in CI/e2e
  .github/workflows/build-x86-image.yaml
  .github/workflows/scheduled-e2e.yaml
  test/e2e/framework/pod.go
  test/e2e/framework/service.go
  test/e2e/kube-ovn/kubectl-ko/kubectl-ko.go
  test/e2e/kube-ovn/node/node.go
  test/e2e/kube-ovn/service/service.go
  test/e2e/kube-ovn/subnet/subnet.go
  test/e2e/kube-ovn/underlay/underlay.go
Labels: test, ci

#2841 add e2e test for slr
  test/e2e/framework/endpoints.go
  test/e2e/framework/switch-lb-rule.go
  test/e2e/kube-ovn/e2e_test.go
  test/e2e/kube-ovn/switch_lb_rule/switch_lb_rule.go
  yamls/crd.yaml
Labels: test

#2861 bump k8s to v1.27.2
  dist/images/Dockerfile.base
  go.mod
  go.sum
  yamls/kind.yaml.j2
Labels: dependencies, go
