Repository kubeovn/kube-ovn, pull requests merged in 2023-10, with the labels that each got.

#3275 fix ovn build failure
  .github/workflows/build-windows.yaml
  dist/images/Dockerfile.base
Labels: need backport

#3276 update directory name in charts readme
  charts/README.md
Labels: need backport

#3281 ovs: load kernel module ip_tables only when it exists
  dist/images/start-ovs.sh
Labels: need backport

#3279 bump go modules
  go.mod
  go.sum
Labels: dependencies, go

#3282 bgp: support announce policy
  .gitignore
  Makefile
  pkg/speaker/config.go
  pkg/speaker/subnet.go
  yamls/clab-bgp.yaml.j2
  yamls/speaker.yaml
Labels: feature

#3283 bgp: support multiple peer addresses
  .gitignore
  Makefile
  pkg/speaker/config.go
  pkg/speaker/subnet.go
  yamls/clab-bgp-ha.yaml.j2
Labels: feature

#3285 webhook: use dedicated port for health probe
  Makefile
  cmd/webhook/server.go
  yamls/webhook.yaml
Labels: need backport, webhook

#3284 webhook: fix ip validation when pod is annotated with an ippool name
  pkg/webhook/static_ip.go
Labels: bug, need backport, webhook

#3302 Don't enqueue VPC update when DeletionTimestamp is zero
  pkg/controller/vpc.go
Labels: bug, need backport

#3218 sync subnet to vpc while switching between custom VPC and default VPC
  pkg/controller/subnet.go
  pkg/controller/vpc.go
  pkg/util/const.go
Labels: bug

#3323 fix golang lint error
  pkg/daemon/ovs_linux.go
Labels: need backport

#3322 kube-ovn-controller: fix ovn ic log directory not mounted to hostpath
  charts/templates/controller-deploy.yaml
  dist/images/install.sh
  yamls/kube-ovn-dual-stack.yaml
  yamls/kube-ovn-ipv6.yaml
  yamls/kube-ovn.yaml
  yamls/ovn-dpdk.yaml
  yamls/ovn-ha.yaml
Labels: bug, need backport

#3328 profile: fix fd leak
  cmd/cmdmain.go
Labels: bug, need backport

#3324 bump k8s to v1.28.3
  go.mod
  go.sum
Labels: dependencies, go

#3339 ci: bump various versions
  .github/workflows/build-windows.yaml
  .github/workflows/build-x86-image.yaml
  .github/workflows/scheduled-e2e.yaml
  Makefile
Labels: ci

#3300 Add Layer 2 forwarding for subnet ports again
  pkg/controller/pod.go
Labels: bug, need backport

#3350 fix access svc ip failed, when acl is on
  pkg/ovs/ovn-nb-acl.go
  pkg/ovs/ovn-nb-acl_test.go
Labels: bug, network policy
