Repository kubeovn/kube-ovn, pull requests merged in 2023-12, with the labels that each got.

#3504 cni-server: set sysctl variable net.ipv4.ip_no_pmtu_disc to 1 by default
  dist/images/start-cniserver.sh
Labels: need backport

#3208 netpol: do not create unused address set for services
  pkg/controller/network_policy.go
Labels: network policy

#3525 fix chassis gc
  pkg/controller/gc.go
  pkg/controller/node.go
Labels: bug, need backport

#3532 ovn-central: check raft inconsistency from nb/sb logs
  dist/images/ovn-healthcheck.sh
Labels: need backport

#3505 bump go modules
  dist/images/Dockerfile.base
  dist/images/Dockerfile.base-dpdk
  go.mod
  go.sum
Labels: dependencies, go, network policy

#3514 fix: apply changes to the latest version
  pkg/controller/init.go
  pkg/controller/subnet.go
  pkg/controller/vip.go
  pkg/controller/vlan.go
  pkg/controller/vpc.go
  test/e2e/ovn-vpc-nat-gw/e2e_test.go
Labels: bug, need backport

#3561 Makefile: fix kwok installation
  .gitignore
  Makefile
  yamls/kwok-kustomization.yaml.j2
  yamls/kwok-stage.yaml
  yamls/kwok.yaml
Labels: need backport
