Repository kubeovn/kube-ovn, pull requests merged in 2023-02, with the labels that each got.

#2279 fix access from node to overlay pods when network policy ingress exists
  pkg/controller/node.go
  pkg/ovs/ovn-nbctl-legacy.go
  test/e2e/framework/network-policy.go
  test/e2e/kube-ovn/e2e_test.go
  test/e2e/kube-ovn/network-policy/network-policy.go
Labels: bug

#2273 add named port support
  .github/workflows/build-x86-image.yaml
  pkg/controller/controller.go
  pkg/controller/network_policy.go
  pkg/controller/pod.go
  pkg/ovs/ovn-nbctl-legacy.go
  pkg/util/named_port.go
Labels: feature

#2289 fix ct.new flag not work
  dist/images/kubectl-ko
  dist/images/update/1.7-1.8.3.sh
  dist/images/update/1.8.0-1.8.3.sh
  dist/images/update/1.8.3-1.9.1.sh
  docs/kubectl-plugin.md
Labels: bug, need backport

#2286 ovn northd: fix connection inactivity probe
  dist/images/start-db.sh
Labels: bug, need backport

#2295 fix gosec ci installation
  .github/workflows/build-x86-image.yaml
Labels: ci, need backport

#2296 update trivy deprecated arg and the ignored CVE.
  .trivyignore
  Makefile
Labels: security

#2302 fix image tag in helm chart
  Makefile
  kubeovn-helm/values.yaml
Labels: bug

#2300 fix u2o code err
  pkg/daemon/ovs_linux.go
Labels: bug, need backport

#2305 fix kube-ovn-controller crash on startup
  pkg/controller/network_policy.go
Labels: bug, need backport

#2299 ovndb: use Local_Config to configure listen addresses
  Makefile
  dist/images/Dockerfile.base
  dist/images/start-db.sh
  test/e2e/framework/framework.go
  test/e2e/security/e2e_test.go
Labels: feature

#2319 e2e: do not test versions prior to 1.11 for ovn-ic update
  test/e2e/ovn-ic/e2e_test.go
Labels: test

#2307 feat: configure routes via pod annotation
  pkg/daemon/handler.go
  pkg/daemon/ovs_linux.go
  pkg/util/const.go
  test/e2e/framework/deployment.go
  test/e2e/framework/service.go
  test/e2e/framework/statefulset.go
  test/e2e/framework/util.go
  test/e2e/kube-ovn/e2e_test.go
  test/e2e/kube-ovn/ipam/ipam.go
  test/e2e/kube-ovn/node/node.go
  test/e2e/kube-ovn/pod/pod.go
Labels: feature

#2311 feat: support default service session stickiness timeout
  Makefile.e2e
  pkg/controller/endpoint.go
  pkg/controller/init.go
  pkg/controller/vpc.go
  pkg/ovs/ovn-nbctl-legacy.go
  pkg/util/const.go
  test/e2e/framework/image.go
Labels: feature

#2327 perf: use empty struct to reduce memory usage
  pkg/controller/pod.go
  pkg/util/named_port.go
Labels: performance

#2325 fix k8s networking dns e2e
  .github/workflows/build-x86-image.yaml
  Makefile.e2e
Labels: test

#2328 e2e: skip case of switching session affinity
  Makefile.e2e
Labels: test

#2323 fix getting service backends in dual-stack clusters
  pkg/controller/endpoint.go
Labels: bug, need backport

#2331 OVN LB: add support for SCTP protocol
  Makefile.e2e
  dist/images/Dockerfile.base
  dist/images/install.sh
  pkg/apis/kubeovn/v1/types.go
  pkg/controller/config.go
  pkg/controller/endpoint.go
  pkg/controller/gc.go
  pkg/controller/init.go
  pkg/controller/network_policy.go
  pkg/controller/service.go
  pkg/controller/service_lb.go
  pkg/controller/subnet.go
  pkg/controller/vpc.go
  pkg/ovs/ovn-nbctl-legacy.go
  pkg/util/k8s.go
  test/e2e/kube-ovn/node/node.go
  yamls/crd.yaml
Labels: feature

#2335 Add neighbor-address format check for kube-ovn-speaker
  pkg/speaker/config.go
Labels: bug, need backport

#2337 enqueue endpoint when handling service add event
  Makefile.e2e
  pkg/controller/service.go
Labels: bug, test, need backport

#2340 fix encap ip when the tunnel interface has multiple addresses
  pkg/daemon/config.go
  pkg/daemon/config_linux.go
  pkg/daemon/config_windows.go
Labels: bug, need backport

#2312 update go version to v1.20
  .github/workflows/build-arm64-image.yaml
  .github/workflows/build-kube-ovn-debug.yaml
  .github/workflows/build-windows.yaml
  .github/workflows/build-x86-image.yaml
  .github/workflows/lint.yaml
  .github/workflows/scheduled-e2e.yaml
  docs/development.md
  go.mod
  go.sum
  pkg/util/arp.go
  test/e2e/framework/util.go
  test/unittest/ipam/ipam.go
Labels: need backport, dependencies, go

#2338 simplify github actions workflows
  .github/workflows/build-arm64-image.yaml
  .github/workflows/build-dpdk-image.yaml
  .github/workflows/build-kube-ovn-debug.yaml
  .github/workflows/build-windows.yaml
  .github/workflows/build-x86-image.yaml
  .github/workflows/lint.yaml
  .github/workflows/scheduled-e2e.yaml
Labels: ci

#2360 Do not wait pod deletion one by one to accelerate install
  dist/images/install.sh
Labels: ci

#2359 use existing node switch cidr instead of the configured one
  pkg/controller/init.go
Labels: bug, need backport

#2363 fix github actions workflows
  .github/workflows/build-windows.yaml
  .github/workflows/build-x86-image.yaml
  .github/workflows/codeql-analysis.yml
  Makefile
Labels: ci

#2369 ci: fix default branch test
  .github/workflows/build-windows.yaml
  .github/workflows/build-x86-image.yaml
Labels: ci

#2345 Add gateway monitor metrics and event
  pkg/controller/subnet.go
  pkg/daemon/controller.go
  pkg/daemon/controller_linux.go
  pkg/daemon/controller_windows.go
  pkg/daemon/gateway.go
  pkg/daemon/gateway_linux.go
  pkg/daemon/metrics.go
  pkg/util/const.go
  pkg/util/iptables.go
  test/e2e/framework/event.go
  test/e2e/framework/kind/kind.go
  test/e2e/kube-ovn/subnet/subnet.go
  test/e2e/kube-ovn/underlay/underlay.go
Labels: feature

#2376 accelerate cleanup
  dist/images/cleanup.sh
Labels: ci

#2375 e2e: run specs in parallel
  .github/workflows/build-x86-image.yaml
  Makefile.e2e
  test/e2e/framework/framework.go
  test/e2e/k8s-network/e2e_test.go
  test/e2e/kube-ovn/e2e_test.go
  test/e2e/kube-ovn/underlay/underlay.go
  test/e2e/lb-svc/e2e_test.go
  test/e2e/ovn-eip/e2e_test.go
  test/e2e/ovn-ic/e2e_test.go
  test/e2e/security/e2e_test.go
Labels: test, need backport

#2378 ci: fix path filter for windows build
  .github/workflows/build-windows.yaml
Labels: ci, need backport

#2367 fix service dual stack add/del cluster ips not change ovn nb
  pkg/controller/service.go
  test/e2e/framework/service.go
  test/e2e/kube-ovn/e2e_test.go
  test/e2e/kube-ovn/service/service.go
Labels: bug, need backport

#2381 ci: make path filter more accurate
  .github/workflows/build-windows.yaml
  hack/go-list.sh
Labels: ci, need backport

#2379 ci: skip netpol e2e automatically for push events
  .github/workflows/build-x86-image.yaml
Labels: ci, need backport

#2390 ci: fix ref name check
  .github/workflows/build-arm64-image.yaml
Labels: ci, need backport

#2395 Fix routeregexp ipv6
  pkg/ovs/ovn-nbctl-legacy.go
  pkg/ovs/ovn-nbctl-legacy_test.go
Labels: bug, need backport
