Repository kubeovn/kube-ovn, pull requests merged in 2023-06, with the labels that each got.

#2851 underlay: do not delete patch ports created by ovn-controller
  .github/workflows/build-x86-image.yaml
  pkg/daemon/init.go
Labels: bug, need backport

#2882 kube-ovn-controller: fix subnet update
  pkg/controller/init.go
  pkg/controller/subnet.go
Labels: bug

#2896 refactor IPAM
  pkg/controller/subnet.go
  pkg/ipam/ip.go
  pkg/ipam/ip_range.go
  pkg/ipam/ip_range_list.go
  pkg/ipam/ipam.go
  pkg/ipam/subnet.go
  test/unittest/ipam/ipam.go
Labels: performance

#2912 For eip created without spec.V4ip this field is always empty
  pkg/controller/vpc_nat_gw_eip.go
Labels: bug, need backport, vpc

#2919 cni-server: clear iptables mark before doing masquerade
  pkg/daemon/gateway_linux.go
Labels: bug, need backport

#2909 e2e: fix waiting deployment to be restarted
  go.mod
  go.sum
  test/e2e/framework/deployment.go
  test/e2e/framework/pod.go
  test/e2e/kube-ovn/subnet/subnet.go
  test/e2e/kube-ovn/underlay/underlay.go
  test/e2e/ovn-vpc-nat-gw/e2e_test.go
Labels: test

#2928 fix race condition in gateway check logs
  go.mod
  go.sum
  pkg/controller/node.go
  pkg/daemon/gateway_linux.go
  pkg/daemon/ovs.go
  pkg/daemon/ovs_linux.go
  pkg/daemon/ovs_windows.go
  pkg/pinger/ping.go
Labels: bug

#2927 modify lb-svc dnat port error
  pkg/controller/service_lb.go
Labels: bug, need backport

#2931 e2e: fix u2o case
  test/e2e/kube-ovn/underlay/underlay.go
Labels: test

#2941 controller: fix DHCP MTU when the default network mode is underlay
  pkg/controller/subnet.go
  pkg/util/const.go
Labels: bug, need backport

#2944 Revert "nm not managed only in the change provide nic name case (#2754)"
  pkg/daemon/ovs_linux.go
Labels: bug, need backport

#2924 e2e: add qos policy test cases
  pkg/controller/qos_policy.go
  test/e2e/framework/docker/network.go
  test/e2e/framework/exec_utils.go
  test/e2e/framework/iptables-eip.go
  test/e2e/framework/qos-policy.go
  test/e2e/framework/vpc-nat-gw.go
  test/e2e/iptables-vpc-nat-gw/e2e_test.go
Labels: test, ci

#2950 ci: fix build-base strategy
  .github/workflows/build-kube-ovn-base.yaml
Labels: ci

#2949 underlay: sync NetworkManager IP config to OVS bridge
  pkg/daemon/controller.go
  pkg/daemon/controller_linux.go
  pkg/daemon/init.go
  pkg/daemon/init_linux.go
  pkg/daemon/init_windows.go
  pkg/daemon/nm_linux.go
  pkg/daemon/ovs_linux.go
  pkg/daemon/ovs_windows.go
Labels: feature

#2961 uninstall.sh: flush and delete iptables chain OVN-MASQUERADE
  dist/images/uninstall.sh
Labels: bug, need backport

#2963 cni-server: reconcile ovn0 routes periodically
  pkg/daemon/controller.go
  pkg/daemon/controller_linux.go
  pkg/daemon/controller_windows.go
Labels: bug, need backport

#2973 bump k8s version to v1.26.6
  .github/workflows/build-x86-image.yaml
  .trivyignore
  dist/images/Dockerfile.base
  go.mod
  go.sum
  yamls/kind.yaml.j2
Labels: security

#2958 IPAM: add support for ippool
  .github/workflows/build-x86-image.yaml
  charts/templates/kube-ovn-crd.yaml
  charts/templates/ovn-CR.yaml
  dist/images/cleanup.sh
  dist/images/install.sh
  pkg/apis/kubeovn/v1/condition.go
  pkg/apis/kubeovn/v1/register.go
  pkg/apis/kubeovn/v1/status.go
  pkg/apis/kubeovn/v1/types.go
  pkg/apis/kubeovn/v1/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/typed/kubeovn/v1/fake/fake_ippool.go
  pkg/client/clientset/versioned/typed/kubeovn/v1/fake/fake_kubeovn_client.go
  pkg/client/clientset/versioned/typed/kubeovn/v1/generated_expansion.go
  pkg/client/clientset/versioned/typed/kubeovn/v1/ippool.go
  pkg/client/clientset/versioned/typed/kubeovn/v1/kubeovn_client.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/kubeovn/v1/interface.go
  pkg/client/informers/externalversions/kubeovn/v1/ippool.go
  pkg/client/listers/kubeovn/v1/expansion_generated.go
  pkg/client/listers/kubeovn/v1/ippool.go
  pkg/controller/controller.go
  pkg/controller/init.go
  pkg/controller/ippool.go
  pkg/controller/namespace.go
  pkg/controller/node.go
  pkg/controller/pod.go
  pkg/controller/subnet.go
  pkg/controller/vip.go
  pkg/controller/vpc_nat_gw_eip.go
  pkg/ipam/ip.go
  pkg/ipam/ip_range.go
  pkg/ipam/ip_range_list.go
  pkg/ipam/ipam.go
  pkg/ipam/ippool.go
  pkg/ipam/subnet.go
  pkg/util/validator.go
  test/e2e/kube-ovn/subnet/subnet.go
  test/e2e/kube-ovn/underlay/underlay.go
  test/unittest/ipam/ipam.go
  test/unittest/ipam_bench/ipam_test.go
  yamls/crd.yaml
  yamls/sa.yaml
Labels: feature

#2979 IPAM: fix subnet mutex not released when static IP is out of range
  pkg/ipam/subnet.go
Labels: bug

#2977 add unittest for IPAM
  charts/templates/kube-ovn-crd.yaml
  dist/images/install.sh
  pkg/apis/kubeovn/v1/types.go
  pkg/apis/kubeovn/v1/zz_generated.deepcopy.go
  pkg/controller/ippool.go
  pkg/internal/big_int.go
  pkg/ipam/ip.go
  pkg/ipam/ip_range.go
  pkg/ipam/ip_range_list.go
  pkg/ipam/ipam.go
  pkg/ipam/subnet.go
  test/unittest/ipam/ip.go
  test/unittest/ipam/ip_range.go
  test/unittest/ipam/ip_range_list.go
  test/unittest/ipam/ipam.go
  yamls/crd.yaml
Labels: test

#2986 underlay: does not set a device managed to no if it has VLAN managed by NM
  pkg/daemon/nm_linux.go
Labels: bug, need backport

#2988 underlay: fix NetworkManager syncer for virtual interfaces
  pkg/daemon/nm_linux.go
Labels: bug, need backport

#2981 add e2e for new ippool feature
  pkg/internal/big_int.go
  test/e2e/framework/deployment.go
  test/e2e/framework/ippool.go
  test/e2e/framework/namespace.go
  test/e2e/framework/pod.go
  test/e2e/framework/util.go
  test/e2e/kube-ovn/ipam/ipam.go
  test/e2e/kube-ovn/qos/qos.go
Labels: test

#2989 fix deleting old sb chassis for a re-added node
  pkg/controller/node.go
  pkg/ovs/ovn-sbctl.go
Labels: bug, need backport

#2987 choose subnet by pod's annotation in networkpolicy
  pkg/controller/network_policy.go
  pkg/controller/subnet.go
  pkg/ovs/ovn-nb-acl.go
  pkg/ovs/ovn-nb-acl_test.go
Labels: network policy
