Repository kubeovn/kube-ovn, pull requests merged in 2023-09, with the labels that each got.

#3173 Add tolerations to pinger Daemonset
  charts/templates/pinger-ds.yaml
Labels: chart

#3176 subnet: fix deleting lr policy on node deletion
  pkg/controller/node.go
Labels: bug, need backport

#3178 subnet: fix deleting lr policy on node deletion
  pkg/controller/node.go
Labels: bug, need backport

#3164 chart: fix ovs-ovn upgrade
  .github/workflows/scheduled-e2e.yaml
  Makefile
  charts/README.md
  charts/templates/upgrade-ovs-ovn.yaml
  charts/values.yaml
  dist/images/start-ovs.sh
  dist/images/upgrade-ovs.sh
  yamls/ovn.yaml
Labels: bug, need backport, chart

#3166 fix ovn build
  .github/workflows/build-windows.yaml
  dist/images/Dockerfile.base
Labels: need backport

#3160 ci: wait for terminating ovs-ovn pod to disappear
  .github/workflows/build-x86-image.yaml
Labels: ci, need backport

#3184 underlay: fix ip/route tranfer when the nic is managed by NetworkManager
  go.mod
  go.sum
  pkg/daemon/init.go
  pkg/daemon/nm_linux.go
  pkg/daemon/ovs.go
  pkg/daemon/ovs_linux.go
  pkg/daemon/ovs_windows.go
Labels: bug, need backport

#3197 netpol: fix duplicate default drop acl
  pkg/controller/network_policy.go
  pkg/ovs/ovn-nb-acl.go
  pkg/ovs/ovn-nb-acl_test.go
Labels: bug, need backport, network policy

#3195 fix: add static route to wrong table of ovn
  pkg/ovs/ovn-nb-logical_router_route.go
Labels: bug, need backport

#3240 fix goproxy Denial of Service vulnerability
  go.mod
  go.sum
Labels: security, need backport

#3243 fix: for existing nic, no need to set the port type to internal
  pkg/daemon/ovs.go
  pkg/daemon/ovs_linux.go
  pkg/daemon/ovs_windows.go
Labels: bug, need backport, mirror

#3259 pinger: increase packet send interval
  pkg/pinger/ping.go
Labels: need backport

#3159 bump k8s to v1.28.2
  .github/workflows/build-x86-image.yaml
  .github/workflows/scheduled-e2e.yaml
  Makefile
  Makefile.e2e
  cmd/webhook/server.go
  go.mod
  go.sum
  hack/update-codegen-docker.sh
  pkg/controller/gc.go
  pkg/controller/pod.go
  pkg/daemon/controller_linux.go
  test/e2e/framework/image.go
  test/e2e/ha/ha_test.go
  test/e2e/iptables-vpc-nat-gw/e2e_test.go
  test/e2e/k8s-network/e2e_test.go
  test/e2e/kube-ovn/e2e_test.go
  test/e2e/kube-ovn/kubectl-ko/kubectl-ko.go
  test/e2e/kube-ovn/node/node.go
  test/e2e/kube-ovn/pod/vpc_pod_probe.go
  test/e2e/kube-ovn/service/service.go
  test/e2e/kube-ovn/switch_lb_rule/switch_lb_rule.go
  test/e2e/kubevirt/e2e_test.go
  test/e2e/lb-svc/e2e_test.go
  test/e2e/ovn-ic/e2e_test.go
  test/e2e/ovn-vpc-nat-gw/e2e_test.go
  test/e2e/security/e2e_test.go
  test/e2e/webhook/e2e_test.go
  yamls/kind.yaml.j2
Labels: dependencies, go, network policy
