Repository kubeovn/kube-ovn, pull requests merged in 2024-04, with the labels that each got.

#3831 fix ic e2e
  test/e2e/ovn-ic/e2e_test.go
Labels: test

#3887 chart: fix ovs-ovn update strategy
  charts/kube-ovn/Chart.yaml
  charts/kube-ovn/templates/_helpers.tpl
Labels: need backport, chart

#3890 Fix init sg
  mocks/pkg/ovs/interface.go
  pkg/controller/controller.go
  pkg/controller/security_group.go
  pkg/controller/subnet.go
  pkg/ovs/interface.go
  pkg/ovs/ovn-nb-acl.go
Labels: security

#3904 support specifying routes when providing IPAM for other CNI plugins
  .github/workflows/build-x86-image.yaml
  Makefile.e2e
  cmd/cni/cni.go
  pkg/daemon/handler.go
  pkg/daemon/ovs_linux.go
  pkg/daemon/ovs_windows.go
  pkg/netconf/ipam_conf.go
  pkg/netconf/netconf.go
  pkg/netconf/netconf_windows.go
  pkg/request/cniserver.go
  test/e2e/framework/network-attachment-definition.go
  test/e2e/framework/pod.go
  test/e2e/multus/e2e_test.go
Labels: feature

#3905 bump go toolchain to go1.22.2
  .github/workflows/build-x86-image.yaml
  .github/workflows/scheduled-e2e.yaml
  Makefile
  go.mod
  go.sum
Labels: dependencies, go

#3914 refactor kubevirt vm e2e
  .github/workflows/build-x86-image.yaml
  .github/workflows/scheduled-e2e.yaml
  Makefile
  go.mod
  go.sum
  pkg/controller/pod.go
  pkg/daemon/controller_linux.go
  pkg/daemon/controller_windows.go
  pkg/daemon/handler.go
  pkg/util/const.go
  test/e2e/framework/framework.go
  test/e2e/framework/network-attachment-definition.go
  test/e2e/framework/virtual-machine.go
  test/e2e/iptables-vpc-nat-gw/e2e_test.go
  test/e2e/kubevirt/e2e_test.go
  test/e2e/multus/e2e_test.go
Labels: test, need backport

#3863 1.11 distinguish portSecurity with security group
  pkg/controller/pod.go
  pkg/controller/security_group.go
  pkg/controller/service.go
  pkg/ovs/ovn-nbctl-legacy.go
Labels: security

#3927 bump k8s to v1.29.4
  Makefile
  dist/images/Dockerfile.base
  go.mod
  go.sum
Labels: dependencies, go

#3928 ovn: check whether db file is fixed
  dist/images/start-db.sh
Labels: bug, need backport

#3929 cni-server: set sysctl variables only when the env variables are passed in
  dist/images/start-cniserver.sh
Labels: need backport

#3940 drop both IPv4 and IPv6 traffic in networkpolicy drop acl
  mocks/pkg/ovs/interface.go
  pkg/controller/network_policy.go
  pkg/ovs/interface.go
  pkg/ovs/ovn-nb-acl.go
  pkg/ovs/ovn-nb-acl_test.go
Labels: network policy

#3925 check kube ovn podrestarts
  .github/workflows/build-x86-image.yaml
  .github/workflows/scheduled-e2e.yaml
  Makefile
  cmd/daemon/cniserver.go
  dist/images/check-kube-ovn-pod-restarts.sh
  dist/images/kubectl-ko
  pkg/controller/subnet.go
  pkg/daemon/ovs.go
  pkg/daemon/ovs_linux.go
  pkg/daemon/ovs_windows.go
  pkg/ovs/ovn-nb_global.go
  pkg/ovs/ovn.go
  pkg/util/const.go
Labels: ci

#3951 fix nil pointer dereference
  .trivyignore
  pkg/controller/vpc.go
Labels: bug, need backport

#3958 fix index out of range
  pkg/pinger/config.go
Labels: bug, need backport

#3959 add patch permission for cni clusterrole
  charts/kube-ovn/templates/ovn-CR.yaml
  dist/images/install.sh
  yamls/sa.yaml
Labels: bug, need backport
