Repository kubeovn/kube-ovn, pull requests merged in 2024-05, with the labels that each got.

#3975 chart: fix kubeVersion to allow for patterns that match sub versions
  charts/kube-ovn/Chart.yaml
Labels: need backport, chart

#3966 bump k8s to v1.27.13
  Makefile
  cmd/daemon/cniserver.go
  cmd/ovn_ic_controller/ovn_ic_controller.go
  cmd/speaker/speaker.go
  cmd/webhook/server.go
  dist/images/Dockerfile.base
  go.mod
  go.sum
  test/e2e/cyclonus.yaml
  test/e2e/framework/daemonset.go
  test/e2e/framework/docker/container.go
  test/e2e/framework/docker/exec.go
  test/e2e/framework/docker/network.go
  test/e2e/framework/event.go
  test/e2e/framework/expect.go
  test/e2e/framework/framework.go
  test/e2e/framework/image.go
  test/e2e/framework/iproute/iproute.go
  test/e2e/framework/kind/kind.go
  test/e2e/framework/kube-ovn.go
  test/e2e/framework/kubectl.go
  test/e2e/framework/log.go
  test/e2e/framework/pod.go
  test/e2e/framework/provider-network.go
  test/e2e/framework/service.go
  test/e2e/framework/subnet.go
  test/e2e/framework/util.go
  test/e2e/framework/vlan.go
  test/e2e/framework/wait.go
  test/e2e/k8s-network/e2e_test.go
  test/e2e/kube-ovn/e2e_test.go
  test/e2e/kube-ovn/ipam/ipam.go
  test/e2e/kube-ovn/kubectl-ko/kubectl-ko.go
  test/e2e/kube-ovn/node/node.go
  test/e2e/kube-ovn/qos/qos.go
  test/e2e/kube-ovn/subnet/subnet.go
  test/e2e/kube-ovn/underlay/underlay.go
  test/e2e/lb-svc/e2e_test.go
  test/e2e/ovn-ic/e2e_test.go
Labels: dependencies, go

#3989 bump go to 1.22.3
  .github/workflows/build-arm64-image.yaml
  .github/workflows/build-windows.yaml
  .github/workflows/build-x86-image.yaml
  .github/workflows/scheduled-e2e.yaml
  .trivyignore
  go.mod
Labels: need backport, go

#3994 e2e: fix skip cases for k8s network conformance tests
  Makefile.e2e
Labels: test

#3992 fix node gc
  pkg/controller/gc.go
  pkg/controller/init.go
  pkg/controller/ip.go
  pkg/controller/node.go
  pkg/controller/subnet.go
  pkg/daemon/gateway.go
  pkg/util/const.go
  pkg/util/ovn.go
  test/e2e/kube-ovn/node/node.go
Labels: bug, need backport

#4005 fix controller-runtime logger not set
  pkg/controller/init.go
Labels: need backport

#4007 fix: close file
  pkg/ovn_leader_checker/ovn.go
Labels: need backport

#4011 fix lsp not updating addresses
  pkg/ovs/ovn-nb-logical_switch_port.go
Labels: bug, need backport

#4004 fix: Resolved the hidden issue with zombie processes
  dist/images/start-controller.sh
  dist/images/start-ic-controller.sh
  dist/images/start-ovn-monitor.sh
  dist/images/start-webhook.sh
Labels: bug, need backport

#4016 fix lr policy route for u2o not deleted correctly
  pkg/controller/subnet.go
Labels: bug

#4013 fix: u2o dual stack uses the corresponding svc ip
  pkg/controller/subnet.go
Labels: bug, need backport

#4018 base: set entrypoint to dumb-init
  dist/images/Dockerfile.base
  dist/images/start-cniserver.sh
  dist/images/start-controller.sh
  dist/images/start-db.sh
  dist/images/start-ic-controller.sh
  dist/images/start-ic-db.sh
  dist/images/start-ovn-monitor.sh
  dist/images/start-ovs.sh
  dist/images/start-webhook.sh
Labels: need backport

#4015 fix lsp not updated correctly when logical switch is changed
  pkg/ovs/ovn-nb-logical_switch_port.go
  test/e2e/kube-ovn/pod/pod _routes.go
  test/e2e/kube-ovn/pod/pod_recreation.go
  test/e2e/kube-ovn/underlay/underlay.go
  test/e2e/kubevirt/e2e_test.go
Labels: bug, test, need backport

#4019 ci: bump k8s to v1.30.0
  .github/workflows/build-x86-image.yaml
  .github/workflows/scheduled-e2e.yaml
  yamls/kind.yaml.j2
Labels: ci

#4020 fix container args
  charts/kube-ovn/templates/central-deploy.yaml
  charts/kube-ovn/templates/ic-controller-deploy.yaml
  charts/kube-ovn/templates/monitor-deploy.yaml
  charts/kube-ovn/templates/ovncni-ds.yaml
  charts/kube-ovn/templates/ovsovn-ds.yaml
  charts/kube-ovn/templates/pinger-ds.yaml
  dist/images/install.sh
Labels: need backport

#3995 reconcile iptable to the first position after iptables -t nat -F
  pkg/daemon/gateway_linux.go
  pkg/util/iptables.go
Labels: enhancement

#4021 bump gosec to 2.20.0
  .github/workflows/build-windows.yaml
  .github/workflows/build-x86-image.yaml
  Makefile
  cmd/cmdmain.go
  cmd/daemon/cniserver.go
  pkg/controller/vpc_dns.go
  pkg/daemon/config.go
  pkg/daemon/handler_linux.go
  pkg/daemon/ovs_linux.go
  pkg/ovn_ic_controller/ovn_ic_controller.go
  pkg/ovn_leader_checker/ovn.go
  pkg/ovnmonitor/util.go
  pkg/ovsdb/client/client.go
  pkg/pinger/ovn.go
  pkg/pinger/util.go
  pkg/util/arp.go
Labels: need backport, go

#4030 fix node annotations not updated when initializing the default provid…
  pkg/controller/init.go
Labels: need backport

#4028 bump k8s to 1.30.1
  .trivyignore
  dist/images/Dockerfile.base
  go.mod
  go.sum
Labels: dependencies, go

#4025 do not use exec for start scripts using `trap quit EXIT`
  charts/kube-ovn/templates/central-deploy.yaml
  charts/kube-ovn/templates/ic-controller-deploy.yaml
  charts/kube-ovn/templates/monitor-deploy.yaml
  charts/kube-ovn/templates/ovncni-ds.yaml
  charts/kube-ovn/templates/ovsovn-ds.yaml
  charts/kube-ovn/templates/pinger-ds.yaml
  dist/images/install-ic-server.sh
  dist/images/install.sh
  dist/images/start-cniserver.sh
  dist/images/start-db.sh
  dist/images/start-ic-db.sh
  dist/images/start-ovs.sh
Labels: need backport

#4024 cleanup.sh: remove sa/clusterrole/clusterrolebinding
  dist/images/cleanup.sh
Labels: need backport

#4029 bump k8s to 1.27.14
  .trivyignore
  dist/images/Dockerfile.base
  go.mod
  go.sum
  yamls/kind.yaml.j2
Labels: dependencies, go

#4034 uninstall.sh: delete OVN-POSTROUTING rule in mangle table
  dist/images/uninstall.sh
Labels: need backport

#4047 fix deleting vip on ovn lb
  dist/images/Dockerfile
  dist/images/Dockerfile.base
  pkg/ovs/ovn-nbctl-legacy.go
Labels: bug

#4035 wait for all pods to be deleted before deleting serviceaccount/cluste…
  dist/images/cleanup.sh
Labels: need backport

#4048 fix ipv6 service ip not deleted in ovn lb
  pkg/controller/service.go
  pkg/ovs/ovn-nbctl-legacy.go
Labels: bug

#4054 crd: add subnet name pattern
  charts/kube-ovn/templates/kube-ovn-crd.yaml
  dist/images/install.sh
Labels: enhancement, need backport

#4057 ci: fix scheduled e2e
  .github/workflows/scheduled-e2e.yaml
Labels: ci

#4062 bump ginkgo to v2.18.0
  Makefile.e2e
  go.mod
  go.sum
Labels: ci, dependencies, go

#4061 fix: should update subnet status after change vm subnet
  pkg/controller/pod.go
Labels: bug, need backport

#4065 e2e: skip sctp connectivity tests for versions prior to 1.12
  Makefile.e2e
Labels: ci

#4042 fix node gc
  cmd/controller/controller.go
  cmd/daemon/cniserver.go
  cmd/pinger/pinger.go
  cmd/webhook/server.go
  go.mod
  go.sum
  pkg/controller/controller.go
  pkg/controller/endpoint.go
  pkg/controller/external-gw.go
  pkg/controller/init.go
  pkg/controller/inspection.go
  pkg/controller/namespace.go
  pkg/controller/network_policy.go
  pkg/controller/node.go
  pkg/controller/ovn-ic.go
  pkg/controller/pod.go
  pkg/controller/security_group.go
  pkg/controller/service.go
  pkg/controller/subnet.go
  pkg/controller/vlan.go
  pkg/controller/vpc.go
  pkg/controller/vpc_nat_gateway.go
  pkg/daemon/config.go
  pkg/daemon/controller.go
  pkg/daemon/gateway.go
  pkg/daemon/handler.go
  pkg/daemon/ovs.go
  pkg/daemon/server.go
  pkg/ipam/ipam.go
  pkg/ipam/subnet.go
  pkg/ovs/adapter.go
  pkg/ovs/ovn-nb-logical_router_policy.go
  pkg/ovs/ovn-nbctl-legacy.go
  pkg/ovs/ovn-sbctl.go
  pkg/ovs/ovn.go
  pkg/ovs/ovs-vsctl.go
  pkg/ovsdb/ovnnb/meter_band.go
  pkg/pinger/ovn.go
  pkg/pinger/ping.go
  pkg/speaker/bgpapiutil/capability.go
  pkg/speaker/subnet.go
  pkg/util/arp.go
  pkg/util/net.go
  pkg/util/pod_exec.go
  yamls/kind.yaml.j2
Labels: bug

#4040 fix node gc
  pkg/controller/node.go
  pkg/util/arp.go
  test/unittest/ipam/ipam.go
Labels: bug, need backport

#4043 fix: gateway should not be network address and broadcast address
  pkg/controller/pod.go
  pkg/util/validator.go
  pkg/util/validator_test.go
Labels: enhancement, need backport

#4074 Add support for Yunsilicon NIC
  docs/hw-offload-yunsilicon.md
  pkg/daemon/handler.go
  pkg/daemon/ovs_linux.go
  pkg/ovs/ovs-vsctl.go
  pkg/ovs/ovs-vsctl_linux.go
  pkg/util/const.go
Labels: feature

#4077 fix crypto/rand: argument to Int is <= 0
  pkg/util/net.go
  pkg/util/net_test.go
Labels: bug, need backport

#4069 ci: downgrade node image to v1.29.2
  yamls/kind.yaml.j2
Labels: ci, need backport

#4070 base: avoid unnecessary env variables
  dist/images/Dockerfile.base
  dist/images/Dockerfile.rpm
Labels: need backport

#4079 delete lease on cleanup
  dist/images/cleanup.sh
Labels: need backport

#4080 fix exit on error
  pkg/util/net.go
Labels: need backport

#4058 ovs: get controllerrevision with option --ignore-not-found
  dist/images/cleanup.sh
  dist/images/start-ovs.sh
Labels: need backport

#4075 opt: replace ovn-sbctl with ovsdb-client
  pkg/pinger/ovn.go
Labels: performance, need backport

#4081 ci: print all the previous logs for restarted pods
  .github/workflows/build-x86-image.yaml
  .github/workflows/scheduled-e2e.yaml
  Makefile
  dist/images/check-kube-ovn-pod-restarts.sh
  hack/ci-check-crash.sh
Labels: ci, need backport

#4082 install.sh: wait for all kube-ovn-pinger pods to be ready
  dist/images/install.sh
Labels: need backport

#4095 fix mac conflict
  pkg/util/net.go
Labels: bug, need backport

#4096 install.sh: waiting for deleted kube-ovn-pinger to disapper
  dist/images/install.sh
Labels: need backport

#4100 Makefile: run kubectl-ko script when collecting logs
  .gitignore
  Makefile
Labels: need backport

#4092 add reinit process for lb-svc pod
  pkg/controller/pod.go
  pkg/controller/service_lb.go
Labels: bug, need backport

#4060 add unit test for util
  pkg/util/arp_test.go
  pkg/util/net.go
  pkg/util/net_test.go
  pkg/util/ovn_test.go
  pkg/util/strings_test.go
  pkg/util/subnet_test.go
  pkg/util/validator_test.go
  pkg/util/vpc_nat_gateway_test.go
Labels: test
