Repository kubeovn/kube-ovn, pull requests merged in 2024-08, with the labels that each got.

#4357 fix: load-balancer for dnat cleaned after restarting kube-ovn-controller
  pkg/controller/gc.go
Labels: bug, need backport

#4335 vpc dns: remove unused variable
  pkg/controller/vpc_dns.go
Labels: need backport

#4373 bump go to 1.22.6
  go.mod
  go.sum
  hack/update-codegen-docker.sh
  pkg/apis/kubeovn/v1/zz_generated.deepcopy.go
Labels: need backport, go

#4377 bump multus to v4.1.0
  Makefile
  go.mod
  go.sum
Labels: ci, dependencies, go

#4380 fix controller-runtime logger not set
  cmd/controller/controller.go
  cmd/daemon/cniserver.go
  cmd/ovn_monitor/ovn_monitor.go
  cmd/pinger/pinger.go
  pkg/controller/init.go
Labels: bug, need backport

#4359 replace protocol check in netpol update
  pkg/controller/network_policy.go
Labels: bug, need backport, network policy

#4334 refactor ipsec function
  .github/workflows/build-x86-image.yaml
  Makefile
  Makefile.e2e
  charts/kube-ovn/templates/controller-deploy.yaml
  charts/kube-ovn/templates/ovn-CR.yaml
  charts/kube-ovn/templates/ovncni-ds.yaml
  charts/kube-ovn/values.yaml
  dist/images/cleanup.sh
  dist/images/install.sh
  dist/images/ipsec.sh
  dist/images/uninstall.sh
  mocks/pkg/ovs/interface.go
  pkg/controller/config.go
  pkg/controller/controller.go
  pkg/controller/pki.go
  pkg/controller/signer.go
  pkg/daemon/config.go
  pkg/daemon/controller.go
  pkg/daemon/ipsec.go
  pkg/ovs/interface.go
  pkg/ovs/ovn-nb_global.go
  pkg/util/const.go
  test/e2e/framework/daemonset.go
  test/e2e/ipsec/e2e_test.go
Labels: feature

#4381 fix EOF during TLS handshake caused by health check
  charts/kube-ovn/templates/controller-deploy.yaml
  charts/kube-ovn/templates/monitor-deploy.yaml
  charts/kube-ovn/templates/ovncni-ds.yaml
  cmd/cmdmain.go
  cmd/health_check/health_check.go
  dist/images/Dockerfile
  dist/images/install.sh
  go.mod
  pkg/server/server.go
Labels: need backport

#4384 serve pprof in metrics server if metrics server listens on 0.0.0.0
  cmd/controller/controller.go
  cmd/daemon/cniserver.go
  cmd/ovn_monitor/ovn_monitor.go
  cmd/pinger/pinger.go
  pkg/metrics/server.go
Labels: bug, need backport

#4387 ipsec: fix chart installation failure
  .github/workflows/build-x86-image.yaml
  Makefile
  charts/kube-ovn/templates/_helpers.tpl
  charts/kube-ovn/templates/central-deploy.yaml
  charts/kube-ovn/templates/controller-deploy.yaml
  charts/kube-ovn/templates/ic-controller-deploy.yaml
  charts/kube-ovn/templates/monitor-deploy.yaml
  charts/kube-ovn/templates/ovncni-ds.yaml
  charts/kube-ovn/templates/ovsovn-ds.yaml
  charts/kube-ovn/templates/pinger-ds.yaml
  dist/images/install.sh
  pkg/controller/pki.go
  pkg/controller/security_group.go
  pkg/controller/signer.go
  pkg/daemon/ipsec.go
  test/e2e/ipsec/e2e_test.go
  test/e2e/kube-ovn/underlay/underlay.go
Labels: bug, chart

#4388 ci: fix git diff
  .github/workflows/build-x86-image.yaml
Labels: ci

#4395 cni-server: do not set sysctl variables
  dist/images/start-cniserver.sh
  pkg/daemon/ovs_linux.go
Labels: bug, need backport

#4397 increase health probe timeout
  charts/kube-ovn/templates/controller-deploy.yaml
  charts/kube-ovn/templates/monitor-deploy.yaml
  charts/kube-ovn/templates/ovncni-ds.yaml
  cmd/health_check/health_check.go
  dist/images/install.sh
Labels: need backport

#4407 ci: bump golangci-lint to v1.60.1
  .github/workflows/build-x86-image.yaml
  cmd/controller/controller.go
  cmd/daemon/cniserver.go
  cmd/ovn_ic_controller/ovn_ic_controller.go
  cmd/ovn_monitor/ovn_monitor.go
  cmd/pinger/pinger.go
  cmd/speaker/speaker.go
  cmd/webhook/server.go
  pkg/controller/namespace.go
  pkg/controller/service_lb.go
  pkg/controller/vpc_nat_gateway.go
  pkg/daemon/ovs_linux.go
  pkg/daemon/server.go
  pkg/speaker/config.go
  pkg/util/network_attachment.go
  test/e2e/iptables-vpc-nat-gw/e2e_test.go
Labels: ci

#4410 bump k8s to v1.30.4
  cmd/controller/controller.go
  cmd/daemon/cniserver.go
  cmd/ovn_ic_controller/ovn_ic_controller.go
  cmd/ovn_monitor/ovn_monitor.go
  cmd/pinger/pinger.go
  cmd/speaker/speaker.go
  cmd/webhook/server.go
  dist/images/Dockerfile.base
  go.mod
  go.sum
  pkg/controller/config.go
  pkg/controller/gc.go
  pkg/controller/inspection.go
  pkg/controller/namespace.go
  pkg/controller/node.go
  pkg/controller/provider_network.go
  pkg/controller/service_lb.go
  pkg/controller/vpc_dns.go
  pkg/controller/vpc_nat_gateway.go
  pkg/daemon/config.go
  pkg/daemon/controller.go
  pkg/daemon/ovs.go
  pkg/daemon/ovs_linux.go
  pkg/daemon/ovs_windows.go
  pkg/daemon/server.go
  pkg/ovn_ic_controller/config.go
  pkg/ovn_ic_controller/ovn_ic_controller.go
  pkg/ovn_leader_checker/ovn.go
  pkg/ovs/ovs-vsctl.go
  pkg/ovs/ovs-vsctl_linux.go
  pkg/pinger/config.go
  pkg/pinger/ovn.go
  pkg/pinger/ping.go
  pkg/speaker/config.go
  pkg/util/network_attachment.go
  yamls/kind.yaml.j2
Labels: dependencies, go

#4411 bump kind to v0.24.0
  .github/workflows/build-x86-image.yaml
  Makefile
Labels: ci

#4416 vpc-nat-gateway: do not add routes for underlay subnets
  pkg/controller/vpc_nat_gateway.go
Labels: bug, need backport

#4420 netpol: add allow acl rules for u2o logical gateway
  mocks/pkg/ovs/interface.go
  pkg/controller/network_policy.go
  pkg/controller/subnet.go
  pkg/ovs/interface.go
  pkg/ovs/ovn-nb-acl.go
  pkg/ovs/ovn-nb-acl_test.go
Labels: bug, need backport, network policy

#4428 vpc-nat-gateway: use iptables-legacy for centos 7
  dist/images/vpcnatgateway/Dockerfile
  dist/images/vpcnatgateway/nat-gateway.sh
Labels: bug, need backport

#4433 bump kubevirt to v1.3.1
  Makefile
  go.mod
  go.sum
Labels: ci, dependencies, go

#4434 bump github.com/vishvananda/netlink to v1.2.1
  go.mod
  go.sum
  pkg/daemon/tproxy_linux.go
Labels: dependencies, go

#4444 metrics: do not export information if a subnet is not validated
  pkg/controller/exporter.go
Labels: need backport
