Repository kubeovn/kube-ovn, pull requests merged in 2024-09, with the labels that each got.

#4347 add anp and banp e2e
  .gitignore
  Makefile
  Makefile.e2e
  charts/kube-ovn/templates/controller-deploy.yaml
  charts/kube-ovn/values.yaml
  dist/images/install.sh
  pkg/controller/admin_network_policy.go
  test/anp/anp_test.go
  test/anp/conformance.sh
  test/anp/go.mod
  test/anp/go.sum
Labels: test

#4474 ci: bump golangci-lint to v1.60.3
  .github/workflows/build-x86-image.yaml
  pkg/daemon/ovs_linux.go
  pkg/speaker/utils.go
  pkg/tproxy/tproxy_tcp_linux.go
Labels: ci, go, github_actions, size:S, lgtm

#4473 fix error logging
  pkg/util/net.go
Labels: go, size:S

#4478 fix: kubectl-ko using kube-ovn-cni pod for nsenter
  dist/images/kubectl-ko
Labels: bug, size:S, lgtm

#4466 fix bug: dpdk场景下添加删除ProviderNetwork失败
  pkg/daemon/gateway_linux.go
  pkg/daemon/init.go
  pkg/daemon/ovs_linux.go
Labels: size:L

#4337 ci: bump cilium to v1.16.1
  .github/workflows/build-x86-image.yaml
  Makefile
Labels: ci, size:L, lgtm

#4477 fix: arping reply may duplicate
  dist/images/vpcnatgateway/lb-svc.sh
Labels: bug, need backport, size:XS

#4484 fix 解决部署遇到的不成功问题
  dist/images/install.sh
Labels: bug, size:XS, lgtm

#4482 bump go to 1.22.7
  go.mod
  go.sum
  hack/update-codegen-docker.sh
  test/anp/go.mod
  test/anp/go.sum
Labels: go, size:M, lgtm

#4455 Add ipam ut
  pkg/ipam/ipam.go
  pkg/ipam/ipam_test.go
Labels: lgtm

#4451 Add ipam
  pkg/ipam/subnet_test.go
Labels: lgtm

#4461 ut: add unit test for bfd acl and address_set
  pkg/ovs/ovn-nb-acl_test.go
  pkg/ovs/ovn-nb-address_set_test.go
  pkg/ovs/ovn-nb-bfd_test.go
  pkg/ovs/ovn-nb-suite_test.go
Labels: size:XL

#4460 add gobgp client cmd
  dist/images/Dockerfile.base
Labels: lgtm

#4488 fix: backport ut
  go.mod
  go.sum
  pkg/ovs/ovn-nb-acl.go
Labels: test, go, size:M

#4489 fix: ipam ut name conflicts
  pkg/ipam/ipam_test.go
  pkg/ipam/subnet_test.go
Labels: test, size:S, lgtm

#4487 tproxy: support named port
  pkg/daemon/gateway.go
  pkg/daemon/gateway_linux.go
  pkg/daemon/tproxy_linux.go
  test/e2e/kube-ovn/pod/vpc_pod_probe.go
Labels: feature, test, need backport, go, size:L, lgtm

#4425 fix: support ptp networks with ipv4 /31 netmask and ipv6 /127 netmask
  pkg/ipam/subnet_test.go
  pkg/util/net.go
  pkg/util/net_test.go
  pkg/util/validator.go
  pkg/util/validator_test.go
  test/unittest/util/net.go
Labels: size:L, lgtm

#4472 update Makefile
  .github/workflows/build-x86-image.yaml
  Makefile
  yamls/kind.yaml.j2
Labels: github_actions, size:XL

#4492 fix: go mod
  go.mod
  go.sum
Labels: go, size:S

#4496 bump golangci-lint to v1.61.0
  .github/workflows/build-x86-image.yaml
  pkg/ovn_ic_controller/ovn_ic_controller.go
  pkg/ovs/ovn-nb-logical_switch_port_test.go
  pkg/util/net.go
  pkg/util/net_test.go
Labels: go, github_actions, size:M, lgtm

#4375 add mcast querier ip for multicast
  dist/images/install.sh
  pkg/apis/kubeovn/v1/types.go
  pkg/controller/ip.go
  pkg/controller/subnet.go
  pkg/util/const.go
  test/e2e/kube-ovn/subnet/subnet.go
Labels: feature, size:L, lgtm

#4498 fix: gobgp CVE
  dist/images/Dockerfile.base
Labels: bug, security, size:XS, lgtm

#4490 make: add ut cover
  .gitignore
  Makefile
  pkg/ipam/subnet_test.go
  pkg/util/arp_test.go
Labels: test, size:L, lgtm

#4507 fix: err log
  pkg/util/net.go
Labels: go, size:S, lgtm

#4512 bump k8s to v1.31.1
  dist/images/Dockerfile.base
  go.mod
  go.sum
Labels: dependencies, size:L, lgtm

#4513 bump k8s to v1.30.5
  dist/images/Dockerfile.base
  go.mod
  go.sum
Labels: dependencies, size:M, lgtm

#4511 fix: mac arm64 run netlink ut
  pkg/util/arp_test.go
Labels: test, size:XS, lgtm

#4509 fix: upgrade submodule ginkgo
  test/anp/go.mod
  test/anp/go.sum
Labels: dependencies, size:XS, lgtm

#4508 ut: add unit for dhcp_options logical_switch and ovn-nb_global
  pkg/ovs/ovn-nb-dhcp_options.go
  pkg/ovs/ovn-nb-dhcp_options_test.go
  pkg/ovs/ovn-nb-logical_switch_test.go
  pkg/ovs/ovn-nb-suite_test.go
  pkg/ovs/ovn-nb_global_test.go
Labels: test, go, size:XL, lgtm

#4497 fix mistake to announce ipv4
  pkg/speaker/eip.go
Labels: bug, go, size:XS, lgtm

#4510 add ginkgo ut coverage
  .gitignore
  Makefile
Labels: test, size:XS, lgtm

#4514 Utils net ut
  pkg/util/net.go
  pkg/util/net_test.go
  pkg/util/validator.go
Labels: go, size:L, lgtm

#4521 add pod patch and exec ut
  pkg/util/patch_test.go
  pkg/util/pod_exec_test.go
Labels: test, size:L, lgtm

#4525 add ut
  pkg/util/arp_test.go
  pkg/util/klog_test.go
  pkg/util/link_test.go
Labels: test, size:M, lgtm

#4515 ut:add ut for func DialTCP and DialAPIServer in apk/util/k8s.go
  pkg/controller/config.go
  pkg/daemon/config.go
  pkg/util/k8s.go
  pkg/util/k8s_test.go
Labels: test, go, size:L, lgtm

#4505 fix bugs and enhance unit test coverage for all functions in pkg/util/validator.go
  pkg/util/validator.go
  pkg/util/validator_test.go
Labels: bug, test, go, size:L, lgtm

#4533 check whether subnet exists before deleting vpc
  pkg/controller/vpc.go
Labels: vpc, size:S, lgtm

#4532 bump multus to v4.1.1
  .github/workflows/build-x86-image.yaml
  Makefile
  yamls/clab-bgp-ha.yaml.j2
  yamls/clab-bgp.yaml.j2
Labels: need backport, github_actions, size:M, lgtm

#4536 add ut for ip.go
  pkg/util/ip_test.go
Labels: test, go, size:M, lgtm

#4500 [fix]: delete the NIC regardless of whether the Pod was found or not.
  pkg/daemon/handler.go
  pkg/daemon/ovs_linux.go
  pkg/daemon/ovs_windows.go
  pkg/util/const.go
Labels: bug, go, size:L

#4523 fix speaker metrics
  cmd/speaker/speaker.go
  pkg/speaker/config.go
Labels: go, size:M, lgtm

#4524 base: rebuild go binary deps from source
  .github/workflows/build-kube-ovn-base.yaml
  .github/workflows/build-x86-image.yaml
  Makefile
  dist/images/Dockerfile.base
  dist/images/Dockerfile.base-dpdk
  dist/images/go-deps/download-go-deps.sh
  dist/images/go-deps/rebuild-go-deps.sh
Labels: go, github_actions, size:L, lgtm

#4535 add arp ut
  pkg/controller/init.go
  pkg/controller/node.go
  pkg/util/arp_test.go
Labels: test, size:L, lgtm

#4544 add utils ut
  pkg/util/k8s.go
  pkg/util/k8s_test.go
Labels: test, size:L, lgtm

#4545 fix: ovn0 doesn't have ipv6 local link addresss in kylin OS
  pkg/daemon/ovs_linux.go
Labels: bug, go, size:M, lgtm

#4543 allow user to set vxlan_sys_4789 tx off
  Makefile
  charts/kube-ovn/templates/ovncni-ds.yaml
  charts/kube-ovn/values.yaml
  cmd/daemon/cniserver.go
  cmd/daemon/init.go
  cmd/daemon/init_windows.go
  dist/images/install.sh
  pkg/daemon/config.go
  pkg/daemon/ovs_linux.go
Labels: bug, chart, size:M, lgtm

#4552 fix only ipv6 mode should add ovn0 locallink ipv6 address
  pkg/daemon/ovs_linux.go
Labels: bug, go, size:XS, lgtm

#4553 fix only ipv6 mode should add ovn0 locallink ipv6 address
  pkg/daemon/ovs_linux.go
Labels: bug, go, size:XS

#4550 fix kube-ovn-cni capabilities
  charts/kube-ovn/templates/ovncni-ds.yaml
  dist/images/install.sh
Labels: bug, need backport, size:XS, lgtm

#4547 fix ovn0 add ipv6 local-link address
  pkg/daemon/ovs_linux.go
Labels: bug, go, size:M, lgtm

#4549 ut: ovn sb suite
  pkg/controller/config.go
  pkg/controller/controller.go
  pkg/ovn_ic_controller/config.go
  pkg/ovn_ic_controller/controller.go
  pkg/ovs/ovn-nb-acl_test.go
  pkg/ovs/ovn-nb-address_set_test.go
  pkg/ovs/ovn-nb-bfd_test.go
  pkg/ovs/ovn-nb-dhcp_options_test.go
  pkg/ovs/ovn-nb-gateway_chassis_test.go
  pkg/ovs/ovn-nb-load_balancer_health_check_test.go
  pkg/ovs/ovn-nb-load_balancer_test.go
  pkg/ovs/ovn-nb-logical_router_policy_test.go
  pkg/ovs/ovn-nb-logical_router_port_test.go
  pkg/ovs/ovn-nb-logical_router_route_test.go
  pkg/ovs/ovn-nb-logical_router_test.go
  pkg/ovs/ovn-nb-logical_switch_port_test.go
  pkg/ovs/ovn-nb-logical_switch_test.go
  pkg/ovs/ovn-nb-nat_test.go
  pkg/ovs/ovn-nb-port_group_test.go
  pkg/ovs/ovn-nb-suite_test.go
  pkg/ovs/ovn-nb_global_test.go
  pkg/ovs/ovn-nb_test.go
  pkg/ovs/ovn-sb-chassis_test.go
  pkg/ovs/ovn.go
  pkg/ovs/ovn_test.go
  pkg/util/arp_test.go
Labels: test, size:XXL, lgtm

#4567 add values for OVSDB_CON_TIMEOUT and OVSDB_INACTIVITY_TIMEOUT
  charts/kube-ovn/templates/controller-deploy.yaml
  charts/kube-ovn/values.yaml
  dist/images/install.sh
Labels: chart, size:XS, lgtm

#4562 Fix error log not printed nearby in ovs package
  pkg/ovs/ovn-ic-sbctl.go
  pkg/ovs/ovn-nb-acl.go
  pkg/ovs/ovn-nb-address_set.go
  pkg/ovs/ovn-nb-dhcp_options.go
  pkg/ovs/ovn-nb-gateway_chassis.go
  pkg/ovs/ovn-nb-load_balancer.go
  pkg/ovs/ovn-nb-load_balancer_health_check.go
  pkg/ovs/ovn-nb-logical_router.go
  pkg/ovs/ovn-nb-logical_router_policy.go
  pkg/ovs/ovn-nb-logical_router_port.go
  pkg/ovs/ovn-nb-logical_router_route.go
  pkg/ovs/ovn-nb-logical_router_test.go
  pkg/ovs/ovn-nb-logical_switch.go
  pkg/ovs/ovn-nb-logical_switch_port.go
  pkg/ovs/ovn-nb-logical_switch_test.go
  pkg/ovs/ovn-nb-nat.go
  pkg/ovs/ovn-nb-port_group.go
  pkg/ovs/ovn-nb.go
  pkg/ovs/ovn-sb-chassis.go
  pkg/ovs/ovn.go
  pkg/ovs/ovs-vsctl.go
  pkg/ovs/ovs-vsctl_linux.go
  pkg/ovs/util.go
Labels: bug, go, size:L, lgtm

#4494 Check network mask when init subnet
  pkg/controller/init.go
  pkg/util/net.go
  pkg/util/validator.go
Labels: need backport, go, size:S, lgtm
