Repository kubeovn/kube-ovn, pull requests merged in 2024-06, with the labels that each got.

#4111 fix: IP Add/Sub overflow or underflow
  pkg/ipam/ip.go
  pkg/ipam/ip_test.go
Labels: bug, need backport

#4121 bump go to 1.22.4
  go.mod
  go.sum
Labels: dependencies, go

#4083 bump ovn to v24.03 - part 1
  .github/workflows/build-windows.yaml
  dist/images/Dockerfile.base
  dist/images/Dockerfile.base-dpdk
  pkg/ovsdb/ovnnb/acl.go
  pkg/ovsdb/ovnnb/dns.go
  pkg/ovsdb/ovnnb/logical_router_policy.go
  pkg/ovsdb/ovnnb/logical_router_port.go
  pkg/ovsdb/ovnnb/mirror.go
  pkg/ovsdb/ovnnb/model.go
  pkg/ovsdb/ovnnb/qos.go
  pkg/ovsdb/ovnsb/bfd.go
  pkg/ovsdb/ovnsb/dhcpv6_options.go
  pkg/ovsdb/ovnsb/dns.go
  pkg/ovsdb/ovnsb/fdb.go
  pkg/ovsdb/ovnsb/igmp_group.go
  pkg/ovsdb/ovnsb/load_balancer.go
  pkg/ovsdb/ovnsb/mirror.go
  pkg/ovsdb/ovnsb/model.go
  pkg/ovsdb/ovnsb/service_monitor.go
Labels: network policy

#4129 trivy: ignore unfixed CVEs
  .trivyignore
Labels: need backport

#4126 fix ipam subnet concurrent map iteration and map write
  pkg/controller/exporter.go
  pkg/ipam/ipam.go
  pkg/ipam/subnet.go
Labels: bug, need backport

#4112 Ipam ut
  pkg/ipam/ipam.go
  pkg/ipam/subnet.go
  pkg/ipam/subnet_test.go
Labels: test

#4127 add ovn0 default route
  pkg/daemon/controller_linux.go
  pkg/daemon/controller_windows.go
  pkg/daemon/init.go
  pkg/daemon/ovs_linux.go
  pkg/daemon/ovs_windows.go
  test/e2e/kube-ovn/node/node.go
Labels: bug, need backport

#4140 speaker: add option to set node IP to override pod IP
  pkg/speaker/config.go
  pkg/speaker/subnet.go
  yamls/speaker.yaml
Labels: feature

#4161 ci: fix retrieving docker network subnet/gateway
  Makefile
Labels: need backport

#4164 bump k8s to v1.30.2
  go.mod
  go.sum
Labels: dependencies, go

#4169 e2e: fix retrieving docker network information
  test/e2e/iptables-vpc-nat-gw/e2e_test.go
  test/e2e/kube-ovn/subnet/subnet.go
  test/e2e/kube-ovn/underlay/underlay.go
  test/e2e/lb-svc/e2e_test.go
  test/e2e/ovn-vpc-nat-gw/e2e_test.go
Labels: test

#4168 fix reconcile routes
  pkg/daemon/controller_linux.go
  pkg/daemon/controller_windows.go
  pkg/daemon/gateway_linux.go
  pkg/daemon/ovs_linux.go
  test/e2e/framework/iproute/iproute.go
  test/e2e/kube-ovn/node/node.go
Labels: need backport

#4115 ut add ip range split
  test/unittest/ipam/ip_range_list.go
Labels: test

#4179 ci: push amd64 legacy image only for branches >= v1.13
  .github/workflows/build-kube-ovn-base.yaml
Labels: ci

#4114 fix change vm subnet e2e
  pkg/controller/pod.go
  test/e2e/kubevirt/e2e_test.go
Labels: test

#4160 ci: check pod crashes on installation/e2e failure
  .github/workflows/build-x86-image.yaml
Labels: ci, need backport

#4185 base: bump cni plugins to v1.5.1
  .trivyignore
  dist/images/Dockerfile.base
  dist/images/Dockerfile.base-dpdk
Labels: need backport

#4198 pinger: reset interface_rx_multicast_packets
  pkg/pinger/util.go
Labels: bug, need backport

#4199 fix vm not running after changing the subnet
  pkg/ovs/ovn-nb-logical_switch_port.go
  test/e2e/kubevirt/e2e_test.go
Labels: bug, need backport

#4192 e2e: add ginkgo.GinkgoHelper()
  test/e2e/framework/daemonset.go
  test/e2e/framework/deployment.go
  test/e2e/framework/endpoints.go
  test/e2e/framework/event.go
  test/e2e/framework/exec_utils.go
  test/e2e/framework/expect.go
  test/e2e/framework/framework.go
  test/e2e/framework/ip.go
  test/e2e/framework/ippool.go
  test/e2e/framework/iptables-dnat.go
  test/e2e/framework/iptables-eip.go
  test/e2e/framework/iptables-fip.go
  test/e2e/framework/iptables-snat.go
  test/e2e/framework/iptables/iptables.go
  test/e2e/framework/kube-ovn.go
  test/e2e/framework/namespace.go
  test/e2e/framework/network-attachment-definition.go
  test/e2e/framework/network-policy.go
  test/e2e/framework/ovn-dnat.go
  test/e2e/framework/ovn-eip.go
  test/e2e/framework/ovn-fip.go
  test/e2e/framework/ovn-snat.go
  test/e2e/framework/pod.go
  test/e2e/framework/provider-network.go
  test/e2e/framework/qos-policy.go
  test/e2e/framework/security-group.go
  test/e2e/framework/service.go
  test/e2e/framework/statefulset.go
  test/e2e/framework/subnet.go
  test/e2e/framework/switch-lb-rule.go
  test/e2e/framework/util.go
  test/e2e/framework/vip.go
  test/e2e/framework/virtual-machine.go
  test/e2e/framework/vlan.go
  test/e2e/framework/vpc-nat-gw.go
  test/e2e/framework/vpc.go
  test/e2e/framework/wait.go
  test/e2e/iptables-vpc-nat-gw/e2e_test.go
  test/e2e/kube-ovn/ipam/ipam.go
  test/e2e/kube-ovn/kubectl-ko/kubectl-ko.go
  test/e2e/kube-ovn/pod/vpc_pod_probe.go
  test/e2e/kube-ovn/qos/qos.go
  test/e2e/kube-ovn/service/service.go
  test/e2e/kube-ovn/subnet/subnet.go
  test/e2e/kube-ovn/switch_lb_rule/switch_lb_rule.go
  test/e2e/kube-ovn/underlay/underlay.go
  test/e2e/ovn-ic/e2e_test.go
  test/e2e/ovn-vpc-nat-gw/e2e_test.go
  test/e2e/security/e2e_test.go
  test/e2e/vip/e2e_test.go
  test/unittest/ipam/ip_range_list.go
Labels: test

#4187 add e2e test cases for nat outgoing routes
  Makefile.e2e
  dist/images/Dockerfile.base
  test/e2e/framework/framework.go
  test/e2e/framework/kube-ovn.go
  test/e2e/kube-ovn/kubectl-ko/kubectl-ko.go
  test/e2e/kube-ovn/network-policy/network-policy.go
  test/e2e/kube-ovn/node/node.go
  test/e2e/kube-ovn/pod/pod _routes.go
  test/e2e/kube-ovn/pod/vpc_pod_probe.go
  test/e2e/kube-ovn/service/service.go
  test/e2e/kube-ovn/subnet/subnet.go
  test/e2e/kube-ovn/underlay/underlay.go
  test/e2e/multus/e2e_test.go
  test/e2e/ovn-vpc-nat-gw/e2e_test.go
  test/e2e/vip/e2e_test.go
  test/e2e/webhook/pod/pod.go
Labels: test

#4177 e2e: fix getting ipv4 address from link
  test/e2e/ovn-vpc-nat-gw/e2e_test.go
Labels: test

#4125 add unit test for ip_range
  pkg/ipam/ip_range_test.go
Labels: test

#4206 fix getting service cluster ips
  pkg/util/k8s.go
Labels: bug, need backport

#4211 ic: ensure db file is fixed
  .gitignore
  Makefile
  dist/images/install-ic-server.sh
  dist/images/start-ic-db.sh
  pkg/controller/controller.go
  pkg/ovn_ic_controller/ovn_ic_controller.go
  pkg/ovs/ovn-ic-nbctl.go
  yamls/kind.yaml.j2
  yamls/ovn-ic-config.yaml.j2
Labels: need backport

#4215 base: clean ipset deb files
  dist/images/Dockerfile.base
Labels: need backport

#4220 e2e: fix logging
  test/e2e/kube-ovn/node/node.go
Labels: test

#4216 e2e: add curl parameters
  test/e2e/kube-ovn/network-policy/network-policy.go
  test/e2e/kube-ovn/node/node.go
  test/e2e/kube-ovn/service/service.go
  test/e2e/kube-ovn/switch_lb_rule/switch_lb_rule.go
  test/e2e/kube-ovn/underlay/underlay.go
  test/e2e/ovn-ic/e2e_test.go
Labels: test

#4208 support to set nic bandwidth and mirror when pod is annotated with De…
  pkg/daemon/controller.go
  pkg/daemon/controller_linux.go
Labels: feature

#4218 e2e: exec ovn-nbctl via `kubectl exec svc/ovn-nb`
  test/e2e/framework/expect.go
  test/e2e/framework/kubectl.go
  test/e2e/kube-ovn/service/service.go
  test/e2e/kube-ovn/subnet/subnet.go
  test/e2e/kube-ovn/underlay/underlay.go
  test/e2e/kubevirt/e2e_test.go
  test/e2e/ovn-ic/e2e_test.go
  test/e2e/vip/e2e_test.go
Labels: test

#4223 fix ipv6 service ip not added to ovn lb vips due to pod cache not synced
  pkg/controller/endpoint.go
  pkg/controller/gc.go
  pkg/controller/service.go
  test/e2e/kube-ovn/service/service.go
Labels: bug, need backport

#4225 e2e: retry traceroute
  test/e2e/kube-ovn/network-policy/network-policy.go
  test/e2e/kube-ovn/subnet/subnet.go
Labels: test

#4227 ci: collect and upload audit logs on e2e failure
  .github/workflows/build-x86-image.yaml
  .gitignore
  Makefile
  hack/audit-to-json.sh
  yamls/audit-policy.yaml
  yamls/kind.yaml.j2
Labels: ci

#4231 ci: dump/upload events on e2e test failure
  .github/workflows/build-x86-image.yaml
  Makefile
  test/e2e/framework/framework.go
Labels: ci

#4235 lb svc: fix dead lock
  pkg/controller/service.go
  pkg/controller/service_lb.go
  pkg/controller/vpc_lb.go
  pkg/controller/vpc_nat_gateway.go
  test/e2e/framework/deployment.go
  test/e2e/multus/e2e_test.go
Labels: bug

#4230 update node labels/annotations by json merge patch
  cmd/daemon/cniserver.go
  pkg/controller/external_gw.go
  pkg/controller/node.go
  pkg/daemon/controller.go
  pkg/daemon/ovs_linux.go
  pkg/ovn_ic_controller/ovn_ic_controller.go
  pkg/util/k8s.go
Labels: bug, need backport
