Repository kubeovn/kube-ovn, pull requests merged in 2024-12, with the labels that each got.

#4692 feature: VPC Egress Gateway
  .github/workflows/build-x86-image.yaml
  Makefile.e2e
  charts/kube-ovn/Chart.yaml
  charts/kube-ovn/templates/controller-deploy.yaml
  charts/kube-ovn/templates/kube-ovn-crd.yaml
  charts/kube-ovn/templates/ovn-CR.yaml
  dist/images/bfdd-prestart.sh
  dist/images/cleanup.sh
  dist/images/init-vpc-egress-gateway.sh
  dist/images/install.sh
  dist/images/kubectl-ko
  dist/images/start-bfdd.sh
  mocks/pkg/ovs/interface.go
  pkg/apis/kubeovn/v1/condition.go
  pkg/apis/kubeovn/v1/register.go
  pkg/apis/kubeovn/v1/vpc-egress-gateway.go
  pkg/apis/kubeovn/v1/vpc.go
  pkg/apis/kubeovn/v1/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/typed/kubeovn/v1/fake/fake_kubeovn_client.go
  pkg/client/clientset/versioned/typed/kubeovn/v1/fake/fake_vpcegressgateway.go
  pkg/client/clientset/versioned/typed/kubeovn/v1/generated_expansion.go
  pkg/client/clientset/versioned/typed/kubeovn/v1/kubeovn_client.go
  pkg/client/clientset/versioned/typed/kubeovn/v1/vpcegressgateway.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/kubeovn/v1/interface.go
  pkg/client/informers/externalversions/kubeovn/v1/vpcegressgateway.go
  pkg/client/listers/kubeovn/v1/expansion_generated.go
  pkg/client/listers/kubeovn/v1/vpcegressgateway.go
  pkg/controller/config.go
  pkg/controller/controller.go
  pkg/controller/deployment.go
  pkg/controller/subnet.go
  pkg/controller/vpc.go
  pkg/controller/vpc_egress_gateway.go
  pkg/ovn_ic_controller/ovn_ic_controller.go
  pkg/ovs/interface.go
  pkg/ovs/ovn-nb-bfd.go
  pkg/ovs/ovn-nb-bfd_test.go
  pkg/ovs/ovn-nb-logical_router_policy.go
  pkg/ovs/ovn-nb-logical_router_policy_test.go
  pkg/ovs/ovn-nb-logical_router_route.go
  pkg/ovs/ovn.go
  pkg/util/const.go
  pkg/util/hash.go
  pkg/util/k8s.go
  pkg/util/pod_routes.go
  pkg/util/strings.go
  test/e2e/framework/framework.go
  test/e2e/framework/pod.go
  test/e2e/framework/provider-network.go
  test/e2e/framework/vlan.go
  test/e2e/framework/vpc-egress-gateway.go
  test/e2e/kube-ovn/subnet/subnet.go
  test/e2e/kube-ovn/underlay/underlay.go
  test/e2e/ovn-vpc-nat-gw/e2e_test.go
  test/e2e/vpc-egress-gateway/e2e_test.go
  yamls/audit-policy.yaml
Labels: feature, vpc, size:XXL, lgtm

#4782 ci: bump kubevirt to v1.4.0
  .github/workflows/build-x86-image.yaml
  Makefile
Labels: ci, size:S, lgtm

#4781 bump go to 1.23.4
  dist/images/Dockerfile.base
  dist/images/go-deps/download-go-deps.sh
  go.mod
  go.sum
  test/anp/go.mod
Labels: dependencies, size:S

#4783 ci: report unittest coverage
  .github/workflows/build-x86-image.yaml
  .gitignore
  Makefile
Labels: ci, size:XS

#4791 auto detect kubevirt install
  pkg/controller/controller.go
  pkg/controller/kubevirt.go
  pkg/controller/pod.go
Labels: size:M, lgtm

#4797 base: fix underlay network break during upgrade from v1.12
  dist/images/Dockerfile.base
Labels: bug, need backport, size:XS, lgtm

#4799 ci: fix names of artifacts uploaded by vpc egress agteway e2e test
  .github/workflows/build-x86-image.yaml
Labels: ci, size:S, lgtm

#4807 fix issue 4803: The two names should have a containment relationship
  pkg/webhook/static_ip.go
Labels: bug, size:XS, lgtm

#4813 bump k8s to v1.31.4
  dist/images/Dockerfile.base
  dist/images/go-deps/download-go-deps.sh
  go.mod
  go.sum
Labels: dependencies, size:M, lgtm

#4790 add some unittests
  go.mod
  go.sum
  mocks/pkg/ovs/interface.go
  pkg/apis/kubeovn/v1/condition_test.go
  pkg/apis/kubeovn/v1/register_test.go
  pkg/apis/kubeovn/v1/zz_generated.deepcopy_test.go
  pkg/controller/vpc.go
  pkg/controller/vpc_egress_gateway.go
  pkg/ovs/interface.go
  pkg/ovs/ovn-nb-bfd_test.go
  pkg/ovs/ovn-nb-logical_router_policy_test.go
  pkg/ovs/ovn-nb-logical_router_route.go
  pkg/ovs/ovn-nb-logical_router_route_test.go
  pkg/ovs/ovn-nb-suite_test.go
  pkg/util/hash_test.go
  pkg/util/k8s_test.go
  pkg/util/patch_test.go
  pkg/util/pod_routes.go
  pkg/util/pod_routes_test.go
  pkg/util/strings_test.go
Labels: test, size:XXL, lgtm

#4816 fix(helm): add get on crd for ovn-cr
  charts/kube-ovn/templates/ovn-CR.yaml
Labels: chart, size:XS

#4819 release v1.12.7-mc
  charts/kube-ovn/Chart.yaml
  charts/kube-ovn/values.yaml
  dist/images/install.sh
Labels: chart, size:XS, lgtm

#4820 prepare for next release
  VERSION
Labels: size:XS

#4810 fix node local dns ip hit ct when acl is set
  dist/images/Dockerfile.base
Labels: bug, size:XS, lgtm

#4774 add anp/banp unit test
  pkg/controller/admin_network_policy.go
  pkg/controller/admin_network_policy_test.go
  pkg/controller/baseline_admin_network_policy.go
  pkg/controller/baseline_admin_network_policy_test.go
Labels: test, network policy, size:L

#4824 skip node local dns ip conntrack when set acl 1.13
  dist/images/Dockerfile.base
Labels: size:XS

#4828 cni: do not exit if the sysctl variable does not exist or can not be set
  cmd/cni/sysctl.go
Labels: bug, need backport, go, size:XS, lgtm

#4835 refactor: remove redundant policy route addition in node handling
  pkg/controller/node.go
Labels: performance, size:XS, lgtm

#4836 e2e: add test case for specifying mac address when nad plugin is macvlan
  dist/images/kubectl-ko
  pkg/controller/gc.go
  pkg/controller/pod.go
  pkg/controller/service_lb.go
  pkg/controller/vpc_dns.go
  pkg/controller/vpc_egress_gateway.go
  pkg/controller/vpc_lb.go
  pkg/controller/vpc_nat_gateway.go
  pkg/daemon/controller.go
  pkg/daemon/controller_linux.go
  pkg/daemon/controller_windows.go
  pkg/util/const.go
  pkg/util/k8s.go
  pkg/util/network_attachment.go
  pkg/util/network_attachment_test.go
  test/e2e/framework/cni.go
  test/e2e/kube-ovn/node/node.go
  test/e2e/kube-ovn/pod/pod_routes.go
  test/e2e/kube-ovn/service/service.go
  test/e2e/kube-ovn/subnet/subnet.go
  test/e2e/lb-svc/e2e_test.go
  test/e2e/multus/e2e_test.go
  test/e2e/ovn-vpc-nat-gw/e2e_test.go
  test/e2e/vip/e2e_test.go
  test/e2e/vpc-egress-gateway/e2e_test.go
  test/e2e/webhook/pod/pod.go
Labels: test, size:XL, lgtm

#4839 ci: wait for kubevirt crd to be created before creating CR
  Makefile
Labels: ci, need backport, size:S, lgtm

#4844 fix getting subnet cidr by protocol
  pkg/daemon/gateway.go
  pkg/daemon/gateway_linux.go
  pkg/daemon/gateway_test.go
Labels: bug, need backport, size:M, lgtm

#4838 use JSON merge patch to update labels/annotations
  charts/kube-ovn/templates/ovn-CR.yaml
  cmd/daemon/cniserver.go
  dist/images/install.sh
  pkg/apis/kubeovn/v1/zz_generated.deepcopy_test.go
  pkg/controller/endpoint.go
  pkg/controller/external_gw.go
  pkg/controller/init.go
  pkg/controller/inspection.go
  pkg/controller/namespace.go
  pkg/controller/node.go
  pkg/controller/pod.go
  pkg/controller/vpc_nat_gateway.go
  pkg/daemon/controller.go
  pkg/daemon/ovs_linux.go
  pkg/ovn_ic_controller/controller.go
  pkg/ovn_ic_controller/ovn_ic_controller.go
  pkg/ovn_leader_checker/ovn.go
  pkg/ovn_leader_checker/ovn_test.go
  pkg/speaker/controller.go
  pkg/util/k8s.go
  pkg/util/k8s_test.go
  pkg/util/patch.go
  pkg/util/patch_test.go
Labels: bug, enhancement, need backport, size:XL, lgtm

#4842 use cache.MetaObjectToName() to get namespaced name
  pkg/controller/admin_network_policy.go
  pkg/controller/baseline_admin_network_policy.go
  pkg/controller/controller.go
  pkg/controller/deployment.go
  pkg/controller/endpoint.go
  pkg/controller/inspection.go
  pkg/controller/ip.go
  pkg/controller/ippool.go
  pkg/controller/kubevirt.go
  pkg/controller/namespace.go
  pkg/controller/network_policy.go
  pkg/controller/node.go
  pkg/controller/ovn_dnat.go
  pkg/controller/ovn_eip.go
  pkg/controller/ovn_fip.go
  pkg/controller/ovn_snat.go
  pkg/controller/pod.go
  pkg/controller/qos_policy.go
  pkg/controller/security_group.go
  pkg/controller/service.go
  pkg/controller/signer.go
  pkg/controller/subnet.go
  pkg/controller/switch_lb_rule.go
  pkg/controller/vip.go
  pkg/controller/vlan.go
  pkg/controller/vpc.go
  pkg/controller/vpc_dns.go
  pkg/controller/vpc_egress_gateway.go
  pkg/controller/vpc_nat_gateway.go
  pkg/controller/vpc_nat_gw_eip.go
  pkg/controller/vpc_nat_gw_nat.go
  pkg/daemon/controller.go
Labels: refactor, size:XL, lgtm

#4821 remove unused function
  pkg/ovs/ovn-nb-suite_test.go
  pkg/ovs/ovs-vsctl.go
  pkg/ovs/ovs-vsctl_test.go
Labels: refactor, size:S, lgtm

#4851 deps: bump golang.org/x/net to v0.33.0
  .github/workflows/build-x86-image.yaml
  go.mod
  go.sum
Labels: security, dependencies, go, size:M

#4852 bump go to 1.23.4
  .github/workflows/build-x86-image.yaml
  dist/images/Dockerfile.base
  dist/images/go-deps/download-go-deps.sh
  go.mod
  go.sum
  hack/update-codegen-docker.sh
  test/anp/go.mod
Labels: security, dependencies, go, size:L

#4853 bump go to 1.22.10
  dist/images/Dockerfile.base
  go.mod
  go.sum
Labels: security, dependencies, go, size:M

#4854 bump go to 1.22.10
  dist/images/Dockerfile.base
  go.mod
  go.sum
Labels: security, dependencies, go, size:S

#4857 fix: err is always nil
  pkg/controller/gc.go
  pkg/daemon/handler.go
  pkg/util/validator.go
  pkg/util/validator_test.go
Labels: bug, size:XS, lgtm

#4855 clean up legacy iptables rules only when iptables/ip6_tables is loaded
  pkg/daemon/controller_linux.go
Labels: need backport, go, size:M, lgtm

#4848 fix(controller/subnet): controller crashes on subnets if gateway is u…
  pkg/controller/subnet.go
Labels: bug, need backport, size:S

#4863 keep dockerfile variable the same as download-go-deps.sh
  dist/images/Dockerfile.base
Labels: size:XS

#4826 Add default subnet in custom vpc to the beginning of the list
  pkg/controller/namespace.go
Labels: vpc, size:XS, lgtm

#4825 skip node local dns ip conntrack when set acl
  dist/images/Dockerfile.base
Labels: network policy, size:XS, lgtm

#4800 pod should use mac and ips provider by multus firstly
  pkg/controller/pod.go
  test/e2e/multus/e2e_test.go
Labels: bug, size:M, lgtm

#4874 add kubevirt live migration optimize (#4773)
  charts/kube-ovn/templates/controller-deploy.yaml
  charts/kube-ovn/templates/ovn-CR.yaml
  charts/kube-ovn/values.yaml
  dist/images/install.sh
  go.mod
  go.sum
  pkg/controller/config.go
  pkg/controller/controller.go
  pkg/controller/kubevirt.go
  pkg/controller/pod.go
  pkg/util/const.go
Labels: feature, go, size:L

#4875 pod should use mac and ips provider by multus firstly (#4800)
  pkg/controller/pod.go
Labels: size:M

#4876 auto detect kubevirt install (#4791)
  pkg/controller/controller.go
  pkg/controller/kubevirt.go
  pkg/controller/pod.go
Labels: feature, size:M

#4878 should be able to use mac and ip provided by k8s.v1.cni.cncf.io/netwo…
  test/e2e/multus/e2e_test.go
Labels: test, size:XS

#4877 remove unused function
  pkg/controller/init.go
  pkg/ovs/ovn-nb-dhcp_options.go
  pkg/ovs/ovn-nb-dhcp_options_test.go
  pkg/ovs/ovn-nb-suite_test.go
Labels: refactor, size:M, lgtm

#4879 fix security
  go.mod
  go.sum
Labels: security, size:S, lgtm

#4880 fix golangci-lint
  test/e2e/multus/e2e_test.go
Labels: go, size:XS, lgtm

#4793 add nodeSelector for lb-svc
  pkg/controller/service_lb.go
Labels: feature, need backport, size:M, lgtm

#4882 bump go modules used by ANP e2e tests
  test/anp/go.mod
  test/anp/go.sum
Labels: dependencies, go, size:M, lgtm

#4883 ipam: use ip provided by nad annotation when providing IPAM for other CNI plugins
  pkg/controller/pod.go
  test/e2e/framework/iproute/iproute.go
  test/e2e/multus/e2e_test.go
Labels: enhancement, need backport, size:L, lgtm

#4885 rename Makefile.e2e to e2e.mk
  Makefile
  e2e.mk
Labels: size:XS, lgtm

#4777 Support multiple IPPools in the namespace
  pkg/controller/namespace.go
  pkg/controller/pod.go
  test/e2e/framework/namespace.go
  test/e2e/kube-ovn/ipam/ipam.go
  test/e2e/kube-ovn/subnet/subnet-selectors.go
Labels: feature, test, size:L, lgtm
