Repository kubeovn/kube-ovn, pull requests merged in 2024-03, with the labels that each got.

#3785 bump github.com/osrg/gobgp/v3 to v3.24.0
  go.mod
  go.sum
Labels: dependencies, go

#3787 fix incorrect variable assignment
  pkg/controller/node.go
Labels: bug, need backport

#3790 fix: go toolchain config
  go.mod
Labels: go

#3795 Makefile: add target kind-install-metallb
  .gitignore
  Makefile
Labels: need backport

#3805 Fix newly created multi-network card pod traffic mirroring
  pkg/daemon/handler.go
Labels: bug, need backport

#3806 pinger: do not setup metrics if disabled
  cmd/pinger/pinger.go
  pkg/pinger/config.go
  pkg/pinger/ovn.go
  pkg/pinger/ping.go
Labels: need backport

#3800 add sts e2e case for pr
  test/e2e/framework/statefulset.go
  test/e2e/kube-ovn/pod/statefulset.go
Labels: test

#3818 Makefile: fix clab bgp configuration
  .gitignore
  Makefile
  yamls/clab-bgp-ha.yaml.j2
  yamls/clab-bgp.yaml.j2
Labels: need backport

#3808 kubectl-ko: fix subnet diagnose failure
  cmd/pinger/pinger.go
  dist/images/kubectl-ko
  pkg/util/net.go
  test/e2e/kube-ovn/kubectl-ko/kubectl-ko.go
  test/e2e/kube-ovn/node/node.go
  test/e2e/kube-ovn/switch_lb_rule/switch_lb_rule.go
Labels: bug, need backport

#3837 bump github.com/onsi/ginkgo/v2 to v2.17.0
  Makefile
  Makefile.e2e
  go.mod
  go.sum
Labels: ci, dependencies, go

#3829 ci: bump helm to v3.14.3
  .github/workflows/build-x86-image.yaml
  .github/workflows/scheduled-e2e.yaml
  .gitignore
  Makefile
Labels: ci

#3843 iptables: reject access to invalid service port only for TCP
  dist/images/uninstall.sh
  pkg/daemon/gateway_linux.go
Labels: bug, need backport

#3833 bump k8s to v1.29.3
  dist/images/Dockerfile.base
  go.mod
  go.sum
  hack/update-codegen-docker.sh
Labels: dependencies, go

#3851 chart: fix missing ENABLE_IC
  charts/kube-ovn/templates/ic-controller-deploy.yaml
  charts/kube-ovn/values.yaml
Labels: need backport, chart

#3872 fix reference to nil pointer
  pkg/controller/init.go
  pkg/controller/subnet.go
Labels: bug

#3873 ci: fix memory leak reporting caused by ovn-controller crashes
  .github/workflows/build-x86-image.yaml
Labels: ci, need backport

#3879 ovn: update patch for skipping ct
  dist/images/Dockerfile.base
  mocks/pkg/ovs/interface.go
  pkg/controller/subnet.go
  pkg/ovs/interface.go
  pkg/ovs/ovn-nb-logical_switch_port.go
  pkg/ovs/ovn-nb-logical_switch_port_test.go
  pkg/ovs/ovn-nb.go
Labels: performance, need backport

#3871 compile binaries with debug information for debug images
  .github/workflows/build-arm64-image.yaml
  Makefile
Labels: need backport

#3881 ovn: reduce down time during upgrading from version 21.06
  charts/kube-ovn/templates/central-deploy.yaml
  dist/images/Dockerfile.base
Labels: need backport
