Repository kubeovn/kube-ovn, pull requests merged in 2024-01, with the labels that each got.

#3594 bump k8s to v1.28.5
  go.mod
  go.sum
Labels: dependencies, go, network policy

#3530 ovs: increase cpu limit to 2 cores
  charts/values.yaml
  dist/images/install.sh
Labels: bug, need backport

#3599 ci: install kube-ovn with helm chart
  .github/workflows/build-x86-image.yaml
  Makefile
Labels: ci

#3613 chart: fix ovs-ovn upgrade
  Makefile
  charts/Chart.yaml
  charts/templates/_helpers.tpl
  charts/templates/kube-ovn-crd.yaml
  charts/templates/ovsovn-ds.yaml
  charts/templates/upgrade-ovs-ovn.yaml
  dist/images/upgrade-ovs.sh
Labels: bug, need backport, chart

#3649 kube-ovn-monitor and kube-ovn-pinger should not export pprof path
  cmd/ovn_monitor/ovn_monitor.go
  cmd/pinger/pinger.go
Labels: bug, need backport

#3654 bump go modules
  .github/workflows/build-x86-image.yaml
  .github/workflows/scheduled-e2e.yaml
  Makefile
  dist/images/Dockerfile.base
  go.mod
  go.sum
  test/e2e/framework/docker/container.go
Labels: dependencies, go

#3650 ovs: reduce cpu utilization
  dist/images/Dockerfile.base
Labels: performance, need backport

#3644 chart: fix parsing image tag when the image url contains a port
  charts/templates/_helpers.tpl
Labels: bug, need backport, chart

#3661 fix nil pointer
  pkg/controller/vpc_nat_gw_eip.go
Labels: need backport

#3662 fix 409
  pkg/util/validator.go
  pkg/util/validator_test.go
  pkg/webhook/subnet.go
Labels: need backport

#3665 delete cm ovn-ic-config cause crash 1.11
  dist/images/install.sh
  kubeovn-helm/templates/ic-controller-deploy.yaml
  pkg/ovn_ic_controller/ovn_ic_controller.go
Labels: bug, need backport

#3664 replace github.com/golang/mock with go.uber.org/mock/mockgen
  dist/images/ovn-ic-db-docker.sh
  go.mod
  go.sum
  hack/mockgen.sh
  mocks/pkg/ovs/interface.go
  pkg/controller/controller_test.go
  pkg/controller/ovn_ic_test.go
  pkg/controller/security_group_test.go
  pkg/controller/subnet_test.go
  yamls/ovn-dpdk.yaml
  yamls/rh-mod-job.yaml
Labels: dependencies, go

#3632 ovn-ic-ecmp refactor
  Makefile
  charts/templates/ic-controller-deploy.yaml
  cmd/cmdmain.go
  cmd/ovn_ic_controller/ovn_ic_controller.go
  dist/images/Dockerfile
  dist/images/cleanup.sh
  dist/images/install-ic-server.sh
  dist/images/install.sh
  dist/images/kubectl-ko
  dist/images/ovn-ic-db-docker.sh
  dist/images/ovn-ic-healthcheck.sh
  dist/images/start-ic-controller.sh
  dist/images/start-ic-db.sh
  pkg/controller/controller.go
  pkg/controller/ovn_ic_test.go
  pkg/daemon/gateway_linux.go
  pkg/ovn_ic_controller/config.go
  pkg/ovn_ic_controller/controller.go
  pkg/ovn_ic_controller/ovn_ic_controller.go
  pkg/ovn_leader_checker/ovn.go
  pkg/ovs/ovn-ic-nbctl.go
  pkg/ovs/ovn-ic-sbctl.go
  test/e2e/framework/framework.go
  test/e2e/ovn-ic/e2e_test.go
  yamls/kind.yaml.j2
Labels: feature, need backport

#3637 ovn-ic-ecmp refactor 1.12
  Makefile
  charts/templates/ic-controller-deploy.yaml
  cmd/cmdmain.go
  cmd/ovn_ic_controller/ovn_ic_controller.go
  dist/images/Dockerfile
  dist/images/cleanup.sh
  dist/images/install-ic-server.sh
  dist/images/install.sh
  dist/images/kubectl-ko
  dist/images/ovn-ic-healthcheck.sh
  dist/images/start-ic-controller.sh
  dist/images/start-ic-db.sh
  pkg/controller/controller.go
  pkg/controller/ovn_ic_test.go
  pkg/daemon/gateway_linux.go
  pkg/ovn_ic_controller/config.go
  pkg/ovn_ic_controller/controller.go
  pkg/ovn_ic_controller/ovn_ic_controller.go
  pkg/ovn_leader_checker/ovn.go
  pkg/ovs/ovn-ic-nbctl.go
  pkg/ovs/ovn-ic-sbctl.go
  test/e2e/framework/framework.go
  yamls/kind.yaml.j2
Labels: feature, need backport

#3663 ovn: do not send direct traffic between lports to conntrack
  charts/templates/controller-deploy.yaml
  charts/values.yaml
  dist/images/Dockerfile.base
  dist/images/install.sh
  mocks/pkg/ovs/interface.go
  pkg/controller/config.go
  pkg/controller/controller.go
  pkg/ovs/interface.go
  pkg/ovs/ovn-nb_global.go
  yamls/kube-ovn-dual-stack.yaml
  yamls/kube-ovn-ipv6.yaml
  yamls/kube-ovn.yaml
Labels: performance, need backport, network policy

#3678 Makefile: fix install/upgrade chart
  Makefile
Labels: need backport

#3671 ovn: add nb option version_compatibility
  charts/templates/central-deploy.yaml
  charts/templates/upgrade-ovs-ovn.yaml
  dist/images/Dockerfile.base
  dist/images/start-db.sh
  dist/images/upgrade-ovs.sh
Labels: need backport, chart

#3680 set after genev_sys_6081 started
  cmd/daemon/cniserver.go
Labels: bug, need backport

#3667 Support ip creation
  pkg/controller/controller.go
  pkg/controller/external_gw.go
  pkg/controller/gc.go
  pkg/controller/init.go
  pkg/controller/ip.go
  pkg/controller/node.go
  pkg/controller/ovn_eip.go
  pkg/controller/pod.go
  pkg/controller/pod_iptables_eip.go
  pkg/controller/pod_iptables_fip.go
  pkg/controller/subnet.go
  pkg/controller/vip.go
  pkg/controller/vpc.go
  pkg/controller/vpc_nat_gw_eip.go
  pkg/controller/vpc_nat_gw_nat.go
  pkg/daemon/handler.go
  pkg/ipam/ipam.go
  pkg/util/const.go
  pkg/util/net.go
  pkg/webhook/ip.go
  pkg/webhook/static_ip.go
  pkg/webhook/webhook.go
  test/e2e/webhook/pod/pod.go
Labels: feature

#3677 Compatible with controller deployment methods before kube-ovn 1.11.16
  dist/images/start-ic-db.sh
Labels: need backport
