Repository kubeovn/kube-ovn, pull requests merged in 2024-07, with the labels that each got.

#4246 do not exit if chassis is not found
  pkg/controller/init.go
  pkg/controller/node.go
Labels: bug, need backport

#4238 check both sts name and UID when handling pod deletion
  pkg/controller/gc.go
  pkg/controller/init.go
  pkg/controller/pod.go
Labels: bug, need backport

#4247 ci: do not compile fastpath kernel module for centos
  .github/workflows/build-x86-image.yaml
Labels: ci, need backport

#4236 refactor lb svc e2e
  Makefile
  test/e2e/framework/cni.go
  test/e2e/lb-svc/e2e_test.go
  test/e2e/multus/e2e_test.go
  yamls/lb-svc-attachment.yaml
Labels: test

#4242 do not allocate mac for non-ovn subnets
  pkg/controller/ip.go
  pkg/controller/pod.go
  pkg/daemon/handler.go
  pkg/ipam/ipam.go
  test/e2e/multus/e2e_test.go
Labels: need backport

#4260 do not create iptables rule for setting tcp mss
  pkg/daemon/gateway.go
  pkg/daemon/gateway_linux.go
  pkg/daemon/gateway_windows.go
Labels: need backport

#4264 fix vpcnatgw image is not synced
  pkg/controller/controller.go
  pkg/controller/service_lb.go
  pkg/controller/vpc_lb.go
  pkg/controller/vpc_nat.go
  pkg/controller/vpc_nat_gateway.go
Labels: bug, need backport

#4265 ipam: fix ip not released for non-ovn subnets
  pkg/ipam/subnet.go
Labels: bug, need backport

#4266 when router is deleted return success for static route deletion
  pkg/ovs/ovn-nb-logical_router_route.go
Labels: bug, need backport

#4268 ci: disable cgo when building kubelet and cni plugins
  .github/workflows/build-arm64-image.yaml
  .github/workflows/build-x86-image.yaml
Labels: ci

#4270 remove unused environment variable LOG_ROTATE
  charts/kube-ovn/templates/ovn-dpdk-ds.yaml
  charts/kube-ovn/templates/ovsovn-ds.yaml
  dist/images/install.sh
Labels: need backport

#4271 logrotate: set file size limit to 100M
  dist/images/Dockerfile
  dist/images/logrotate/kubeovn
  dist/images/logrotate/openvswitch
  dist/images/logrotate/ovn
Labels: need backport

#4272 klog: set log file max size to 200MB
  charts/kube-ovn/templates/controller-deploy.yaml
  charts/kube-ovn/templates/ic-controller-deploy.yaml
  charts/kube-ovn/templates/monitor-deploy.yaml
  charts/kube-ovn/templates/ovncni-ds.yaml
  charts/kube-ovn/templates/pinger-ds.yaml
  dist/images/install.sh
Labels: need backport

#4274 ci: run go mod tidy before building kubectl
  .github/workflows/build-arm64-image.yaml
  .github/workflows/build-x86-image.yaml
Labels: ci

#4280 fix ovn lb not updated due to service update failure
  pkg/controller/endpoint.go
Labels: bug, need backport

#4284 fix using route table name as vpc name
  pkg/controller/pod.go
  pkg/controller/subnet.go
Labels: bug, need backport

#4282 underlay: set trunks of host nic port
  charts/kube-ovn/templates/ovn-CR.yaml
  dist/images/install.sh
  pkg/daemon/controller.go
  pkg/daemon/init.go
  pkg/daemon/ovs_linux.go
  pkg/daemon/ovs_windows.go
Labels: need backport

#4290 add anp/banp code
  charts/kube-ovn/templates/ovn-CR.yaml
  dist/images/install.sh
  go.mod
  go.sum
  mocks/pkg/ovs/interface.go
  pkg/controller/admin_network_policy.go
  pkg/controller/baseline_admin_network_policy.go
  pkg/controller/config.go
  pkg/controller/controller.go
  pkg/controller/namespace.go
  pkg/controller/pod.go
  pkg/ovs/interface.go
  pkg/ovs/ovn-nb-acl.go
  pkg/ovs/ovn-nb-acl_test.go
  pkg/ovs/ovn-nb_test.go
  pkg/ovsdb/ovnnb/acl.go
  pkg/util/const.go
  yamls/adminnetworkpolicies-v0.1.5.yaml
  yamls/baselineadminnetworkpolicies-v0.1.5.yaml
Labels: network policy

#3040 security: run as unprivileged
  charts/kube-ovn/templates/central-deploy.yaml
  charts/kube-ovn/templates/controller-deploy.yaml
  charts/kube-ovn/templates/ovncni-ds.yaml
  charts/kube-ovn/templates/ovsovn-ds.yaml
  dist/images/install.sh
  pkg/daemon/ovs_linux.go
  yamls/speaker.yaml
  yamls/webhook.yaml
Labels: security, need backport

#4302 fix map concurrent read and write crash
  cmd/controller/controller.go
  pkg/controller/controller.go
Labels: bug, need backport

#4306 bump k8s to v1.27.16
  dist/images/Dockerfile.base
  go.mod
  go.sum
Labels: dependencies, go

#4305 bump k8s to v1.30.3
  dist/images/Dockerfile.base
  go.mod
  go.sum
Labels: dependencies, go

#4307 bump k8s to v1.27.16
  dist/images/Dockerfile.base
  go.mod
  go.sum
Labels: dependencies, go

#4297 metrics: add support for secure serving
  charts/kube-ovn/templates/controller-deploy.yaml
  charts/kube-ovn/templates/monitor-deploy.yaml
  charts/kube-ovn/templates/ovn-CR.yaml
  charts/kube-ovn/templates/ovn-CRB.yaml
  charts/kube-ovn/templates/ovncni-ds.yaml
  charts/kube-ovn/values.yaml
  cmd/controller/controller.go
  cmd/controller_health_check/controller_health_check.go
  cmd/daemon/cniserver.go
  cmd/ovn_monitor/ovn_monitor.go
  dist/images/install.sh
  go.mod
  pkg/controller/config.go
  pkg/daemon/config.go
  pkg/daemon/tproxy_linux.go
  pkg/ovnmonitor/config.go
  pkg/pinger/ping.go
  pkg/server/server.go
  pkg/util/net.go
Labels: security, need backport

#4320 e2e: skip north gateway test for versions prior to v1.12
  test/e2e/kube-ovn/pod/pod_routes.go
Labels: test

#4321 ci: add timeout for executing cleanup.sh
  .github/workflows/build-x86-image.yaml
Labels: ci

#4311 bump kubevirt to v1.3.0
  Makefile
  go.mod
  go.sum
  pkg/controller/gc.go
  pkg/controller/pod.go
  test/e2e/framework/virtual-machine.go
Labels: dependencies, go

#4312 metrics: fix missing rbac for sa ovn
  charts/kube-ovn/templates/ovn-CR.yaml
  charts/kube-ovn/templates/ovn-CRB.yaml
  dist/images/install.sh
Labels: bug, need backport

#4324 fix dialing https server
  charts/kube-ovn/templates/controller-deploy.yaml
  cmd/controller_health_check/controller_health_check.go
  dist/images/install.sh
  pkg/util/k8s.go
Labels: bug, need backport

#4287 ci: bump submariner to 0.18.0
  .github/workflows/build-x86-image.yaml
  Makefile
  yamls/kwok-stage.yaml
  yamls/kwok.yaml
Labels: ci

#4294 add support for interface activation strategy
  dist/images/Dockerfile.base
  mocks/pkg/ovs/interface.go
  pkg/controller/pod.go
  pkg/daemon/handler.go
  pkg/daemon/ovs_linux.go
  pkg/ovs/interface.go
  pkg/ovs/ovn-nb-logical_switch_port.go
  pkg/util/const.go
Labels: feature

#4329 pinger: fix process not terminated on sigkill
  cmd/ovn_ic_controller/ovn_ic_controller.go
  cmd/pinger/pinger.go
  cmd/speaker/speaker.go
  go.mod
  go.sum
  pkg/pinger/ping.go
Labels: need backport

#4333 crd: fix missing fields
  charts/kube-ovn/templates/kube-ovn-crd.yaml
  dist/images/install.sh
Labels: bug

#4326 security: run as non-root user
  .github/workflows/build-x86-image.yaml
  .gitignore
  Makefile
  charts/kube-ovn/templates/central-deploy.yaml
  charts/kube-ovn/templates/controller-deploy.yaml
  charts/kube-ovn/templates/ic-controller-deploy.yaml
  charts/kube-ovn/templates/monitor-deploy.yaml
  charts/kube-ovn/templates/ovncni-ds.yaml
  charts/kube-ovn/templates/ovsovn-ds.yaml
  charts/kube-ovn/templates/pinger-ds.yaml
  cmd/cmdmain.go
  cmd/controller/controller.go
  cmd/daemon/cniserver.go
  cmd/daemon/init.go
  cmd/daemon/init_windows.go
  cmd/ovn_ic_controller/ovn_ic_controller.go
  cmd/ovn_monitor/ovn_monitor.go
  cmd/pinger/pinger.go
  cmd/speaker/speaker.go
  cmd/windows/daemon/main_windows.go
  dist/images/Dockerfile
  dist/images/Dockerfile.base
  dist/images/install-cni.sh
  dist/images/install-ic-server.sh
  dist/images/install.sh
  dist/images/iptables-wrapper-installer.sh
  go.mod
  go.sum
  pkg/daemon/config.go
  pkg/daemon/controller_linux.go
  pkg/daemon/exporter_metric.go
  pkg/daemon/metrics.go
  pkg/daemon/netns_linux.go
  pkg/daemon/ovs_linux.go
  test/e2e/framework/exec_utils.go
  test/e2e/ha/ha_test.go
  test/e2e/kube-ovn/node/node.go
  test/e2e/kube-ovn/pod/pod_routes.go
  test/e2e/kube-ovn/underlay/underlay.go
  test/e2e/multus/e2e_test.go
  test/e2e/security/e2e_test.go
  yamls/coredns-template.yaml
Labels: security, need backport

#4296 Add ut
  pkg/ipam/ipam.go
  pkg/ipam/ipam_test.go
Labels: test

#4338 add acl action log annotation for netpol/anp/banp
  mocks/pkg/ovs/interface.go
  pkg/controller/admin_network_policy.go
  pkg/controller/baseline_admin_network_policy.go
  pkg/controller/network_policy.go
  pkg/ovs/interface.go
  pkg/ovs/ovn-nb-acl.go
  pkg/ovs/ovn-nb-acl_test.go
  pkg/util/const.go
Labels: network policy

#4285 Add BGP capabilities to the NAT GW
  charts/kube-ovn/templates/kube-ovn-crd.yaml
  dist/images/install.sh
  pkg/apis/kubeovn/v1/types.go
  pkg/controller/controller.go
  pkg/controller/vpc_nat.go
  pkg/controller/vpc_nat_gateway.go
  pkg/speaker/bgp.go
  pkg/speaker/config.go
  pkg/speaker/controller.go
  pkg/speaker/eip.go
  pkg/speaker/subnet.go
  pkg/speaker/utils.go
  pkg/util/const.go
Labels: feature
