Repository kubeovn/kube-ovn, pull requests merged in 2024-02, with the labels that each got.

#3692 kube-ovn-controller: remove unused codes
  pkg/controller/controller.go
Labels: need backport

#3696 remove unused option
  charts/templates/controller-deploy.yaml
  charts/values.yaml
  dist/images/install.sh
  pkg/controller/config.go
  pkg/controller/controller.go
  yamls/kube-ovn-dual-stack.yaml
  yamls/kube-ovn-ipv6.yaml
  yamls/kube-ovn.yaml
Labels: need backport

#3691 update chart release workflow
  .github/workflows/release-chart.yaml
  cr.yaml
Labels: need backport, chart

#3694 ci: bump kind to v0.21.0
  .github/workflows/build-x86-image.yaml
  .github/workflows/scheduled-e2e.yaml
  Makefile
  yamls/kind.yaml.j2
Labels: ci

#3693 bump k8s to v1.27.10
  .github/workflows/build-arm64-image.yaml
  .github/workflows/build-kube-ovn-test.yaml
  .github/workflows/build-windows.yaml
  .github/workflows/build-x86-image.yaml
  .github/workflows/changelog.yaml
  .github/workflows/codeql-analysis.yml
  .github/workflows/lint.yaml
  .github/workflows/publish.yaml
  .github/workflows/release-chart.yaml
  Makefile
  go.mod
  go.sum
  yamls/kind.yaml.j2
Labels: ci, dependencies, go

#3698 fix: ip delete use wrong key, ip delete only once
  pkg/controller/init.go
  pkg/controller/ip.go
Labels: bug

#3720 ovn: remove unnecessary patch
  Makefile
  dist/images/Dockerfile.base
  mocks/pkg/ovs/interface.go
  pkg/controller/node.go
  pkg/controller/security_group.go
  pkg/daemon/ovs.go
  pkg/ovs/interface.go
  pkg/ovs/ovn-nb-acl_test.go
  pkg/ovs/ovn-nb-load_balancer_health_check.go
  pkg/ovs/ovn-nb-logical_switch_port.go
  pkg/ovs/ovn-nb-logical_switch_port_test.go
  pkg/ovs/ovn-nb-suite_test.go
  pkg/ovs/ovn-nb_global.go
  pkg/ovs/ovs-vsctl.go
  pkg/ovs/ovs-vsctl_linux.go
  test/e2e/framework/endpoints.go
  test/e2e/framework/switch-lb-rule.go
  test/e2e/ha/ha_test.go
  test/e2e/kube-ovn/service/service.go
Labels: need backport

#3728 update chart relase action workflow
  .github/workflows/release-chart.yaml
Labels: need backport

#3731 bump libovsdb
  go.mod
  go.sum
  pkg/ovs/ovn-nb-acl_test.go
  pkg/ovs/ovn-nb-bfd_test.go
  pkg/ovs/ovn-nb-gateway_chassis.go
  pkg/ovs/ovn-nb-gateway_chassis_test.go
  pkg/ovs/ovn-nb-load_balancer.go
  pkg/ovs/ovn-nb-load_balancer_health_check.go
  pkg/ovs/ovn-nb-load_balancer_health_check_test.go
  pkg/ovs/ovn-nb-load_balancer_test.go
  pkg/ovs/ovn-nb-logical_router_port_test.go
  pkg/ovs/ovn-nb-logical_router_test.go
  pkg/ovs/ovn-nb-logical_switch.go
  pkg/ovs/ovn-nb-logical_switch_port.go
  pkg/ovs/ovn-nb-logical_switch_port_test.go
  pkg/ovs/ovn-nb-logical_switch_test.go
  pkg/ovs/ovn-nb-port_group_test.go
  pkg/ovs/ovn-nb-suite_test.go
  pkg/ovs/ovn-nb_global_test.go
  pkg/ovs/ovn.go
  pkg/ovsdb/ovnnb/model.go
  pkg/ovsdb/ovnsb/model.go
Labels: test, dependencies, go

#3729 fix kubevirt e2e
  .github/workflows/build-x86-image.yaml
  Makefile
  test/e2e/kubevirt/e2e_test.go
Labels: test, ci, need backport

#3736 dpdk: remove unnecessary ovn patch
  dist/images/Dockerfile.base-dpdk
Labels: need backport

#3725 bump k8s to v1.29.2
  Makefile
  Makefile.e2e
  go.mod
  go.sum
  test/e2e/framework/framework.go
  test/e2e/ha/ha_test.go
  test/e2e/iptables-vpc-nat-gw/e2e_test.go
  test/e2e/kube-ovn/service/service.go
  test/e2e/kube-ovn/subnet/subnet.go
  yamls/kind.yaml.j2
Labels: test, dependencies, go

#3733 remove invalid ovs build option
  dist/images/Dockerfile.base
  dist/images/Dockerfile.base-dpdk
Labels: need backport

#3735 ci: bump cilium to v1.15.1
  .github/workflows/build-x86-image.yaml
  .github/workflows/scheduled-e2e.yaml
  Makefile
  Makefile.e2e
  test/e2e/framework/framework.go
  yamls/cilium-chaining.yaml
Labels: ci

#3744 ci: collect ko logs for all kind clusters
  .github/workflows/build-x86-image.yaml
Labels: ci, need backport

#3745 base: install libmnl0 instead of libmnl-dev
  dist/images/Dockerfile.base
Labels: need backport

#3743 ci: bump azure/setup-helm to v4.0.0
  .github/workflows/build-x86-image.yaml
  .github/workflows/scheduled-e2e.yaml
Labels: ci, need backport

#3747 fix kubevirt vm e2e
  test/e2e/kubevirt/e2e_test.go
Labels: test

#3759 if startOVNIC firstly, and setazName secondly, the ovn-ic-db may sync…
  pkg/ovn_ic_controller/ovn_ic_controller.go
Labels: bug, need backport

#3764 kube-ovn-controller: fix finalizers migration
  pkg/controller/init.go
Labels: bug

#3765 e2e: fix subnet finalizers validation
  test/e2e/framework/framework.go
  test/e2e/kube-ovn/subnet/subnet.go
Labels: test

#3772 fix crd
  charts/kube-ovn/templates/kube-ovn-crd.yaml
  dist/images/install.sh
  yamls/crd.yaml
Labels: chart

#3773 fix dot imports
  .golangci.yml
  test/unittest/ipam/ipam.go
  test/unittest/unit_suite_test.go
  test/unittest/util/net.go
Labels: go

#3777 fix sts pod's logical switch port do not update externa_id vendor and ls
  pkg/ovs/ovn-nb-logical_switch_port.go
Labels: bug, need backport
