Repository kubeovn/kube-ovn, pull requests merged in 2024-11, with the labels that each got.

#4689 ut: add unit test for ovn-nb-logical_router.go
  pkg/ovs/ovn-nb-logical_router_test.go
  pkg/ovs/ovn-nb_test.go
Labels: test, size:L, lgtm

#4693 add ut for ovn-nb-logical_router_policy
  pkg/ovs/ovn-nb-logical_router_policy_test.go
  pkg/ovs/ovn-nb-suite_test.go
Labels: test, size:L, lgtm

#4695 e2e: add WaitUntil check for ns in subnet labelSelector
  test/e2e/kube-ovn/subnet/subnet-selectors.go
Labels: test, size:M, lgtm

#4660 add process for lb-svc ports update
  dist/images/vpcnatgateway/lb-svc.sh
  pkg/controller/controller.go
  pkg/controller/service.go
  pkg/controller/service_lb.go
Labels: bug, go, size:L, lgtm

#4696 add ut for ovn-nb-logical_router_port_test.go
  pkg/ovs/ovn-nb-logical_router_port_test.go
  pkg/ovs/ovn-nb-suite_test.go
Labels: test, size:L, lgtm

#4697 fix concurrent issue in ovn-nb_test.go
  pkg/ovs/ovn-nb_test.go
Labels: bug, size:XS, lgtm

#4698 ut: fix use of closed network connection
  pkg/daemon/ovs_linux.go
  pkg/ovs/ovn-nb-logical_router_port.go
  pkg/ovs/ovn-nb-suite_test.go
  pkg/ovs/ovn_test.go
Labels: test, size:M, lgtm

#4557 Make NAT gateway generation prefix a variable
  pkg/controller/vpc_nat.go
  pkg/util/vpc_nat_gateway.go
Labels: enhancement, size:S, lgtm

#4703 ci: re-add ovn vpc nat gw e2e to push needs
  .github/workflows/build-x86-image.yaml
Labels: github_actions, size:XS, lgtm

#4704 feat(natgw): extended nexthop support to advertise ipv4 NRLI over ipv6 sessions
  pkg/speaker/bgp.go
  pkg/speaker/config.go
Labels: feature, size:S, lgtm

#4706 add ut for ovn-nb-logical_router_policy.go
  pkg/ovs/ovn-nb-logical_router_policy_test.go
Labels: test, size:L, lgtm

#4701 [bugfix] When add_eip, send a GARP for eip from net1
  dist/images/vpcnatgateway/nat-gateway.sh
Labels: bug, size:XS, lgtm

#4710 ut: fix duplicate LSP name
  pkg/ovs/ovn-nb-logical_switch_port_test.go
Labels: test, size:S, lgtm

#4711 ut: add unit test for pkg/pvs
  pkg/ovs/ovn-nb-gateway_chassis_test.go
  pkg/ovs/ovn-nb-suite_test.go
  pkg/util/k8s_test.go
Labels: test, size:M, lgtm

#4713 add ut in pkg/ovs 24.11.7
  pkg/ovs/ovn-nb-logical_router_route_test.go
  pkg/ovs/ovn-nb-logical_switch_port_test.go
  pkg/ovs/ovn-nb-logical_switch_test.go
  pkg/ovs/ovn-nb-nat_test.go
  pkg/ovs/ovn-nb-port_group_test.go
  pkg/ovs/ovn-nb_test.go
Labels: test, size:M, lgtm

#4676 add process for lb-svc ports update
  dist/images/vpcnatgateway/lb-svc.sh
  pkg/controller/service.go
  pkg/controller/service_lb.go
Labels: bug, size:L, lgtm

#4708 base: bump gobgp to v3.31.0
  .github/workflows/build-x86-image.yaml
  dist/images/go-deps/download-go-deps.sh
Labels: dependencies, size:S, lgtm

#4715 Fix ovn nat e2e
  pkg/controller/ovn_eip.go
  test/e2e/ovn-vpc-nat-gw/e2e_test.go
Labels: test, size:S, lgtm

#4682 minor fixes in vpc pod probe e2e test
  test/e2e/kube-ovn/pod/vpc_pod_probe.go
Labels: test, vpc, size:S, lgtm

#4709 use metav1.LabelSelectorAsSelector() to convert label selector
  pkg/controller/namespace.go
  pkg/controller/subnet.go
Labels: size:S

#4716 bump go to 1.23.3
  dist/images/Dockerfile.base
  go.mod
  go.sum
  test/anp/go.mod
Labels: dependencies, go, size:S, lgtm

#4720 ci: bump kind to v0.25.0
  .github/workflows/build-x86-image.yaml
  yamls/kind.yaml.j2
Labels: ci, size:XS

#4694 [bugfix] Unable to correctly gc port group
  pkg/controller/gc.go
Labels: bug, size:M, lgtm

#4658 ci: add connectivity e2e test
  .github/workflows/build-x86-image.yaml
  Makefile
  test/e2e/connectivity/e2e_test.go
  test/e2e/framework/rpc/server.go
Labels: test, ci, size:L, lgtm

#4721 base: update ovn patches
  dist/images/Dockerfile.base
Labels: size:S, lgtm

#4723 ci: bump golangci-lint to v1.62.0
  .github/workflows/build-x86-image.yaml
  Makefile
  yamls/kwok.yaml
Labels: ci, size:S, lgtm

#4712 base: add ovs-sandbox
  Makefile
  dist/images/Dockerfile.base
  pkg/ovs/ovn-nb-suite_test.go
  pkg/ovs/ovs-vsctl_test.go
Labels: size:S, lgtm

#4719 The eip is not cleaned after eip is deleted (#4718)
  pkg/controller/vpc_nat_gw_eip.go
Labels: bug, need backport, vpc, size:XS, lgtm

#4722 [bugfix] Optimize gc method at port group and node
  pkg/controller/gc.go
  pkg/controller/node.go
Labels: bug, size:M, lgtm

#4724 lb-svc is compatible with dual stack subnets and supports attachment network for device plugin types
  pkg/controller/service.go
  pkg/controller/service_lb.go
  pkg/util/const.go
Labels: enhancement, size:M, lgtm

#4729 kube-ovn-cni will panic if cidr is invalid
  pkg/daemon/gateway.go
  pkg/daemon/gateway_linux.go
Labels: bug, need backport, size:M, lgtm

#4734 ut: fix duplicate lsp name
  pkg/ovs/ovn-nb-logical_switch_port_test.go
Labels: test, size:XS, lgtm

#4731 add adapt with nodes and networks for anp/banp egress rules
  Makefile
  pkg/controller/admin_network_policy.go
  yamls/adminnetworkpolicies-experimental.yaml
  yamls/baselineadminnetworkpolicies-experimental.yaml
Labels: feature, network policy, size:L, lgtm

#4737 fix vm ip lost and show more log about ip delete
  pkg/controller/pod.go
Labels: bug, size:M, lgtm

#4736 add loop check for tunnel nic
  pkg/daemon/controller.go
  pkg/daemon/ovs_linux.go
  pkg/daemon/ovs_windows.go
  pkg/util/const.go
Labels: feature, size:M, lgtm

#4717 vpc: add support for dedicated BFD LRP
  charts/kube-ovn/templates/kube-ovn-crd.yaml
  dist/images/Dockerfile.base
  dist/images/OpenBFDD-allow-ttl-254.patch
  dist/images/install.sh
  dist/images/kubectl-ko
  mocks/pkg/ovs/interface.go
  pkg/apis/kubeovn/v1/types.go
  pkg/apis/kubeovn/v1/zz_generated.deepcopy.go
  pkg/controller/vpc.go
  pkg/ovs/interface.go
  pkg/ovs/ovn-nb-ha_chassis_group.go
  pkg/ovs/ovn-nb-ha_chassis_group_test.go
  pkg/ovs/ovn-nb-logical_router_port.go
  pkg/ovs/ovn-nb-suite_test.go
  pkg/ovs/ovn.go
  test/anp/anp_test.go
  test/e2e/framework/vpc.go
Labels: vpc, size:XL, lgtm

#4749 update release script
  hack/release.sh
Labels: need backport, size:M, lgtm

#4750 split type definitions into separate files
  hack/update-codegen-docker.sh
  pkg/apis/kubeovn/v1/condition.go
  pkg/apis/kubeovn/v1/ip.go
  pkg/apis/kubeovn/v1/ippool.go
  pkg/apis/kubeovn/v1/iptables-dnat-rule.go
  pkg/apis/kubeovn/v1/iptables-eip.go
  pkg/apis/kubeovn/v1/iptables-fip-rule.go
  pkg/apis/kubeovn/v1/iptables-snat-rule.go
  pkg/apis/kubeovn/v1/ovn-dnat-rule.go
  pkg/apis/kubeovn/v1/ovn-eip.go
  pkg/apis/kubeovn/v1/ovn-fip.go
  pkg/apis/kubeovn/v1/ovn-snat-rule.go
  pkg/apis/kubeovn/v1/provider-network.go
  pkg/apis/kubeovn/v1/qos-policy.go
  pkg/apis/kubeovn/v1/register.go
  pkg/apis/kubeovn/v1/security-group.go
  pkg/apis/kubeovn/v1/status.go
  pkg/apis/kubeovn/v1/subnet.go
  pkg/apis/kubeovn/v1/switch-lb-rule.go
  pkg/apis/kubeovn/v1/types.go
  pkg/apis/kubeovn/v1/vip.go
  pkg/apis/kubeovn/v1/vlan.go
  pkg/apis/kubeovn/v1/vpc-dns.go
  pkg/apis/kubeovn/v1/vpc-nat-gateway.go
  pkg/apis/kubeovn/v1/vpc.go
  pkg/apis/kubeovn/v1/zz_generated.deepcopy.go
  pkg/controller/qos_policy.go
  pkg/controller/security_group.go
  pkg/controller/vpc_dns.go
  pkg/controller/vpc_nat_gateway.go
  pkg/controller/vpc_nat_gw_eip.go
  pkg/ovs/ovn-nb-acl.go
  pkg/ovs/ovn-nb-acl_test.go
  test/e2e/framework/iptables-eip.go
  test/e2e/framework/ovn-eip.go
  test/e2e/framework/ovn-fip.go
  test/e2e/framework/security-group.go
  test/e2e/framework/switch-lb-rule.go
  test/e2e/framework/vpc-nat-gateway.go
  test/e2e/iptables-vpc-nat-gw/e2e_test.go
  test/e2e/kube-ovn/switch_lb_rule/switch_lb_rule.go
  test/e2e/vip/e2e_test.go
Labels: refactor, size:XXL, lgtm

#4746 ci: add release-1.13 to workflows
  .github/workflows/build-kube-ovn-base-dpdk.yaml
  .github/workflows/build-kube-ovn-base.yaml
  .github/workflows/scheduled-e2e.yaml
Labels: ci, size:S, lgtm

#4751 add observed generation into condition
  pkg/apis/kubeovn/v1/condition.go
Labels: size:L, lgtm

#4744 remove capability SYS_MODULE
  charts/kube-ovn/templates/ovncni-ds.yaml
  charts/kube-ovn/templates/ovsovn-ds.yaml
  dist/images/Dockerfile.base
  dist/images/install.sh
  dist/images/start-ovs.sh
  test/e2e/framework/iptables/iptables.go
Labels: size:M, lgtm

#4762 skip node local dns ip ct 1.12
  dist/images/Dockerfile.base
  mocks/pkg/ovs/interface.go
  pkg/controller/config.go
  pkg/controller/controller.go
  pkg/ovs/interface.go
  pkg/ovs/ovn-nb_global.go
  pkg/util/net.go
Labels: size:M, lgtm

#4770 bump dpdk base image to ubuntu 24.04
  dist/images/Dockerfile.base-dpdk
Labels: dependencies, size:XS, lgtm

#4771 bump k8s to v1.30.7
  .github/workflows/build-x86-image.yaml
  dist/images/Dockerfile.base
  dist/images/go-deps/download-go-deps.sh
  go.mod
  go.sum
  yamls/kind.yaml.j2
Labels: dependencies, size:L, lgtm

#4773 add kubevirt live migration optimize
  charts/kube-ovn/templates/controller-deploy.yaml
  charts/kube-ovn/templates/ovn-CR.yaml
  charts/kube-ovn/values.yaml
  dist/images/install.sh
  go.mod
  go.sum
  pkg/controller/config.go
  pkg/controller/controller.go
  pkg/controller/kubevirt.go
  pkg/controller/pod.go
  pkg/util/const.go
Labels: enhancement, size:L, lgtm
