Repository kubeovn/kube-ovn, pull requests merged in 2025-09, with the labels that each got.

#5671 crd: fix unrecognized format int32/int64
  charts/kube-ovn-v2/crds/kube-ovn-crd.yaml
  charts/kube-ovn/templates/kube-ovn-crd.yaml
  dist/images/install.sh
Labels: bug, size:L, lgtm

#5676 fix e2e for stuck when delete subnet
  test/e2e/kube-ovn/subnet/subnet.go
Labels: test, size:XS

#5677 Fix e2e
  test/e2e/kube-ovn/subnet/subnet.go
Labels: size:XS

#5678 fix e2e
  test/e2e/kube-ovn/subnet/subnet.go
Labels: test, size:XS

#5698 controller: fix marking ip resource as reserved incorrectly
  pkg/controller/ip.go
Labels: bug, need backport, size:M, lgtm

#5618 Feat: Added non primary cni mode support for Kube-OVN
  charts/kube-ovn-v2/templates/controller/controller-deployment.yaml
  charts/kube-ovn-v2/values.yaml
  charts/kube-ovn/templates/controller-deploy.yaml
  charts/kube-ovn/values.yaml
  dist/images/vpcnatgateway/nat-gateway.sh
  pkg/controller/config.go
  pkg/controller/endpoint_slice.go
  pkg/controller/pod.go
  pkg/controller/vpc_nat_gateway.go
  pkg/util/const.go
  pkg/util/network_attachment.go
Labels: feature, vpc, size:L

#5726 fix: e2e change test url to google.com
  test/e2e/anp-domain/e2e_test.go
Labels: test, size:M, lgtm

#5729 controller: fix ip allocation from IPPools
  .github/workflows/build-x86-image.yaml
  go.mod
  go.sum
  makefiles/e2e.mk
  pkg/controller/pod.go
  test/e2e/kube-ovn/ipam/ipam.go
Labels: bug, need backport, dependencies, go, size:L, lgtm

#5731 ipam: fix allocating from ippool
  pkg/controller/pod.go
  test/e2e/kube-ovn/ipam/ipam.go
Labels: bug, need backport, size:M, lgtm

#5733 fix: subnet status should update after ip created
  pkg/controller/ip.go
  pkg/controller/vpc_nat_gw_eip.go
Labels: bug, size:M, lgtm

#5735 controller: fix lsp not deleted in gc
  go.mod
  mocks/pkg/ovs/interface.go
  pkg/controller/gc.go
  pkg/ovs/interface.go
  pkg/ovs/ovn-nb-acl.go
  pkg/ovs/ovn-nb-acl_test.go
  pkg/ovs/ovn-nb-dhcp_options.go
  pkg/ovs/ovn-nb-dhcp_options_test.go
  pkg/ovs/ovn-nb-logical_switch_port.go
  pkg/ovs/ovn-nb-logical_switch_port_test.go
  pkg/ovs/ovn-nb.go
  pkg/ovs/ovn.go
  pkg/ovsdb/client/client.go
Labels: bug, need backport, size:L, lgtm
