Repository kubeovn/kube-ovn, pull requests merged in 2025-03, with the labels that each got.

#5038 kubectl-ko: fix conntrack state
  dist/images/kubectl-ko
  test/e2e/kube-ovn/kubectl-ko/kubectl-ko.go
Labels: bug, need backport, size:L, lgtm

#5065 add copy of the kubevirt informer from upstream
  go.mod
  go.sum
  pkg/controller/controller.go
  pkg/controller/kubevirt.go
  pkg/informer/kubevirt.go
Labels: go, size:L

#5066 remove genev_sys_6081 when uninstall kube-ovn
  dist/images/uninstall.sh
Labels: size:XS

#5031 Potential fix to #5028
  pkg/controller/namespace.go
Labels: size:XS

#5069 feat: Make Kube-OVN namespace configurable with default value
  dist/images/kubectl-ko
Labels: feature, size:XS

#5071 feat: Improve subnet and VPC finalizer handling
  pkg/controller/subnet.go
  pkg/controller/vpc.go
  test/e2e/iptables-vpc-nat-gw/e2e_test.go
  test/e2e/kube-ovn/pod/vpc_pod_probe.go
Labels: enhancement, vpc, size:M

#5076 bump go to 1.24.1
  .github/workflows/build-x86-image.yaml
  dist/images/Dockerfile.base
  dist/images/go-deps/download-go-deps.sh
  go.mod
  go.sum
  hack/update-codegen-docker.sh
  test/anp/go.mod
  test/anp/go.sum
  yamls/kind.yaml.j2
Labels: go, size:L, lgtm

#5077 bump go to 1.23.7
  .github/workflows/build-x86-image.yaml
  dist/images/Dockerfile.base
  dist/images/go-deps/download-go-deps.sh
  go.mod
  go.sum
  test/anp/go.mod
  test/anp/go.sum
  yamls/kind.yaml.j2
Labels: dependencies, go, size:L, lgtm

#5080 bump kubevirt to v1.5.0
  .github/workflows/build-x86-image.yaml
  Makefile
  go.mod
  go.sum
Labels: dependencies, size:S, lgtm

#5070 [fix] When the Nat-gw pod container restarts unexpectedly, trigger nat-gw statefulset restart to restore the nat-gw pod configuration
  pkg/controller/pod.go
  pkg/controller/vpc_nat_gateway.go
  pkg/util/const.go
Labels: bug, size:M

#5072 [fix] When the Nat-gw pod container restarts unexpectedly, trigger nat-gw statefulset restart to restore the nat-gw pod configuration
  pkg/controller/pod.go
  pkg/controller/vpc_nat_gateway.go
  pkg/util/const.go
Labels: bug, size:M

#5042 cni-server: check ipv6 dadfailed flag
  Makefile
  pkg/daemon/handler.go
  pkg/daemon/ovs_linux.go
  pkg/daemon/ovs_windows.go
  test/e2e/kube-ovn/underlay/underlay.go
Labels: feature, go, size:L, lgtm

#5049 bind to pod ips when env variable ENABLE_BIND_LOCAL_IP is set to true
  cmd/controller/controller.go
  cmd/daemon/cniserver.go
  cmd/ovn_monitor/ovn_monitor.go
  pkg/daemon/config.go
  pkg/daemon/gateway_linux.go
  pkg/daemon/tproxy_linux.go
  pkg/util/net.go
  pkg/util/net_test.go
  test/e2e/kube-ovn/pod/vpc_pod_probe.go
  test/e2e/security/e2e_test.go
Labels: test, need backport, go, size:L, lgtm

#5083 mc build remove cilium e2e
  .github/workflows/build-x86-image.yaml
Labels: ci, size:L

#5084 fix mc
  .github/workflows/build-x86-image.yaml
  .github/workflows/scheduled-e2e.yaml
Labels: github_actions, size:M

#5088 fix: egress network policy not work, when no pod hit matchlabel
  pkg/controller/network_policy.go
Labels: bug, network policy, size:S, lgtm

#5089 fix: egress network policy not work, when no pod hit matchlabel
  pkg/controller/network_policy.go
Labels: bug, network policy, size:S

#5095 fix cve
  .github/workflows/build-x86-image.yaml
  dist/images/Dockerfile.base
  dist/images/go-deps/download-go-deps.sh
  go.mod
  go.sum
Labels: security, size:M

#5096 build(deps): bump gopkg.in/k8snetworkplumbingwg/multus-cni.v4
  .github/workflows/build-windows.yaml
  .github/workflows/build-x86-image.yaml
  Makefile
  go.mod
  go.sum
Labels: dependencies, size:M, lgtm

#5097 bump golangci-lint to v2.0.1
  .github/workflows/build-x86-image.yaml
  .golangci.yml
  pkg/controller/network_policy.go
  pkg/controller/pod.go
  pkg/controller/subnet.go
  pkg/controller/vpc.go
  pkg/controller/vpc_dns.go
  pkg/controller/vpc_nat_gateway.go
  pkg/daemon/config_linux.go
  pkg/daemon/gateway_linux.go
  pkg/daemon/ovs_linux.go
  pkg/daemon/tproxy_linux.go
  pkg/internal/big_int.go
  pkg/ovn_ic_controller/ovn_ic_controller.go
  pkg/ovnmonitor/util.go
  pkg/ovs/ovn-nb-acl.go
  pkg/ovs/ovn-nb-address_set.go
  pkg/ovs/ovn-nb-dhcp_options.go
  pkg/ovs/ovn-nb-load_balancer.go
  pkg/ovs/ovn-nb-load_balancer_health_check.go
  pkg/ovs/ovn-nb-load_balancer_test.go
  pkg/ovs/ovn-nb-logical_router.go
  pkg/ovs/ovn-nb-logical_router_policy.go
  pkg/ovs/ovn-nb-logical_router_port.go
  pkg/ovs/ovn-nb-logical_router_route.go
  pkg/ovs/ovn-nb-logical_router_test.go
  pkg/ovs/ovn-nb-logical_switch.go
  pkg/ovs/ovn-nb-logical_switch_port_test.go
  pkg/ovs/ovn-nb-nat.go
  pkg/ovs/ovn-nb-port_group.go
  pkg/ovs/ovn-nb_global.go
  pkg/ovs/ovn-sb-chassis.go
  pkg/ovs/ovn-sb-chassis_test.go
  pkg/pinger/ovn.go
  pkg/pinger/ping.go
  pkg/util/arp.go
  pkg/util/net.go
  pkg/webhook/webhook.go
  test/e2e/connectivity/e2e_test.go
  test/e2e/framework/daemonset.go
  test/e2e/framework/deployment.go
  test/e2e/framework/pod.go
  test/e2e/framework/virtual-machine.go
  test/e2e/kube-ovn/subnet/subnet.go
  test/e2e/kube-ovn/underlay/underlay.go
  test/e2e/webhook/pod/pod.go
  test/server/server.go
Labels: go, size:L, lgtm

#5104 build(deps): bump github.com/docker/docker
  .github/workflows/build-x86-image.yaml
  go.mod
  go.sum
Labels: size:M

#5105 bump go to 1.23.7
  dist/images/Dockerfile.base
  dist/images/go-deps/download-go-deps.sh
  go.mod
  go.sum
Labels: security, size:M

#5106 feat(controller): skip appending VM LSPs if default Multus network is…
  pkg/controller/gc.go
Labels: enhancement, size:S

#5107 fix content of kubectl-ko
  dist/images/install.sh
  dist/images/kubectl-ko
Labels: size:L

#5111 base: update ovs patches
  dist/images/Dockerfile.base
  dist/images/Dockerfile.base-dpdk
Labels: need backport, size:M
