Repository kubeovn/kube-ovn, pull requests merged in 2025-08, with the labels that each got.

#5536 update ns
  charts/kube-ovn/templates/kube-ovn-crd.yaml
  dist/images/install.sh
Labels: chart, size:XS

#5546 fix nat-gateway arping
  dist/images/vpcnatgateway/nat-gateway.sh
Labels: bug, size:XS, lgtm

#5549 chore: add verbose guard to endpoint update
  pkg/controller/endpoint.go
Labels: size:XS

#5551 do not handle update external vpcs
  charts/kube-ovn-v2/values.yaml
  charts/kube-ovn/values.yaml
  dist/images/install.sh
  pkg/controller/config.go
  pkg/controller/vpc.go
Labels: bug, need backport, vpc, size:S

#5554 fix(helm): static master ips wouldn't work anymore
  charts/kube-ovn-v2/templates/_helpers.tpl
  charts/kube-ovn/templates/_helpers.tpl
Labels: bug, need backport, chart, size:XS, lgtm

#5552 tolerate duplicate ACLs
  pkg/ovs/ovn-nb-acl.go
Labels: bug, need backport, size:M

#5555 Refactor Makefile structure
  Makefile
  makefiles/build.mk
  makefiles/e2e.mk
  makefiles/kind.mk
  makefiles/talos.mk
  makefiles/ut.mk
Labels: refactor, size:S, lgtm

#5558 skip mv if config file already exists
  cmd/daemon/cniserver.go
Labels: bug, need backport, go, size:XS

#5565 Fix the problem that if available ip is 0 but there is a value in exc…
  pkg/controller/pod.go
Labels: bug, size:M

#5567 Fix the problem that if available ip is 0 but there is a value in exc…
  pkg/controller/pod.go
Labels: bug, size:M

#5568 Fix the problem that if available ip is 0 but there is a value in exc…
  pkg/controller/pod.go
Labels: bug, size:M

#5569 vm static ip validate should use vm name
  pkg/webhook/static_ip.go
Labels: bug, go, size:S, lgtm

#5591 remove lsp when gw nodes change
  pkg/controller/external_gw.go
Labels: bug, size:XS

#5585 reduce probability of maps conncurrent iteration and write
  pkg/controller/service.go
Labels: bug, need backport, size:S

#5595 fix dpdk base image
  dist/images/Dockerfile.base-dpdk
Labels: bug, size:S, lgtm

#5534 simple vip
  charts/kube-ovn-v2/crds/kube-ovn-crd.yaml
  charts/kube-ovn/templates/kube-ovn-crd.yaml
  dist/images/install.sh
  pkg/controller/vip.go
Labels: feature, size:M, lgtm

#5606 ci: ignore goveralls failure
  .github/workflows/build-x86-image.yaml
Labels: ci, need backport, size:XS

#5195 base: bump dpdk to 24.11.2 (LTS)
  dist/images/Dockerfile.base-dpdk
Labels: dependencies, dpdk, size:XS, lgtm

#5182 bump k8s to v1.33.4
  .golangci.yml
  dist/images/Dockerfile.base
  dist/images/go-deps/download-go-deps.sh
  go.mod
  go.sum
  hack/update-codegen-docker.sh
  makefiles/talos.mk
  pkg/client/clientset/versioned/fake/clientset_generated.go
  pkg/client/clientset/versioned/typed/kubeovn/v1/kubeovn_client.go
  pkg/client/informers/externalversions/kubeovn/v1/ip.go
  pkg/client/informers/externalversions/kubeovn/v1/ippool.go
  pkg/client/informers/externalversions/kubeovn/v1/iptablesdnatrule.go
  pkg/client/informers/externalversions/kubeovn/v1/iptableseip.go
  pkg/client/informers/externalversions/kubeovn/v1/iptablesfiprule.go
  pkg/client/informers/externalversions/kubeovn/v1/iptablessnatrule.go
  pkg/client/informers/externalversions/kubeovn/v1/ovndnatrule.go
  pkg/client/informers/externalversions/kubeovn/v1/ovneip.go
  pkg/client/informers/externalversions/kubeovn/v1/ovnfip.go
  pkg/client/informers/externalversions/kubeovn/v1/ovnsnatrule.go
  pkg/client/informers/externalversions/kubeovn/v1/providernetwork.go
  pkg/client/informers/externalversions/kubeovn/v1/qospolicy.go
  pkg/client/informers/externalversions/kubeovn/v1/securitygroup.go
  pkg/client/informers/externalversions/kubeovn/v1/subnet.go
  pkg/client/informers/externalversions/kubeovn/v1/switchlbrule.go
  pkg/client/informers/externalversions/kubeovn/v1/vip.go
  pkg/client/informers/externalversions/kubeovn/v1/vlan.go
  pkg/client/informers/externalversions/kubeovn/v1/vpc.go
  pkg/client/informers/externalversions/kubeovn/v1/vpcdns.go
  pkg/client/informers/externalversions/kubeovn/v1/vpcegressgateway.go
  pkg/client/informers/externalversions/kubeovn/v1/vpcnatgateway.go
  pkg/daemon/controller_linux.go
  pkg/informer/kubevirt.go
  test/anp/go.mod
  test/anp/go.sum
  test/e2e/framework/http/http.go
  test/e2e/framework/statefulset.go
Labels: dependencies, go, network policy, size:XL, lgtm

#5624 e2e: skip testcases of ServiceCIDR and IPAddress API for versions prior to 1.13
  makefiles/e2e.mk
Labels: test, size:XS

#5603 fix ovnipsec failed when kube-ovn-cni restart
  charts/kube-ovn-v2/templates/agent/agent-daemonset.yaml
  charts/kube-ovn-v2/values.yaml
  charts/kube-ovn/templates/ovncni-ds.yaml
  charts/kube-ovn/values.yaml
Labels: bug, size:XS, lgtm

#5622 Fix mac conflict 1.11
  pkg/controller/subnet.go
  pkg/ipam/ipam.go
  pkg/ipam/subnet.go
  pkg/ovs/ovn-nb-logical_router_port.go
  pkg/ovs/ovn-nbctl-legacy.go
  pkg/util/net.go
Labels: bug, go, size:M

#5631 fix cve
  .trivyignore
  dist/images/Dockerfile.base
  go.mod
  go.sum
Labels: security, size:S, lgtm

#5646 fix bug for issuse #5597: when slr update, the same vip will be delete too
  pkg/controller/service.go
Labels: bug, size:S, lgtm

#5648 Deep copy informer objects before mutation
  pkg/controller/ip.go
  pkg/controller/service.go
  pkg/controller/switch_lb_rule.go
  pkg/controller/vip.go
  pkg/controller/vpc_dns.go
  pkg/daemon/handler.go
Labels: bug, size:M, lgtm, codex

#5658 release address when acquire a new static address
  pkg/ipam/subnet.go
  pkg/ipam/subnet_test.go
Labels: bug, size:L
