Repository kubeovn/kube-ovn, pull requests merged in 2025-07, with the labels that each got.

#5409 mock: generate code using go tool command
  go.mod
  hack/mockgen.sh
  mocks/doc.go
  mocks/pkg/ovs/interface.go
Labels: go, size:M, lgtm

#5416 upgrade ovn chart name
  charts/kube-ovn-v2/Chart.yaml
Labels: chart, size:XS, lgtm

#5415 change kube-ovn chartname to kube-ovn-v2
  charts/kube-ovn-v2/Chart.yaml
Labels: chart, size:XS, lgtm

#5421 cni-server: fix inserting and deleting iptables rules
  Makefile
  e2e.mk
  kind.mk
  pkg/daemon/gateway_linux.go
  talos.mk
Labels: bug, need backport, size:L, lgtm

#5423 fix parsing resolv.conf when systemd-resolved is running on the host
  pkg/daemon/exporter_metric.go
Labels: bug, need backport, size:XS, lgtm

#5425 kubectl-ko: replace endpoint with endpointslice
  dist/images/kubectl-ko
Labels: need backport, size:XS, lgtm

#5386 Add network attachment informer to controller
  charts/kube-ovn-v2/templates/rbac/ovn-CR.yaml
  charts/kube-ovn/templates/ovn-CR.yaml
  dist/images/install.sh
  pkg/controller/controller.go
  pkg/controller/network_attachment.go
  pkg/controller/pod.go
  pkg/controller/service.go
  pkg/controller/service_lb.go
  pkg/controller/subnet.go
  pkg/controller/vpc_egress_gateway.go
Labels: performance, size:L

#5426 fix setting LR option always_learn_from_arp_request
  pkg/controller/subnet.go
  pkg/controller/vpc.go
Labels: bug, need backport, size:M, lgtm

#5437 replace Endpoint with EndpointSlice
  dist/images/kubectl-ko
  dist/images/ovn-is-leader.sh
  pkg/ovn_leader_checker/ovn.go
Labels: enhancement, size:M, lgtm

#5429 ci: increase timeout of Multus-CNI conformance e2e
  .github/workflows/build-x86-image.yaml
  e2e.mk
Labels: ci, size:XS

#5365 Use cert-manager to issue certificates for IPSec
  .github/workflows/build-x86-image.yaml
  charts/kube-ovn-v2/templates/agent/agent-clusterrole.yaml
  charts/kube-ovn-v2/templates/agent/agent-clusterrolebinding.yaml
  charts/kube-ovn/templates/ovn-CR.yaml
  charts/kube-ovn/templates/ovn-CRB.yaml
  cmd/daemon/cniserver.go
  dist/images/install.sh
  e2e.mk
  go.mod
  go.sum
  kind.mk
  pkg/controller/config.go
  pkg/controller/controller.go
  pkg/daemon/config.go
  pkg/daemon/controller.go
  pkg/daemon/ipsec.go
  test/e2e/ipsec-cert-mgr/e2e_test.go
  yamls/ipsec-certs.yaml
Labels: feature, size:XXL

#5441 bump go to 1.23.11
  dist/images/Dockerfile.base
  go.mod
  go.sum
  test/anp/go.mod
  test/anp/go.sum
Labels: dependencies, go, size:L

#5447 remove already has debs
  dist/images/Dockerfile.base
  dist/images/Dockerfile.base-dpdk
Labels: size:XS, lgtm

#5472 kubectl-ko: collect information about ipsec and xfrm
  dist/images/kubectl-ko
Labels: need backport, size:L, lgtm

#5444 controller: fix setting LR options on initialization
  pkg/controller/init.go
Labels: bug, need backport, size:S, lgtm

#5417 chart version equal to 1.0
  charts/kube-ovn-v2/Chart.yaml
Labels: chart, size:XS, lgtm

#5488 fix missing rbac rule for sa ovn-ovs
  charts/kube-ovn-v2/templates/rbac/ovn-CR.yaml
  charts/kube-ovn/templates/ovn-CR.yaml
  dist/images/install.sh
Labels: bug, need backport, chart, size:S, lgtm

#5445 some fixes in ipsec backed with cert-manager
  .gitignore
  Makefile
  dist/images/generate-ssl.sh
  dist/images/install.sh
  kind.mk
  pkg/daemon/config.go
  pkg/daemon/controller.go
  pkg/daemon/ipsec.go
  pkg/daemon/ipsec_windows.go
  yamls/ipsec-certs.yaml
Labels: bug, size:L

#5414 feat(endpoint_slice): refactor and support arbitrary providers
  pkg/controller/endpoint_slice.go
  pkg/controller/endpoint_slice_test.go
  pkg/controller/switch_lb_rule.go
  pkg/controller/switch_lb_rule_test.go
  test/e2e/framework/framework.go
  test/e2e/kube-ovn/switch_lb_rule/switch_lb_rule.go
Labels: feature, refactor, size:XL

#5493 fix: only addOrUpdateSubnetQueue if the GatewayType is distributed instead of if it's not centralized
  pkg/controller/node.go
Labels: bug, need backport, size:XS

#5500 chart: fix node selector
  charts/kube-ovn-v2/templates/ic/ic-controller-deploy.yaml
  charts/kube-ovn/templates/ic-controller-deploy.yaml
Labels: need backport, chart, size:XS, lgtm

#5501 fix: ip/vpc are not deleted by helm uninstall
  charts/kube-ovn-v2/templates/hooks/post-delete-hook.yaml
  charts/kube-ovn/templates/post-delete-hook.yaml
  dist/images/remove-finalizer.sh
  dist/images/remove-subnet-finalizer.sh
Labels: bug, need backport, chart, size:M, lgtm

#5504 panic install if labeled nodes are not found
  charts/kube-ovn-v2/templates/_helpers.tpl
  charts/kube-ovn/templates/_helpers.tpl
Labels: chart, size:XS, lgtm

#5510 fix concurrent map race
  pkg/controller/controller.go
  pkg/controller/subnet.go
  pkg/controller/vpc.go
Labels: bug, need backport, size:M, lgtm

#5511 fix NB Global not updated after OVN IC is disabled
  pkg/ovn_ic_controller/ovn_ic_controller.go
  pkg/ovs/ovn-nb_global.go
Labels: bug, need backport, size:S, lgtm

#5499 delay timer is incorrect
  pkg/controller/pod.go
Labels: bug, size:XS, lgtm
