Repository kubeovn/kube-ovn, pull requests merged in 2025-01, with the labels that each got.

#4892 remove enable-live-migration-optimize templately
  charts/kube-ovn/templates/controller-deploy.yaml
  dist/images/install.sh
Labels: size:XS, lgtm

#4893 e2e: fix duplicate random cidr
  test/e2e/framework/util.go
Labels: test, size:L, lgtm

#4886 fix: kube-ovn-controller cannot be ready when ENABLE_METRICS is false
  charts/kube-ovn/templates/controller-deploy.yaml
  charts/kube-ovn/templates/monitor-deploy.yaml
  charts/kube-ovn/templates/ovncni-ds.yaml
  cmd/controller/controller.go
  cmd/daemon/cniserver.go
  cmd/health_check/health_check.go
  cmd/ovn_monitor/ovn_monitor.go
  cmd/speaker/speaker.go
  dist/images/install.sh
  pkg/ovnmonitor/config.go
  pkg/speaker/config.go
Labels: bug, size:L, lgtm

#4897 fix: go mod tidy
  go.mod
  go.sum
Labels: dependencies, size:XS, lgtm

#4896 Increase code specification and readability in vxlan nic name and qos
  cmd/daemon/init.go
  pkg/daemon/controller_linux.go
Labels: enhancement, size:S, lgtm

#4904 base: bump cni plugins to v1.6.2
  dist/images/Dockerfile.base
  dist/images/go-deps/download-go-deps.sh
  go.mod
  go.sum
Labels: dependencies, size:S, lgtm

#4903 ipam: check subnet's available ipv6 address count
  pkg/controller/pod.go
Labels: need backport, size:M, lgtm

#4910 e2e: do not check mac annotation for versions prior to v1.13
  test/e2e/multus/e2e_test.go
Labels: test, size:XS, lgtm

#4902 bump go to 1.22.10
  .trivyignore
  cmd/controller/controller.go
  cmd/daemon/cniserver.go
  cmd/ovn_monitor/ovn_monitor.go
  cmd/pinger/pinger.go
  cmd/speaker/speaker.go
  cmd/webhook/server.go
  dist/images/Dockerfile
  dist/images/Dockerfile.base
  dist/images/Dockerfile.debug
  dist/images/go-deps/download-go-deps.sh
  go.mod
  go.sum
  pkg/controller/namespace.go
  pkg/daemon/ovs.go
  pkg/daemon/server.go
  pkg/ovs/ovs-vsctl.go
  pkg/util/network_attachment.go
Labels: go, size:M, lgtm

#4909 subnet: exclude excludeIPs in available/using ips
  pkg/controller/subnet.go
Labels: size:M, lgtm

#4915 cni-server: set node NetworkUnavailable condition after join subnet gateway check
  charts/kube-ovn/templates/ovn-CR.yaml
  dist/images/install.sh
  pkg/daemon/init.go
  pkg/daemon/ovs_linux.go
  pkg/daemon/ovs_windows.go
  pkg/util/k8s.go
Labels: need backport, go, size:M, lgtm

#4918 replace reflect.DeepEqual with slices.Equal and maps.Equal
  pkg/controller/external_gw.go
  pkg/controller/ip.go
  pkg/controller/ippool.go
  pkg/controller/kubevirt.go
  pkg/controller/namespace.go
  pkg/controller/network_policy.go
  pkg/controller/pod.go
  pkg/controller/subnet.go
  pkg/controller/vip.go
  pkg/controller/vpc.go
  pkg/controller/vpc_nat_gateway.go
  pkg/daemon/gateway_linux.go
  pkg/ovn_ic_controller/ovn_ic_controller.go
  pkg/ovs/ovn-nb-logical_switch_port.go
  pkg/ovs/ovn-nb_global.go
  pkg/util/net_test.go
  pkg/util/slice_test.go
  pkg/util/strings_test.go
Labels: refactor, size:L, lgtm

#4917 controller: check condition NodeNetworkUnavailable when determining whether node is ready
  pkg/controller/node.go
Labels: need backport, size:S, lgtm

#4921 remove dup func and fix ut
  mocks/pkg/ovs/interface.go
  pkg/controller/node.go
  pkg/ovs/interface.go
  pkg/ovs/ovn-nb-suite_test.go
  pkg/ovs/ovn-sb-chassis.go
  pkg/ovs/ovn-sb-chassis_test.go
Labels: test, size:L, lgtm

#4895 [performance] in large-scale clusters, init node router policy too slow
  mocks/pkg/ovs/interface.go
  pkg/controller/init.go
  pkg/controller/vpc.go
  pkg/ovs/interface.go
  pkg/ovs/ovn-nb-address_set.go
  pkg/ovs/ovn-nb-address_set_test.go
  pkg/ovs/ovn-nb-logical_router_policy.go
  pkg/ovs/ovn-nb-logical_router_policy_test.go
  pkg/ovs/ovn-nb-logical_router_route.go
  pkg/ovs/ovn-nb-logical_router_route_test.go
  pkg/ovs/ovn-nb-suite_test.go
  pkg/ovs/ovn.go
Labels: performance, size:XXL

#4928 fix log
  pkg/controller/vpc_nat_gw_eip.go
Labels: size:XS

#4930 bump k8s to v1.32.1
  dist/images/Dockerfile.base
  dist/images/go-deps/download-go-deps.sh
  go.mod
  go.sum
  test/anp/go.mod
  test/anp/go.sum
Labels: dependencies, size:L, lgtm

#4912 controller: fix gateway nodes check
  pkg/controller/node.go
Labels: bug, vpc, size:M, lgtm

#4935 bump go to 1.23.5
  .github/workflows/build-x86-image.yaml
  Makefile
  dist/images/Dockerfile.base
  go.mod
  hack/update-codegen-docker.sh
  test/anp/go.mod
  yamls/speaker.yaml
  yamls/vpc-configmap.yaml
  yamls/webhook.yaml
Labels: go, size:M, lgtm

#4936 ci: build arm64 images on arm64 hosted runners
  .github/workflows/build-arm64-image.yaml
  .github/workflows/build-kube-ovn-base.yaml
Labels: ci, need backport, size:M, lgtm

#4941 Add Rackspace as a user
  USERS.md
Labels: docs, size:XS
