Repository kubeovn/kube-ovn, pull requests merged in 2025-02, with the labels that each got.

#4961 bump go to 1.23.6
  dist/images/Dockerfile.base
  go.mod
  go.sum
Labels: dependencies, go, size:S

#4963 bump go to 1.23.6
  dist/images/Dockerfile.base
  dist/images/go-deps/download-go-deps.sh
  go.mod
  go.sum
  hack/update-codegen-docker.sh
  test/anp/go.mod
  test/anp/go.sum
Labels: go, size:L

#4965 bump go to 1.22.12
  dist/images/Dockerfile.base
  dist/images/go-deps/download-go-deps.sh
  go.mod
  go.sum
Labels: dependencies, go, size:M

#4962 bump go to 1.23.6
  dist/images/Dockerfile.base
  go.mod
  hack/update-codegen-docker.sh
  test/anp/go.mod
  test/anp/go.sum
Labels: go, size:S

#4967 controller: consider StatefulSet's start ordinal
  pkg/controller/pod.go
  test/e2e/framework/statefulset.go
  test/e2e/kube-ovn/ipam/ipam.go
Labels: bug, need backport, size:M

#4968 bump github.com/hashicorp/yamux from v0.1.1 to v0.1.2
  go.mod
  go.sum
Labels: security, need backport, dependencies, size:XS

#4945 use httpGet as liveness/readiness probe method
  Makefile
  charts/kube-ovn/templates/controller-deploy.yaml
  charts/kube-ovn/templates/monitor-deploy.yaml
  charts/kube-ovn/templates/ovncni-ds.yaml
  cmd/cmdmain.go
  cmd/controller/controller.go
  cmd/daemon/cniserver.go
  cmd/health_check/health_check.go
  cmd/ovn_monitor/ovn_monitor.go
  dist/images/Dockerfile
  dist/images/install.sh
  go.mod
  pkg/metrics/server.go
  pkg/util/health_check.go
Labels: enhancement, need backport, size:L

#4969 fix: kube-ovn-cni always dump-flows br-provider per period
  pkg/daemon/controller_linux.go
Labels: bug, size:XS, lgtm

#4972 fix: kube-ovn-cni always dump-flows br-provider per period
  pkg/daemon/controller.go
Labels: bug, size:XS

#4971 fix: kube-ovn-cni always dump-flows br-provider per period
  pkg/daemon/controller_linux.go
Labels: bug, size:XS

#4860 refactor: remove duplicated iptables subnet forward rules
  pkg/daemon/gateway_linux.go
Labels: performance, refactor, size:M, lgtm

#4978 Revert "refactor: remove duplicated iptables subnet forward rules"
  pkg/daemon/gateway_linux.go
Labels: size:M

#4977 e2e: fix ip conflict
  test/e2e/kube-ovn/ipam/ipam.go
Labels: test, size:S, lgtm

#4982 ci: bump cilium to v1.17.0
  .github/workflows/build-windows.yaml
  Makefile
  e2e.mk
Labels: ci, size:S, lgtm

#4983 bump golang.org/x/tools from v0.29.0 to v0.30.0
  go.mod
  go.sum
Labels: dependencies, go, size:XS, lgtm

#4984 Bump go bgp to fix CVE
  dist/images/Dockerfile.base
  dist/images/go-deps/download-go-deps.sh
  go.mod
  go.sum
Labels: security, go, size:M

#4976 fix security groups changed when vm is shut down
  pkg/controller/pod.go
  pkg/util/slice.go
  pkg/util/slice_test.go
Labels: bug, size:M, lgtm

#4988 e2e: skip some test cases for versions prior to v1.14 in cilium chaining
  e2e.mk
Labels: test, ci, size:XS

#4980 fix superfluous response.WriteHeader
  pkg/util/health_check.go
Labels: bug, need backport, go, size:XS

#4979 iptables: improve performance for updating subnet metrics rules
  pkg/daemon/gateway_linux.go
Labels: performance, size:L, lgtm

#4986 bump go to 1.24.0
  .github/workflows/build-x86-image.yaml
  dist/images/Dockerfile.base
  go.mod
  hack/update-codegen-docker.sh
  test/anp/go.mod
  test/anp/go.sum
Labels: go, size:S, lgtm

#4994 controller: respect named ports of restartable init containers
  pkg/controller/pod.go
Labels: network policy, size:S, lgtm

#4992 bump k8s to v1.32.2
  .github/workflows/build-x86-image.yaml
  .github/workflows/scheduled-e2e.yaml
  dist/images/Dockerfile.base
  dist/images/go-deps/download-go-deps.sh
  go.mod
  go.sum
  test/anp/go.mod
  test/anp/go.sum
  yamls/kind.yaml.j2
Labels: dependencies, size:L, lgtm

#4996 bump k8s to v1.31.6
  go.mod
  go.sum
Labels: dependencies, size:M

#5004 ignore trivy
  .trivyignore
Labels: size:XS

#5006 fix cve
  dist/images/Dockerfile.base
Labels: security, size:XS

#5014 fix logging in ovn lr/ls gc
  mocks/pkg/ovs/interface.go
  pkg/controller/gc.go
  pkg/ovs/interface.go
  pkg/ovs/ovn-nb-logical_router.go
  pkg/ovs/ovn-nb-logical_router_test.go
  pkg/ovs/ovn-nb-logical_switch.go
  pkg/ovs/ovn-nb-logical_switch_test.go
  pkg/ovs/ovn-nb-suite_test.go
  pkg/ovs/ovn.go
Labels: go, size:L, lgtm

#5017 build(deps): bump github.com/containernetworking/plugins from v1.6.0 to v1.6.2
  go.mod
  go.sum
  test/e2e/framework/docker/container.go
  test/e2e/framework/kind/kind.go
Labels: dependencies, go, size:L

#5019 bump k8s to 1.30.10
  dist/images/Dockerfile.base
  dist/images/go-deps/download-go-deps.sh
  go.mod
  go.sum
Labels: security, dependencies, size:M

#5021 bfd: fix bfdd-control setting mintx/minrx
  dist/images/bfdd-prestart.sh
Labels: bug, size:XS

#5025 add gc interval
  dist/images/install.sh
  kubeovn-helm/templates/controller-deploy.yaml
  kubeovn-helm/values.yaml
  pkg/controller/config.go
  pkg/controller/controller.go
Labels: size:S, lgtm

#5020 fix rerun the completed vmiMigration
  pkg/controller/kubevirt.go
Labels: bug, size:XS, lgtm

#5026 fix rerun the completed vim migration (#5020)
  pkg/controller/kubevirt.go
Labels: bug, size:XS

#5037 ci: remove legacy network policy e2e
  .github/workflows/build-x86-image.yaml
Labels: network policy, github_actions, size:L
