Repository kubeovn/kube-ovn, pull requests merged in 2025-06, with the labels that each got.

#5294 feat(controller): add database health check
  mocks/pkg/ovs/interface.go
  pkg/controller/controller.go
  pkg/ovs/interface.go
Labels: feature, size:M, lgtm

#5303 tls: rotate self-signed key/certificate
  go.mod
  pkg/metrics/dynamic_cert_key.go
  pkg/metrics/server.go
Labels: security, go, size:L

#5311 chore: release branch automate security updates
  renovate.json
Labels: size:XS

#5320 [BUG] Request Latency 99th Quantile series labels are not unique
  dist/monitoring/controller-grafana.json
Labels: bug, size:XS, lgtm

#5323 bump go to 1.23.10
  dist/images/Dockerfile.base
  go.mod
  go.sum
Labels: dependencies, go, size:S

#5322 bump go to 1.23.10
  dist/images/Dockerfile.base
  go.mod
  go.sum
  test/anp/go.mod
  test/anp/go.sum
Labels: dependencies, go, size:S

#5321 bump go to 1.24.4
  dist/images/Dockerfile.base
  go.mod
  go.sum
  test/anp/go.mod
  test/anp/go.sum
Labels: dependencies, go, size:M

#5278 fix fips not really replace
  dist/images/Dockerfile.base
  dist/images/openssl/openssl.cnf
Labels: bug, size:L, lgtm

#5334 merge dad check to 1.12
  test/e2e/kube-ovn/underlay/underlay.go
Labels: test, size:XS, lgtm

#5336 pod has multi nic in the same subnet, but release all
  pkg/controller/ip.go
  pkg/controller/pod.go
  pkg/controller/vip.go
  pkg/ipam/ipam.go
Labels: bug, size:S, lgtm

#5331 base: build openssl fips module from deb source
  .github/workflows/build-kube-ovn-base.yaml
  .github/workflows/build-x86-image.yaml
  dist/images/Dockerfile.base
Labels: security, size:M, lgtm

#5346 fix sts/vm lsp in incorrect port groups after rescheduled to another node
  mocks/pkg/ovs/interface.go
  pkg/controller/node.go
  pkg/controller/pod.go
  pkg/controller/subnet.go
  pkg/ovs/interface.go
  pkg/ovs/ovn-nb-port_group.go
  pkg/ovs/ovn-nb-port_group_test.go
  pkg/ovs/ovn-nb-suite_test.go
Labels: bug, size:L

#5350 add return for enqueueUpdateIP error
  pkg/controller/ip.go
Labels: go, size:XS, lgtm

#5348 fix vpc egress gateway not applied to new pods
  pkg/controller/vpc_egress_gateway.go
Labels: bug, vpc, size:S

#5351 controller: migrate acl tier after upgrade
  mocks/pkg/ovs/interface.go
  pkg/controller/init.go
  pkg/ovs/interface.go
  pkg/ovs/ovn-nb-acl.go
Labels: bug, need backport, network policy, size:M, lgtm

#5371 fix: add validation to prevent subnet and VPC with the same name
  pkg/util/validator.go
  pkg/util/validator_test.go
Labels: bug, size:M

#5364 fix ip cr not delete with pod in the case of subnet not exist
  pkg/controller/gc.go
  pkg/controller/pod.go
Labels: bug, size:M, lgtm

#5368 base: remove unused packages
  dist/images/Dockerfile.base
Labels: size:M

#5370 vpc egress gateway: drop traffic if no nexthop is available
  pkg/controller/vpc_egress_gateway.go
  pkg/util/const.go
Labels: vpc, size:L

#5375 fix(slr): switchlbrule doesn't support multi-homed/ipv6-first pods
  pkg/controller/endpoint_slice.go
Labels: bug, need backport, size:S

#5156 feature: perform duplicate address detection if ipv6 address has a dadfailed flag
  dist/images/openssl/openssl.cnf
  go.mod
  go.sum
  kind.mk
  pkg/daemon/config.go
  pkg/daemon/ovs_linux.go
  pkg/util/ndp.go
  test/e2e/framework/docker/container.go
  test/e2e/kube-ovn/underlay/underlay.go
Labels: feature, go, size:XL, lgtm

#5380 fix(slr): deleting old entries from ipmapping to avoid clogging loadbalancer
  pkg/ovs/ovn-nb-load_balancer.go
Labels: bug, size:M, lgtm

#5385 u2o keep src flow should consider multi-vlan on the same provider
  pkg/daemon/controller_linux.go
  pkg/ovs/ovs-ofctl.go
Labels: size:M, lgtm

#5388 fix migrate down time
  pkg/controller/kubevirt.go
Labels: bug, size:XS, lgtm

#5391 wrong code
  pkg/controller/pod.go
Labels: bug, size:XS, lgtm

#5390 release vm ip when vm is stopped then deleted
  charts/kube-ovn-v2/templates/rbac/ovn-CR.yaml
  charts/kube-ovn/templates/ovn-CR.yaml
  dist/images/install.sh
  pkg/controller/controller.go
  pkg/controller/kubevirt.go
  pkg/informer/kubevirt.go
  pkg/util/const.go
Labels: bug, size:L, lgtm

#5399 Introduce kt cloud to USERS.md
  USERS.md
Labels: docs, size:XS

#5397 fix(services): SLRs could not target VM endpoints
  pkg/controller/endpoint_slice.go
  pkg/controller/endpoint_slice_test.go
  pkg/util/const.go
Labels: bug, size:L, lgtm

#5402 fix matching ipv6 loopback addresses
  pkg/daemon/config.go
Labels: bug, need backport, size:XS, lgtm

#5404 feat(endpoints): auto-detect provider to adjust ip mapping
  pkg/controller/endpoint_slice.go
  pkg/controller/endpoint_slice_test.go
  pkg/util/const.go
Labels: feature, size:L, lgtm
