Repository kubeovn/kube-ovn, pull requests merged in 2025-05, with the labels that each got.

#5199 fix nil pointer
  pkg/ovs/ovn-nb-logical_router_route.go
Labels: bug, go, size:XS, lgtm

#5200 fix
  pkg/ovs/ovn-nb-logical_router_route.go
Labels: size:XS, lgtm

#5202 vpc egress gateway: fix invalid route destination
  .github/workflows/build-x86-image.yaml
  dist/images/init-vpc-egress-gateway.sh
  pkg/util/pod_routes.go
  pkg/util/pod_routes_test.go
Labels: bug, vpc, size:M, lgtm

#5206 base: use local patch files
  .github/workflows/build-x86-image.yaml
  .github/workflows/release-chart.yaml
  .github/workflows/scheduled-e2e.yaml
  dist/images/Dockerfile.base
  dist/images/Dockerfile.base-dpdk
  dist/images/patches/03e35ed9c5b4de0fa8acbc2c057cdd5957a8d605.patch
  dist/images/patches/1b31f07dc60c016153fa35d936cdda0e02e58492.patch
  dist/images/patches/3f3e3a436ff5eb2eaafbeeae8ea9dc0c514fe8a3.patch
  dist/images/patches/4228eab1d722087ba795e310eadc9e25c4513ec1.patch
  dist/images/patches/44229317de74d1e97f7499b371a86c015be6b7a6.patch
  dist/images/patches/49834fdd3fa3b066650bc8b7a8b05a773d217d95.patch
  dist/images/patches/505dc82f54d4ce54e0378fd3bac1052ee644ac59.patch
  dist/images/patches/53d961492036f1d41d9d1b04bab628375a9c6eb5.patch
  dist/images/patches/54056ea65dc28aa1c4c721a2a34d7913f79f8376.patch
  dist/images/patches/54b767822916606dbb78335a3197983f435b5b8a.patch
  dist/images/patches/5593e614e51a5dce28941e5bf760f9ee5397cede.patch
  dist/images/patches/6b4dcb311f171d81a5d40ea51a273fc356c123db.patch
  dist/images/patches/786756870f12ac69a5d7bc498693574c6591c5e9.patch
  dist/images/patches/a6cb8215a80635129e4fada4c0d25c25fb746bf7.patch
  dist/images/patches/b3af07690e7b2328c02318b1bd812c5665c0632b.patch
  dist/images/patches/b973ec477b43df1c3ef3cdb69f8646948fcf94ae.patch
  dist/images/patches/d088c5d8c263552c5a31d87813991aee30ab74de.patch
  dist/images/patches/d4d76ddb2e12cdd9e73bb5e008ebb9fd1b4d6ca6.patch
  dist/images/patches/e490f5ac0b644101913c2a3db8e03d85e859deff.patch
  dist/images/patches/e7d3ba53cdcbc524bb29c54ddb07b83cc4258ed7.patch
  dist/images/patches/f4b1f5fbf0f5aff68299efaa2d0577c90cb2568e.patch
  dist/images/patches/f627b7721ec282f2edaf798913b1559b939687f0.patch
  dist/images/patches/f9e97031b56ab5747b5d73629198331a6daacdfd.patch
  dist/images/patches/ffd2328d4a55271569e2b89e54a2c18f4e186af8.patch
Labels: size:XXL, lgtm

#5201 base: use local patch files
  dist/images/Dockerfile.base
  dist/images/Dockerfile.base-dpdk
  dist/images/patches/03e35ed9c5b4de0fa8acbc2c057cdd5957a8d605.patch
  dist/images/patches/1b31f07dc60c016153fa35d936cdda0e02e58492.patch
  dist/images/patches/3f3e3a436ff5eb2eaafbeeae8ea9dc0c514fe8a3.patch
  dist/images/patches/4228eab1d722087ba795e310eadc9e25c4513ec1.patch
  dist/images/patches/44229317de74d1e97f7499b371a86c015be6b7a6.patch
  dist/images/patches/49834fdd3fa3b066650bc8b7a8b05a773d217d95.patch
  dist/images/patches/505dc82f54d4ce54e0378fd3bac1052ee644ac59.patch
  dist/images/patches/53d961492036f1d41d9d1b04bab628375a9c6eb5.patch
  dist/images/patches/54056ea65dc28aa1c4c721a2a34d7913f79f8376.patch
  dist/images/patches/54b767822916606dbb78335a3197983f435b5b8a.patch
  dist/images/patches/5593e614e51a5dce28941e5bf760f9ee5397cede.patch
  dist/images/patches/6b4dcb311f171d81a5d40ea51a273fc356c123db.patch
  dist/images/patches/786756870f12ac69a5d7bc498693574c6591c5e9.patch
  dist/images/patches/a6cb8215a80635129e4fada4c0d25c25fb746bf7.patch
  dist/images/patches/a9e009136a42cf6d985f97e2bf1ec41df6b5ca29.patch
  dist/images/patches/b3af07690e7b2328c02318b1bd812c5665c0632b.patch
  dist/images/patches/b5e2975eb65f37315545300254fc0f58a9df52b1.patch
  dist/images/patches/b973ec477b43df1c3ef3cdb69f8646948fcf94ae.patch
  dist/images/patches/d088c5d8c263552c5a31d87813991aee30ab74de.patch
  dist/images/patches/d4d76ddb2e12cdd9e73bb5e008ebb9fd1b4d6ca6.patch
  dist/images/patches/e490f5ac0b644101913c2a3db8e03d85e859deff.patch
  dist/images/patches/e7d3ba53cdcbc524bb29c54ddb07b83cc4258ed7.patch
  dist/images/patches/f4b1f5fbf0f5aff68299efaa2d0577c90cb2568e.patch
  dist/images/patches/f627b7721ec282f2edaf798913b1559b939687f0.patch
  dist/images/patches/f9e97031b56ab5747b5d73629198331a6daacdfd.patch
  dist/images/patches/ffd2328d4a55271569e2b89e54a2c18f4e186af8.patch
Labels: size:XXL

#5207 base: use local patch files
  dist/images/Dockerfile.base
  dist/images/Dockerfile.base-dpdk
  dist/images/patches/06f5a7c684a6030036e2663eecf934b37c3e666e.patch
  dist/images/patches/119ab5c7e104d25641cdf4506a359c5729acdd9a.patch
  dist/images/patches/181680672eb74e150f8244361468e63167aaea46.patch
  dist/images/patches/1ea964886da774506962d6bf23f8f894d93a10eb.patch
  dist/images/patches/25d71867370c9a44c66b973556338de7a4d9bad7.patch
  dist/images/patches/2eaaf89fbf3ee2172719ed10d045fd79900edc8e.patch
  dist/images/patches/31f736fb54cf00e893a23e396958883f54f4080f.patch
  dist/images/patches/3605f81a3b9dc4408d4eb82606a926d54666c6a7.patch
  dist/images/patches/40d5597a9a3a09015dda2202f6aa81791c5c03f3.patch
  dist/images/patches/44875725ad6ce3cb38e4d471d540fe69ed204bff.patch
  dist/images/patches/4ad8763f707ff4088ae61396c7931e8735f71f22.patch
  dist/images/patches/54cbe0d1ba2051e640dd3e53498f373362547691.patch
  dist/images/patches/6934f1a1eb5986a904eefb560c0d6d57811453d9.patch
  dist/images/patches/6a4dd2f4b9311a227cc26fef7c398ae9b241311b.patch
  dist/images/patches/79180bb0a90a44f73f8c985c4f2f3b5afbc09dc5.patch
  dist/images/patches/8af8751cdb55f582c675db921f2526b06fd3d8c0.patch
  dist/images/patches/da1388ece89b27012d081c31310fd577b036b071.patch
  dist/images/patches/ebf61515da71fa2e23125a92859fbdb96dcbffe7.patch
  dist/images/patches/f52c239f5ded40b503e4d217f916b46ca413da4c.patch
  dist/images/patches/f9048a894c019cd4cf5587d40cc07054da60ec81.patch
Labels: size:XXL

#5209 bump go to 1.23.8
  dist/images/Dockerfile.base
  go.mod
  go.sum
Labels: dependencies, go, size:S

#5208 base: use local patch files
  .github/workflows/build-arm64-image.yaml
  .github/workflows/build-x86-image.yaml
  .github/workflows/changelog.yaml
  dist/images/Dockerfile.base
  dist/images/Dockerfile.base-dpdk
  dist/images/patches/03a46942b9e14d77a23313c193fe062ccafa4769.patch
  dist/images/patches/0664cbe47d1684ca5b7147e3449779635454970e.patch
  dist/images/patches/168a3f20579b720370f137c82c04cf3b1a9811e2.patch
  dist/images/patches/1792621bf33a661d66ca47620871668267e3e521.patch
  dist/images/patches/22ea22c40b46ee5adeae977ff6cfca81b3ff25d7.patch
  dist/images/patches/28ee0fc71cd4256fc422fff30d13e2aa0028cfca.patch
  dist/images/patches/2d6823753c295411ac63a66d1d1c5a5d8ba57bdc.patch
  dist/images/patches/3cf5c5236494b5f54dd2c363f2b547f9d90b372d.patch
  dist/images/patches/472809ebc83588cf321935804f171b271fd81476.patch
  dist/images/patches/6a4dd2f4b9311a227cc26fef7c398ae9b241311b.patch
  dist/images/patches/8b5084a55ca3f68f46530f43310ae2eae74322d2.patch
  dist/images/patches/9bce4a9bced0d699ebbb2893bc68448bb0243846.patch
  dist/images/patches/ab0818fed95fa3633f8c52e4afb1f8c19ff5ef1f.patch
  dist/images/patches/b721a251dadfb0857a2aebe32611d18ca935421f.patch
  dist/images/patches/bef703ef862fbbf8740b8d5bf6ca8df9ed617da5.patch
  dist/images/patches/c1d265adc1b148a4c3fb07b9e1b172e1fdf99be4.patch
  dist/images/patches/dca043b2c35756fd370214fc40d61f755bd3a66f.patch
  dist/images/patches/e3ed5ec298e2427b77dd2252e8c2218894e45220.patch
  dist/images/patches/f52c239f5ded40b503e4d217f916b46ca413da4c.patch
  dist/images/patches/f61283c8934589fe6de2b1e86041204dfc31a3e3.patch
  dist/images/patches/f9ad910c8036dc138e52738c400ddcca7236337e.patch
Labels: size:XXL

#5215 bump go to 1.23.9
  .github/workflows/build-windows.yaml
  .github/workflows/build-x86-image.yaml
  dist/images/Dockerfile.base
  go.mod
  go.sum
  test/anp/go.mod
  test/anp/go.sum
Labels: dependencies, go, size:M, lgtm

#5214 bump go to 1.24.3
  .github/workflows/build-windows.yaml
  .github/workflows/build-x86-image.yaml
  Makefile
  dist/images/Dockerfile.base
  go.mod
  go.sum
  hack/update-codegen-docker.sh
  test/anp/go.mod
  test/anp/go.sum
Labels: dependencies, go, size:M, lgtm

#5219 fix cve
  go.mod
  go.sum
Labels: security, go, size:M

#5222 fix cve about containernetworking/plugins v1.5.1
  go.mod
  go.sum
Labels: security, go, size:XS

#5226 ci: fix cilium chaining with underlay networking
  Makefile
Labels: ci, need backport, size:XS

#5227 fix docker cve
  go.mod
  go.sum
Labels: security, dependencies, size:XS

#5228 We've seen instances of a VPC being left with a now-deleted subnet on its status field.
  pkg/controller/vpc.go
Labels: bug, need backport, vpc, size:XS, lgtm

#5229 simple vip
  charts/kube-ovn-v2/crds/kube-ovn-crd.yaml
  charts/kube-ovn/templates/kube-ovn-crd.yaml
  dist/images/install.sh
  pkg/apis/kubeovn/v1/vip.go
  pkg/controller/vip.go
  test/e2e/framework/vip.go
  test/e2e/vip/e2e_test.go
Labels: size:L, lgtm

#5141 Deleting FIP sets EIP to ready
  pkg/controller/ovn_eip.go
Labels: size:S, lgtm

#5218 log show handle pod elapsed time
  pkg/controller/pod.go
Labels: bug, size:M, lgtm

#5235 vpc egress gateway: set minimum replicas to zero
  charts/kube-ovn-v2/crds/kube-ovn-crd.yaml
  charts/kube-ovn/templates/kube-ovn-crd.yaml
  dist/images/install.sh
Labels: vpc, chart, size:XS, lgtm

#5238 Feature/x requirements log permission
  cmd/controller/controller.go
  cmd/daemon/cniserver.go
  cmd/ovn_ic_controller/ovn_ic_controller.go
  cmd/ovn_monitor/ovn_monitor.go
  cmd/pinger/pinger.go
  cmd/speaker/speaker.go
  pkg/controller/config.go
  pkg/daemon/config.go
  pkg/ovn_ic_controller/config.go
  pkg/ovnmonitor/config.go
  pkg/pinger/config.go
  pkg/speaker/config.go
  pkg/util/log.go
Labels: feature, size:M, lgtm

#5217 complile openssl 3.5.0 to support fips
  dist/images/Dockerfile.base
Labels: size:S, lgtm

#5239 fix arm
  dist/images/Dockerfile.base
Labels: bug, size:S

#5240 Revert "fix arm"
  dist/images/Dockerfile.base
Labels: size:S

#5241 Fix fisp arm
  dist/images/Dockerfile.base
Labels: bug, size:S

#5243 Update upgrade-ovs.sh to use POD_NAMESPACE variable for fetching upda…
  dist/images/upgrade-ovs.sh
Labels: bug, need backport, size:XS

#5244 Fix fisp arm
  dist/images/Dockerfile.base
Labels: bug, size:S

#5248 remove fips
  dist/images/Dockerfile.base
Labels: size:S

#5252 fix go bgp cve
  dist/images/Dockerfile.base
  dist/images/go-deps/download-go-deps.sh
  go.mod
  go.sum
Labels: security, go, size:S

#5250 fix handle pod elapsed time
  pkg/controller/pod.go
Labels: bug, need backport, size:S, lgtm

#5232 fix: put iptables nat prerouting rule right before kube-proxy inserted one
  pkg/daemon/gateway_linux.go
Labels: bug, size:L

#5255 cleanup: delete additional ConfigMaps and RoleBindings in cleanup script
  dist/images/cleanup.sh
Labels: need backport, size:XS, lgtm

#5251 bump k8s to v1.32.5
  .github/workflows/build-windows.yaml
  .github/workflows/build-x86-image.yaml
  .github/workflows/scheduled-e2e.yaml
  Makefile
  build.mk
  dist/images/Dockerfile.base
  dist/images/go-deps/download-go-deps.sh
  go.mod
  go.sum
  talos.mk
  test/anp/go.mod
  test/anp/go.sum
  yamls/kind.yaml.j2
Labels: dependencies, go, size:L

#5257 mc bump libovsdb
  go.mod
  go.sum
Labels: dependencies, go, size:XS

#5256 fix Node access underlay pod failed when applying network policy
  pkg/controller/node.go
  test/e2e/framework/iproute/iproute.go
  test/e2e/kube-ovn/underlay/underlay.go
Labels: bug, network policy, size:L, lgtm

#5197 chore(vpc-nat-gw): refactor before adding HA gw
  pkg/controller/gc.go
  pkg/controller/vpc_nat_gateway.go
  pkg/util/net.go
  pkg/util/net_test.go
  pkg/util/vpc_nat_gateway.go
  pkg/util/vpc_nat_gateway_test.go
Labels: refactor, vpc, size:XL, lgtm

#5260 vpc egreess gateway: select workloads by namespace selector and pod selector
  charts/kube-ovn-v2/crds/kube-ovn-crd.yaml
  charts/kube-ovn/templates/kube-ovn-crd.yaml
  dist/images/init-vpc-egress-gateway.sh
  dist/images/install.sh
  pkg/apis/kubeovn/v1/vpc-egress-gateway.go
  pkg/apis/kubeovn/v1/zz_generated.deepcopy.go
  pkg/controller/pod.go
  pkg/controller/subnet.go
  pkg/controller/vpc_egress_gateway.go
  test/e2e/framework/vpc-egress-gateway.go
  test/e2e/vpc-egress-gateway/e2e_test.go
Labels: feature, vpc, size:XL, lgtm

#5263 vpc egress gateway: add traffic policy
  charts/kube-ovn-v2/crds/kube-ovn-crd.yaml
  charts/kube-ovn/templates/kube-ovn-crd.yaml
  dist/images/install.sh
  pkg/apis/kubeovn/v1/vpc-egress-gateway.go
  pkg/controller/controller.go
  pkg/controller/node.go
  pkg/controller/pod.go
  pkg/controller/vpc_egress_gateway.go
  pkg/util/const.go
  test/e2e/vpc-egress-gateway/e2e_test.go
Labels: feature, vpc, size:L, lgtm

#5261 mc bump libovsdb to log rpc client lock or block
  go.mod
  go.sum
Labels: dependencies, go, size:XS

#5264 base: update ovn patches
  dist/images/Dockerfile.base
  dist/images/patches/4a8e051f2fde25ea558e0c4ccb9f5d2f1ea3c018.patch
Labels: need backport, size:S

#5265 bump k8s to v1.31.9
  .github/workflows/build-x86-image.yaml
  build.mk
  dist/images/Dockerfile.base
  dist/images/go-deps/download-go-deps.sh
  go.mod
  go.sum
  talos.mk
  test/anp/go.mod
  test/anp/go.sum
  yamls/kind.yaml.j2
Labels: dependencies, go, size:L

#5277 back port
  pkg/controller/pod.go
  pkg/controller/vip.go
  pkg/daemon/controller_windows.go
  pkg/daemon/tproxy_linux.go
Labels: size:S

#5233 check vlan conflict
  charts/kube-ovn-v2/crds/kube-ovn-crd.yaml
  charts/kube-ovn/templates/kube-ovn-crd.yaml
  dist/images/install.sh
  pkg/apis/kubeovn/v1/vlan.go
  pkg/controller/subnet.go
  pkg/controller/vlan.go
  test/e2e/framework/subnet.go
  test/e2e/framework/vlan.go
  test/e2e/kube-ovn/underlay/underlay.go
Labels: bug, size:L, lgtm

#5268 any vpc can use any external subnet
  pkg/apis/kubeovn/v1/vpc.go
  pkg/controller/external_gw.go
  pkg/controller/vpc.go
Labels: feature, size:L, lgtm

#5275 base: add CAP_NET_ADMIN to traceroute
  dist/images/Dockerfile.base
  test/e2e/kube-ovn/subnet/subnet.go
  test/e2e/vpc-egress-gateway/e2e_test.go
Labels: size:XS, lgtm

#5288 tls: specify cipher suites
  pkg/metrics/server.go
Labels: security, size:S, lgtm

#5289 tls: add options to set tls min/max version and cipher suites
  cmd/controller/controller.go
  cmd/daemon/cniserver.go
  cmd/ovn_monitor/ovn_monitor.go
  cmd/pinger/pinger.go
  cmd/speaker/speaker.go
  pkg/controller/config.go
  pkg/daemon/config.go
  pkg/metrics/server.go
  pkg/metrics/server_test.go
  pkg/ovnmonitor/config.go
Labels: security, size:L, lgtm
