Repository kubeovn/kube-ovn, pull requests merged in 2025-04, with the labels that each got.

#4894 ovn lb select the local chassis's backend prefer
  .github/workflows/build-x86-image.yaml
  Makefile
  charts/kube-ovn/templates/controller-deploy.yaml
  charts/kube-ovn/templates/kube-ovn-crd.yaml
  charts/kube-ovn/templates/ovn-CR.yaml
  charts/kube-ovn/values.yaml
  dist/images/Dockerfile.base
  dist/images/install.sh
  e2e.mk
  go.mod
  go.sum
  mocks/pkg/ovs/interface.go
  pkg/apis/kubeovn/v1/subnet.go
  pkg/controller/config.go
  pkg/controller/endpoint.go
  pkg/controller/init.go
  pkg/controller/service.go
  pkg/daemon/controller.go
  pkg/daemon/controller_linux.go
  pkg/daemon/controller_windows.go
  pkg/ovs/interface.go
  pkg/ovs/ovn-nb-load_balancer.go
  pkg/ovs/ovs-ofctl.go
  pkg/util/const.go
  test/e2e/framework/framework.go
  test/e2e/framework/metallb.go
  test/e2e/metallb/e2e_test.go
Labels: feature, enhancement, size:XXL

#5117 bump go to 1.24.2
  dist/images/Dockerfile.base
  go.mod
  go.sum
  test/anp/go.mod
  test/anp/go.sum
Labels: go, size:M

#5118 update as master
  dist/images/Dockerfile.base-dpdk
Labels: size:M

#5122 gc: consider whether the sts pod is alive during lsp gc
  pkg/controller/gc.go
  pkg/controller/pod.go
Labels: bug, need backport

#5120 Introduce Swisscom to USERS.md
  USERS.md
Labels: docs, size:XS, lgtm

#5124 Fix: IPv6 Link-Local Address Used as Source IP During Pod Initialization
  pkg/daemon/ovs_linux.go
Labels: bug, go, size:M, lgtm

#5129 when dad state not ready should return err
  pkg/daemon/ovs_linux.go
Labels: bug, go, size:XS, lgtm

#5130 build(deps): bump golang.org/x/tools from v0.31.0 to v0.32.0
  go.mod
  go.sum
Labels: dependencies, go, size:S

#5139 base: update ovn patches
  dist/images/Dockerfile.base
  dist/images/Dockerfile.base-dpdk
Labels: need backport, size:M, lgtm

#5136 chart: fix local bin directory host path
  charts/kube-ovn/templates/ovncni-ds.yaml
Labels: bug, need backport, chart, size:XS, lgtm

#5140 fix dbus/NetworkManager connection in Talos
  go.mod
  go.sum
  pkg/daemon/nm_linux.go
  pkg/daemon/ovs_linux.go
  pkg/daemon/ovs_windows.go
  test/anp/go.mod
  test/anp/go.sum
Labels: bug, need backport, go, size:S, lgtm

#5109 ci: add installation test for Talos Linux
  .github/workflows/build-x86-image.yaml
  .gitignore
  Makefile
  build.mk
  e2e.mk
  kind.mk
  talos.mk
  talos/cluster-patch.yaml.j2
  talos/libvirt-domain.xml.j2
  talos/libvirt-network.xml
  talos/machine-patch.yaml.j2
  ut.mk
Labels: ci, size:XXL, lgtm, talos

#5144 Support /32 tunnel-source
  pkg/daemon/config.go
Labels: feature, size:S

#5142 Add Finalizer to FIP before programming FIP into the VPC NT Gateway
  pkg/controller/vpc_nat_gw_nat.go
Labels: vpc, size:S, lgtm

#5150 ci: fix kvm/libvirt installation
  .github/workflows/build-x86-image.yaml
Labels: ci, size:S

#5151 ci: bump golangci-lint to v2.1.1
  .github/workflows/build-x86-image.yaml
Labels: ci, size:XS

#5147 ci: add tests for underlay installation on Talos
  .github/workflows/build-x86-image.yaml
  Makefile
  talos.mk
  talos/machine-patch.yaml.j2
Labels: ci, size:M, lgtm, talos

#5137 chart: fix ovs ipsec keys host path
  charts/kube-ovn/templates/ovncni-ds.yaml
Labels: bug, need backport, chart, size:XS

#5146 add dad e2e
  pkg/daemon/ovs_linux.go
  test/e2e/kube-ovn/underlay/underlay.go
Labels: test, size:L, lgtm

#5155 pinger: add liveness/readiness probes
  charts/kube-ovn/templates/pinger-ds.yaml
  charts/kube-ovn/templates/vpc-nat-config.yaml
  dist/images/install.sh
Labels: chart, size:S, lgtm, pinger

#5148 support k8s host vm vip type
  pkg/controller/gc.go
  pkg/controller/ip.go
  pkg/controller/ovn_eip.go
  pkg/controller/subnet.go
  pkg/controller/vip.go
  pkg/util/const.go
Labels: feature, size:M, lgtm

#5158 fix vpc nat gateway to correctly use subnet mapped attachment network #5157
  pkg/controller/vpc_nat_gateway.go
  pkg/util/subnet.go
Labels: bug, vpc, size:M, lgtm

#5166 controller: ensure ovn route policy is reconciled after node is initialized
  pkg/controller/node.go
  pkg/controller/subnet.go
Labels: bug, need backport, size:XS, lgtm

#5172 fix: clean up garbage lsp
  pkg/controller/node.go
Labels: size:XS, lgtm

#5175 base: update ovn patch
  dist/images/Dockerfile.base
Labels: need backport, size:XS

#5177 ci: ignore cni-server restarts caused by join network check failure
  hack/ci-check-crash.sh
Labels: ci, need backport, size:M

#5176 bump k8s to v1.31.8
  dist/images/Dockerfile.base
  dist/images/go-deps/download-go-deps.sh
  go.mod
  go.sum
Labels: dependencies, go, size:L, lgtm

#5179 Makefile: fix installing dev version on talos
  talos.mk
Labels: bug, size:S

#5178 bump k8s to v1.32.4
  .github/workflows/build-x86-image.yaml
  dist/images/Dockerfile.base
  dist/images/go-deps/download-go-deps.sh
  go.mod
  go.sum
  talos.mk
Labels: dependencies, go, size:L, lgtm

#5183 fix metallb e2e
  test/e2e/metallb/e2e_test.go
Labels: test, size:XS, lgtm

#5186 Makefile: set major/minor version number for the master branch
  e2e.mk
Labels: size:XS

#5191 base: bump cni plugins to v1.7.1
  .github/workflows/build-x86-image.yaml
  Makefile
  dist/images/Dockerfile.base
  dist/images/go-deps/download-go-deps.sh
Labels: dependencies, size:S, lgtm

#5185 bump k8s to v1.30.12
  dist/images/Dockerfile.base
  dist/images/go-deps/download-go-deps.sh
  go.mod
  go.sum
  pkg/daemon/tproxy_linux.go
Labels: dependencies, go, size:L, lgtm

#5196 some fixes for chart v2
  .github/workflows/build-x86-image.yaml
  Makefile
  charts/kube-ovn-v2/README.md
  charts/kube-ovn-v2/templates/central/central-deployment.yaml
  charts/kube-ovn-v2/templates/controller/controller-deployment.yaml
  charts/kube-ovn-v2/templates/ic/ic-controller-deploy.yaml
  charts/kube-ovn-v2/templates/webhook/certificate.yaml
  charts/kube-ovn-v2/values.yaml
  charts/kube-ovn/templates/ic-controller-deploy.yaml
  kind.mk
Labels: chart, size:M

#5194 clean up installation script and chart for dpdk installation
  charts/kube-ovn-v2/README.md
  charts/kube-ovn-v2/templates/ovs-ovn/ovs-ovn-daemonset.yaml
  charts/kube-ovn-v2/templates/ovs-ovn/ovs-ovn-dpdk-daemonset.yaml
  charts/kube-ovn-v2/values.yaml
  charts/kube-ovn/templates/ovn-dpdk-ds.yaml
  charts/kube-ovn/templates/ovsovn-ds.yaml
  charts/kube-ovn/values.yaml
  dist/images/install.sh
  dist/images/start-ovs-dpdk.sh
Labels: chart, size:L, lgtm

#5193 fix ip clean
  pkg/controller/init.go
  pkg/controller/ip.go
Labels: bug, need backport, size:S, lgtm
